/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Function describing the decay time acceptance for the Bs->JpsiKs analysis

#include "Riostream.h" 

#include "LHCbAcceptance.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(LHCbAcceptance) 

 LHCbAcceptance::LHCbAcceptance(const char *name, const char *title, 
                        RooAbsReal& _time,
                        RooAbsReal& _xPar,
                        RooAbsReal& _yPar,
                        RooAbsReal& _zPar,
                        RooAbsReal& _betaPar) :
   RooAbsReal(name,title), 
   time("time","time",this,_time),
   xPar("xPar","xPar",this,_xPar),
   yPar("yPar","yPar",this,_yPar),
   zPar("zPar","zPar",this,_zPar),
   betaPar("betaPar","betaPar",this,_betaPar)
 { 
 } 


 LHCbAcceptance::LHCbAcceptance(const LHCbAcceptance& other, const char* name) :  
   RooAbsReal(other,name), 
   time("time",this,other.time),
   xPar("xPar",this,other.xPar),
   yPar("yPar",this,other.yPar),
   zPar("zPar",this,other.zPar),
   betaPar("betaPar",this,other.betaPar)
 { 
 } 



 Double_t LHCbAcceptance::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 
   const double t(time), x(xPar), y(yPar), z(zPar), beta(betaPar);
   return x*(1.+beta*t)/(1.+pow(z*t,-y));
 } 



