/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROO_GRANETPDF_H
#define ROO_GRANETPDF_H 1

#include "RooAbsPdf.h"
#include "RooRealProxy.h"

class RooRealVar;

class RooGranet : public RooAbsPdf {
public:
  RooGranet() {}
  RooGranet(const char *name, const char *title,
            RooAbsReal& _x, RooAbsReal& _x0,
            RooAbsReal& _A,
            RooAbsReal& _B);
  RooGranet(const RooGranet& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooGranet(*this,newname); }
  inline virtual ~RooGranet() { }

  Int_t getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars,
                              const char* rangeName=0) const ;
  Double_t analyticalIntegral(Int_t code, const char* rangeName=0) const ;

protected:

  RooRealProxy x ;
  RooRealProxy x0 ;
  RooRealProxy A ;
  RooRealProxy B ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooGranet,1) // Your description goes here...
};
 
#endif
