/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

#ifndef RANGEACCEPTANCE
#define RANGEACCEPTANCE

#include "RooAbsReal.h"
#include "RooRealProxy.h"

class RangeAcceptance : public RooAbsReal {
public:
  RangeAcceptance() {} ;
  RangeAcceptance(const char *name, const char *title,
	      RooAbsReal& _x, double _xmin, double _xmax);
  RangeAcceptance(const RangeAcceptance& other, const char* name=0) ;
  TObject* clone(const char* newname) const override { return new RangeAcceptance(*this,newname); }
  virtual ~RangeAcceptance();

protected:

  RooRealProxy x;
  double xmin;
  double xmax;

  Double_t evaluate() const override;

private:
  ClassDef(RangeAcceptance, 1);
};

#endif
