###########################################################################################################################################
## P2VVImports                                                                                                                           ##
##                                                                                                                                       ##
## authors':                                                                                                                             ##
##   JvL, Jeroen van Leerdam, Nikhef, j.van.leerdam@nikhef.nl                                                                            ##
##                                                                                                                                       ##
###########################################################################################################################################


# parameter names dictionary:  'P2VV internal name' : ( 'text name', 'LaTeX name' )
parNames = {  'phiCP'                     : ( 'phi_s',                       '$\\phi_\\text{s}$'                          )
            , '__phiCP__'                 : ( 'phi_s (b)'                    '$\\phi_\\text{s}$ (b)'                      )
            , 'lambdaCP'                  : ( '|lambda_s|',                  '$|\\lambda_\\text{s}|$'                     )
            , 'Gamma'                     : ( 'Gamma_s',                     '$\\Gamma_\\text{s}$'                        )
            , 'dGamma'                    : ( 'Delta Gamma_s',               '$\\Delta\\Gamma_\\text{s}$'                 )
            , '__dGamma__'                : ( 'Delta Gamma_s (b)',           '$\\Delta\\Gamma_\\text{s}$ (b)'             )
            , 'dM'                        : ( 'Delta m_s',                   '$\\Delta m_\\text{s}$'                      )
            , 'A0Mag2'                    : ( '|A_0|^2',                     '$|A_0|^2$'                                  )
            , 'AperpMag2'                 : ( '|A_perp|^2',                  '$|A_\\perp|^2$'                             )
            , 'f_S'                       : ( 'F_S',                         '$F_\\text{S}$'                              )
            , 'f_S_bin0'                  : ( 'F_S_0',                       '${F_\\text{S}}_0$'                          )
            , 'f_S_bin1'                  : ( 'F_S_1',                       '${F_\\text{S}}_1$'                          )
            , 'f_S_bin2'                  : ( 'F_S_2',                       '${F_\\text{S}}_2$'                          )
            , 'f_S_bin3'                  : ( 'F_S_3',                       '${F_\\text{S}}_3$'                          )
            , 'f_S_bin4'                  : ( 'F_S_4',                       '${F_\\text{S}}_4$'                          )
            , 'f_S_bin5'                  : ( 'F_S_5',                       '${F_\\text{S}}_5$'                          )
            , 'AparPhase'                 : ( 'delta_para - delta_0',        '$\\delta_\\parallel-\\delta_0$'             )
            , 'AperpPhase'                : ( 'delta_perp - delta_0',        '$\\delta_\\perp-\\delta_0$'                 )
            , 'ASOddPhase'                : ( 'delta_S - delta_perp',        '$\\delta_\\text{S}-\\delta_\\perp$'         )
            , 'ASOddPhase_bin0'           : ( 'delta_S_0 - delta_perp',      '${\\delta_\\text{S}}_0-\\delta_\\perp$'     )
            , 'ASOddPhase_bin1'           : ( 'delta_S_1 - delta_perp',      '${\\delta_\\text{S}}_1-\\delta_\\perp$'     )
            , 'ASOddPhase_bin2'           : ( 'delta_S_2 - delta_perp',      '${\\delta_\\text{S}}_2-\\delta_\\perp$'     )
            , 'ASOddPhase_bin3'           : ( 'delta_S_3 - delta_perp',      '${\\delta_\\text{S}}_3-\\delta_\\perp$'     )
            , 'ASOddPhase_bin4'           : ( 'delta_S_4 - delta_perp',      '${\\delta_\\text{S}}_4-\\delta_\\perp$'     )
            , 'ASOddPhase_bin5'           : ( 'delta_S_5 - delta_perp',      '${\\delta_\\text{S}}_5-\\delta_\\perp$'     )
            , 'timeResSigmaSF'            : ( 'sigma_t',                     '$\\sigma_t$ s.f.'                           )
            , 'wTagP0OS'                  : ( 'p_0 OS',                      '$p_0$ OS'                                   )
            , 'wTagP1OS'                  : ( 'p_1 OS',                      '$p_1$ OS'                                   )
            , 'wTagDelP0OS'               : ( 'Delta p_0 OS',                '$\\Delta p_0$ OS'                           )
            , 'wTagP0SS'                  : ( 'p_0 SS',                      '$p_0$ SS'                                   )
            , 'wTagP1SS'                  : ( 'p_1 SS',                      '$p_1$ SS'                                   )
            , 'wTagDelP0SS'               : ( 'Delta p_1 SS',                '$\\Delta p_0$ SS'                           )
            , 'N_sigMass'                 : ( 'N_sig',                       '$N_\\text{sig}$'                            )
            , 'N_sigMass_bin0'            : ( 'N_sig_0',                     '${N_\\text{sig}}_0$'                        )
            , 'N_sigMass_bin1'            : ( 'N_sig_1',                     '${N_\\text{sig}}_1$'                        )
            , 'N_sigMass_bin2'            : ( 'N_sig_2',                     '${N_\\text{sig}}_2$'                        )
            , 'N_sigMass_bin3'            : ( 'N_sig_3',                     '${N_\\text{sig}}_3$'                        )
            , 'N_sigMass_bin4'            : ( 'N_sig_4',                     '${N_\\text{sig}}_4$'                        )
            , 'N_sigMass_bin5'            : ( 'N_sig_5',                     '${N_\\text{sig}}_5$'                        )
            , 'N_sigMass_{notExclB;bin0}' : ( 'N_sig_U0',                    '${N_\\text{sig}}_{U0}$'                     )
            , 'N_sigMass_{notExclB;bin1}' : ( 'N_sig_U1',                    '${N_\\text{sig}}_{U1}$'                     )
            , 'N_sigMass_{notExclB;bin2}' : ( 'N_sig_U2',                    '${N_\\text{sig}}_{U2}$'                     )
            , 'N_sigMass_{notExclB;bin3}' : ( 'N_sig_U3',                    '${N_\\text{sig}}_{U3}$'                     )
            , 'N_sigMass_{notExclB;bin4}' : ( 'N_sig_U4',                    '${N_\\text{sig}}_{U4}$'                     )
            , 'N_sigMass_{notExclB;bin5}' : ( 'N_sig_U5',                    '${N_\\text{sig}}_{U5}$'                     )
            , 'N_sigMass_{exclB;bin0}'    : ( 'N_sig_B0',                    '${N_\\text{sig}}_{B0}$'                     )
            , 'N_sigMass_{exclB;bin1}'    : ( 'N_sig_B1',                    '${N_\\text{sig}}_{B1}$'                     )
            , 'N_sigMass_{exclB;bin2}'    : ( 'N_sig_B2',                    '${N_\\text{sig}}_{B2}$'                     )
            , 'N_sigMass_{exclB;bin3}'    : ( 'N_sig_B3',                    '${N_\\text{sig}}_{B3}$'                     )
            , 'N_sigMass_{exclB;bin4}'    : ( 'N_sig_B4',                    '${N_\\text{sig}}_{B4}$'                     )
            , 'N_sigMass_{exclB;bin5}'    : ( 'N_sig_B5',                    '${N_\\text{sig}}_{B5}$'                     )
            , 'N_bkgMass'                 : ( 'N_bkg',                       '$N_\\text{bkg}$'                            )
            , 'N_bkgMass_bin0'            : ( 'N_bkg_0',                     '${N_\\text{bkg}}_0$'                        )
            , 'N_bkgMass_bin1'            : ( 'N_bkg_1',                     '${N_\\text{bkg}}_1$'                        )
            , 'N_bkgMass_bin2'            : ( 'N_bkg_2',                     '${N_\\text{bkg}}_2$'                        )
            , 'N_bkgMass_bin3'            : ( 'N_bkg_3',                     '${N_\\text{bkg}}_3$'                        )
            , 'N_bkgMass_bin4'            : ( 'N_bkg_4',                     '${N_\\text{bkg}}_4$'                        )
            , 'N_bkgMass_bin5'            : ( 'N_bkg_5',                     '${N_\\text{bkg}}_5$'                        )
            , 'N_bkgMass_{notExclB;bin0}' : ( 'N_bkg_U0',                    '${N_\\text{bkg}}_{U0}$'                     )
            , 'N_bkgMass_{notExclB;bin1}' : ( 'N_bkg_U1',                    '${N_\\text{bkg}}_{U1}$'                     )
            , 'N_bkgMass_{notExclB;bin2}' : ( 'N_bkg_U2',                    '${N_\\text{bkg}}_{U2}$'                     )
            , 'N_bkgMass_{notExclB;bin3}' : ( 'N_bkg_U3',                    '${N_\\text{bkg}}_{U3}$'                     )
            , 'N_bkgMass_{notExclB;bin4}' : ( 'N_bkg_U4',                    '${N_\\text{bkg}}_{U4}$'                     )
            , 'N_bkgMass_{notExclB;bin5}' : ( 'N_bkg_U5',                    '${N_\\text{bkg}}_{U5}$'                     )
            , 'N_bkgMass_{exclB;bin0}'    : ( 'N_bkg_B0',                    '${N_\\text{bkg}}_{B0}$'                     )
            , 'N_bkgMass_{exclB;bin1}'    : ( 'N_bkg_B1',                    '${N_\\text{bkg}}_{B1}$'                     )
            , 'N_bkgMass_{exclB;bin2}'    : ( 'N_bkg_B2',                    '${N_\\text{bkg}}_{B2}$'                     )
            , 'N_bkgMass_{exclB;bin3}'    : ( 'N_bkg_B3',                    '${N_\\text{bkg}}_{B3}$'                     )
            , 'N_bkgMass_{exclB;bin4}'    : ( 'N_bkg_B4',                    '${N_\\text{bkg}}_{B4}$'                     )
            , 'N_bkgMass_{exclB;bin5}'    : ( 'N_bkg_B5',                    '${N_\\text{bkg}}_{B5}$'                     )
            , 'm_sig_frac'                : ( 'f_mass_1',                    '${f_1}_\\text{mass}$'                       )
            , 'm_sig_mean'                : ( 'mu_mass',                     '$\\mu_\\text{mass}$'                        )
            , 'm_sig_sigma_sf'            : ( 'sigma_mass 2:1 SF',           '$\\text{SF}_{2:1}\\ \\sigma_\\text{mass}$'  )
            , 'm_sig_sigma_1'             : ( 'sigma_mass_1',                '${\\sigma_1}_\\text{mass}$'                 )
            , 'm_sig_sigma_2'             : ( 'sigma_mass_2',                '${\\sigma_2}_\\text{mass}$'                 )
            , 'm_sig_widthPar0'           : ( 'width_par_mass_0',            '${\\text{width}_0}_\\text{mass}$'           )
            , 'm_sig_widthPar1'           : ( 'width_par_mass_1',            '${\\text{width}_1}_\\text{mass}$'           )
            , 'm_sig_widthPar2'           : ( 'width_par_mass_2',            '${\\text{width}_2}_\\text{mass}$'           )
            , 'm_bkg_exp'                 : ( 'alpha_mass',                  '$\\alpha_\\text{mass}$'                     )
            , 'm_bkg_exp_bin0'            : ( 'alpha_mass_0',                '${\\alpha_\\text{mass}}_0$'                 )
            , 'm_bkg_exp_bin1'            : ( 'alpha_mass_1',                '${\\alpha_\\text{mass}}_1$'                 )
            , 'm_bkg_exp_bin2'            : ( 'alpha_mass_2',                '${\\alpha_\\text{mass}}_2$'                 )
            , 'm_bkg_exp_bin3'            : ( 'alpha_mass_3',                '${\\alpha_\\text{mass}}_3$'                 )
            , 'm_bkg_exp_bin4'            : ( 'alpha_mass_4',                '${\\alpha_\\text{mass}}_4$'                 )
            , 'm_bkg_exp_bin5'            : ( 'alpha_mass_5',                '${\\alpha_\\text{mass}}_5$'                 )
            , 'm_bkg_arg'                 : ( 'alpha_mass',                  '$\\alpha_\\text{mass}$'                     )
            , 'm_bkg_arg_bin0'            : ( 'alpha_mass_0',                '${\\alpha_\\text{mass}}_0$'                 )
            , 'm_bkg_arg_bin1'            : ( 'alpha_mass_1',                '${\\alpha_\\text{mass}}_1$'                 )
            , 'm_bkg_arg_bin2'            : ( 'alpha_mass_2',                '${\\alpha_\\text{mass}}_2$'                 )
            , 'm_bkg_arg_bin3'            : ( 'alpha_mass_3',                '${\\alpha_\\text{mass}}_3$'                 )
            , 'm_bkg_arg_bin4'            : ( 'alpha_mass_4',                '${\\alpha_\\text{mass}}_4$'                 )
            , 'm_bkg_arg_bin5'            : ( 'alpha_mass_5',                '${\\alpha_\\text{mass}}_5$'                 )
           }

# nominal values of physics parameters
parValues = {  'phiCP'           : (  6.8319e-02,  9.10e-02, -1.       )
             , 'lambdaCP'        : (  9.4325e-01,  3.07e-02, -1.       )
             , 'Gamma'           : (  6.7136e-01,  4.80e-03, -1.       )
             , 'dGamma'          : (  1.0023e-01,  1.62e-02, -1.       )
             , 'dM'              : (  1.7666e+01,  7.67e-02, -1.       )
             , 'A0Mag2'          : (  5.2112e-01,  6.08e-03, -1.       )
             , 'AperpMag2'       : (  2.4854e-01,  8.65e-03, -1.       )
             , 'f_S_bin0'        : (  2.2680e-01,  7.73e-02, -1.       )
             , 'f_S_bin1'        : (  6.6880e-02,  2.86e-02, -1.       )
             , 'f_S_bin2'        : (  7.8550e-03,  1.17e-02, -1.       )
             , 'f_S_bin3'        : (  1.6331e-02,  1.07e-02, -1.       )
             , 'f_S_bin4'        : (  5.4786e-02,  2.63e-02, -1.       )
             , 'f_S_bin5'        : (  1.6738e-01,  4.25e-02, -1.       )
             , 'AparPhase'       : (  3.2984,     -0.206029,  0.129595 )
             , 'AperpPhase'      : (  3.0694,      2.17e-01, -1.       )
             , 'ASOddPhase_bin0' : (  1.3139,     -0.489581,  0.781625 )
             , 'ASOddPhase_bin1' : (  7.6908e-01, -0.232555,  0.383645 )
             , 'ASOddPhase_bin2' : (  5.0846e-01, -0.305175,  1.39871  )
             , 'ASOddPhase_bin3' : ( -5.0756e-01, -0.352498,  0.211829 )
             , 'ASOddPhase_bin4' : ( -4.5637e-01, -0.262108,  0.184739 )
             , 'ASOddPhase_bin5' : ( -6.4999e-01, -0.224725,  0.183571 )
             , 'timeResSigmaSF'  : (  1.4497,      5.48e-02, -1.       )
             , 'wTagP0OS'        : (  3.9062e-01,  7.69e-03, -1.       )
             , 'wTagP1OS'        : (  1.0001,      2.29e-02, -1.       )
             , 'wTagDelP0OS'     : (  1.1002e-02,  3.40e-03, -1.       )
             , 'wTagP0SS'        : (  3.6126e-01,  1.59e-02, -1.       )
             , 'wTagP1SS'        : (  1.0182,      1.57e-01, -1.       )
             , 'wTagDelP0SS'     : ( -1.9030e-02,  5.00e-03, -1.       )
             , 'm_sig_mean'      : (  5368.220,    4.84e-02, -1.       )
             , 'm_sig_frac'      : (  7.5966e-01,  3.49e-02, -1.       )
             , 'm_sig_sigma_1'   : (  6.0797,      1.33e-01, -1.       )
             , 'm_sig_sigma_sf'  : (  2.0652,      8.87e-02, -1.       )
             , 'm_sig_widthPar0' : (  1.7415e+01,  1.00,     -1.       )
             , 'm_sig_widthPar1' : ( -5.9840e+01,  1.00,     -1.       )
             , 'm_sig_widthPar2' : (  4.2391e+01,  1.00,     -1.       )
             , 'm_bkg_exp_bin0'  : ( -1.7308e-03,  1.47e-04, -1.       )
             , 'm_bkg_exp_bin1'  : ( -1.7485e-03,  1.77e-04, -1.       )
             , 'm_bkg_exp_bin2'  : ( -1.7361e-03,  1.98e-04, -1.       )
             , 'm_bkg_exp_bin3'  : ( -1.2293e-03,  1.98e-04, -1.       )
             , 'm_bkg_exp_bin4'  : ( -1.5366e-03,  1.55e-04, -1.       )
             , 'm_bkg_exp_bin5'  : ( -1.5861e-03,  9.95e-05, -1.       )
            }

# values of physics parameters with phase space MC angular acceptance
parValuesPHSPAcc = {  'phiCP'           : (  7.0691e-02,  9.08e-02, -1.       )
                    , 'lambdaCP'        : (  9.4518e-01,  2.97e-02, -1.       )
                    , 'Gamma'           : (  6.7113e-01,  4.83e-03, -1.       )
                    , 'dGamma'          : (  1.0038e-01,  1.62e-02, -1.       )
                    , 'dM'              : (  1.7664e+01,  7.70e-02, -1.       )
                    , 'A0Mag2'          : (  5.2531e-01,  6.07e-03, -1.       )
                    , 'AperpMag2'       : (  2.4478e-01,  8.80e-03, -1.       )
                    , 'f_S_bin0'        : (  2.3063e-01, -0.073649,  0.080953 )
                    , 'f_S_bin1'        : (  6.9315e-02, -0.027325,  0.029634 )
                    , 'f_S_bin2'        : (  8.7124e-03, -0.007704,  0.014229 )
                    , 'f_S_bin3'        : (  1.6198e-02, -0.009186,  0.012207 )
                    , 'f_S_bin4'        : (  5.6242e-02, -0.025579,  0.027261 )
                    , 'f_S_bin5'        : (  1.6906e-01, -0.042141,  0.042779 )
                    , 'AparPhase'       : (  3.4047e+00, -0.153221,  0.104434 )
                    , 'AperpPhase'      : (  3.1016e+00,  2.15e-01, -1.       )
                    , 'ASOddPhase_bin0' : (  1.2889e+00, -0.471392,  0.758919 )
                    , 'ASOddPhase_bin1' : (  7.5367e-01, -0.225195,  0.36704  )
                    , 'ASOddPhase_bin2' : (  4.7920e-01, -0.288453,  1.36977  )
                    , 'ASOddPhase_bin3' : ( -5.2024e-01, -0.36217,   0.218655 )
                    , 'ASOddPhase_bin4' : ( -4.5437e-01, -0.25763,   0.183822 )
                    , 'ASOddPhase_bin5' : ( -6.5442e-01, -0.225561,  0.184025 )
                    , 'timeResSigmaSF'  : (  1.4458e+00,  4.53e-02, -1.       )
                    , 'wTagP0OS'        : (  3.9056e-01,  7.69e-03, -1.       )
                    , 'wTagP1OS'        : (  1.0001e+00,  2.29e-02, -1.       )
                    , 'wTagDelP0OS'     : (  1.1008e-02,  3.40e-03, -1.       )
                    , 'wTagP0SS'        : (  3.6112e-01,  1.59e-02, -1.       )
                    , 'wTagP1SS'        : (  1.0189e+00,  1.57e-01, -1.       )
                    , 'wTagDelP0SS'     : ( -1.9023e-02,  5.00e-03, -1.       )
                   }
