/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef MASSK10
#define MASSK10

#include "RooAbsReal.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
#include "TComplex.h"
#include "MassAbsFunc.h"

class MassK10 : public MassAbsFunc {
public:
  MassK10():MassAbsFunc() {} ; 
  MassK10(const char *name, const char *title,
	      RooAbsReal& _m1,
	      RooAbsReal& _m2,
	      RooAbsReal& _Af,
	      RooAbsReal& _df,
	      RooAbsReal& _Ag,
	      RooAbsReal& _dg,
	      RooAbsReal& _Ape,
	      RooAbsReal& _dpe,
	      RooAbsReal& _m_kst,
	      RooAbsReal& _m_kst0,
	      RooAbsReal& _g_kst,
	      RooAbsReal& _g_kst0,
	 RooAbsReal& _m_Bs,
	  RooArgList& _acc_coefList,
	  RooAbsReal& _norm):
    MassAbsFunc(name, title, _m1, _m2,_m_kst, _m_kst0, _g_kst, _g_kst0, _m_Bs, _acc_coefList, _norm),
    Af("Af","Af",this,_Af),
    df("df","df",this,_df),
    Ag("Ag","Ag",this,_Ag),
    dg("dg","dg",this,_dg),
    Ape("Ape","Ape",this,_Ape),
    dpe("dpe","dpe",this,_dpe){}

    MassK10(const MassK10& other, const char* name=0):
      MassAbsFunc(other,name),
      Af("Af",this,other.Af),
      df("df",this,other.df),
      Ag("Ag",this,other.Ag),
      dg("dg",this,other.dg),
      Ape("Ape",this,other.Ape),
      dpe("dpe",this,other.dpe){}

  virtual TObject* clone(const char* newname) const { return new MassK10(*this,newname); }
  inline virtual ~MassK10() { }

protected:

  RooRealProxy Af ;
  RooRealProxy df ;
  RooRealProxy Ag ;
  RooRealProxy dg ;
  RooRealProxy Ape ;
  RooRealProxy dpe ;
  
  Double_t evaluate() const ;

private:

  ClassDef(MassK10,1) // Your description goes here...
};
 
#endif
