/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ANGF4
#define ANGF4

//local include
#include "AngAbsFunc.h"

#include "RooAbsReal.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class AngF4 : public AngAbsFunc {
public:
  AngF4():AngAbsFunc() {} ; 
  AngF4(const char *name, const char *title,
	      RooAbsReal& _c1,
	      RooAbsReal& _c2,
	      RooAbsReal& _ph,
	TH2D& _acc):
    AngAbsFunc(name, title, _c1, _c2, _ph, _acc) { } 

  AngF4(const AngF4& other, const char* name=0):
      AngAbsFunc(other, name) { } 

  virtual TObject* clone(const char* newname) const { return new AngF4(*this,newname); }
  inline virtual ~AngF4() { }

  Double_t integrateBin(Int_t code, double loc1, double hic1, double loc2, double hic2, double loph, double hiph)const;

  Double_t evaluate() const ;


protected:


  ClassDef(AngF4,1) // Your description goes here...
};
 
#endif
