// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.1.4         [262404]
ROOT Release   : 5.34/07       [336391]
Creator        : pseyfert
Date           : Fri Dec 20 21:20:30 2013
Host           : Linux lxbuild175.cern.ch 2.6.18-308.4.1.el5 #1 SMP Wed Apr 18 16:26:27 CEST 2012 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /auto/sigma0/pseyfert/zoontuple/Bender_v22r7/Phys/Tau23Mu/scripts/TMVA_training_v3
Training events: 41107
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 14
TMath::Exp(-1000*LifeTime)    TMath_Exp__M_1000_T_LifeTime_ TMath::Exp(-1000*LifeTime)    transformed decay time        1                                 'F'    [1.93987222119e-11,0.731256723404]
IPSig                         IPSig                         IPSig                         IP significance               1                                 'F'    [0.0111495917663,24.9779434204]
VertexChi2                    VertexChi2                    VertexChi2                    vertex #chi^{2}               1                                 'F'    [0.00189490010962,14.9983968735]
acos(dira)                    acos_dira_                    acos(dira)                    pointing angle                1                                 'F'    [0,0.137716650963]
pt                            pt                            pt                            p_{T}                         [MeV/c]                           'F'    [41.2933425903,37961.9179688]
Laura_SumBDT                  Laura_SumBDT                  Laura_SumBDT                  Laura_SumBDT                                                    'F'    [-2.57286167145,5]
min(p0_IPSig,min(p1_IPSig,p2_IPSig)) min_p0_IPSig,min_p1_IPSig,p2_IPSig__ min(p0_IPSig,min(p1_IPSig,p2_IPSig)) min. #mu IP significance             1                                        'F'    [2.30495882034,102.738922119]
DOCAone                       DOCAone                       DOCAone                       DOCA (#mu 1 and 2)            mm                                'F'    [2.63570382231e-06,0.923672735691]
DOCAtwo                       DOCAtwo                       DOCAtwo                       DOCA (#mu 2 and 3)            mm                                'F'    [2.4348450367e-08,0.744905769825]
DOCAthree                     DOCAthree                     DOCAthree                     DOCA (#mu 1 and 3)            mm                                'F'    [6.10736776707e-07,1.05343544483]
CDF3                          CDF3                          CDF3                          cone isolation                1                                 'F'    [0.00300450995564,1]
p0_track_MatchChi2            p0_track_MatchChi2            p0_track_MatchChi2            track match #chi^{2} (#mu 1)  1                                 'F'    [0.0559116005898,84.5542831421]
p1_track_MatchChi2            p1_track_MatchChi2            p1_track_MatchChi2            track match #chi^{2} (#mu 2)  1                                 'F'    [0.0131226135418,75.9046707153]
p2_track_MatchChi2            p2_track_MatchChi2            p2_track_MatchChi2            track match #chi^{2} (#mu 3)  1                                 'F'    [0.0151327997446,79.3785171509]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 14 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "TMath::Exp(-1000*LifeTime)", "IPSig", "VertexChi2", "acos(dira)", "pt", "Laura_SumBDT", "min(p0_IPSig,min(p1_IPSig,p2_IPSig))", "DOCAone", "DOCAtwo", "DOCAthree", "CDF3", "p0_track_MatchChi2", "p1_track_MatchChi2", "p2_track_MatchChi2" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 0.99999988079071;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 0.99999988079071;
      fVmin[7] = -1;
      fVmax[7] = 0.99999988079071;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 0.99999988079071;
      fVmin[11] = -1;
      fVmax[11] = 1;
      fVmin[12] = -1;
      fVmax[12] = 1;
      fVmin[13] = -1;
      fVmax[13] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][14];
   double fMax_1[3][14];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[14];
   double fVmax[14];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[14];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[20][15];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][20];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 15; fWeights[0] = new double[15]; 
   fLayerSize[1] = 20; fWeights[1] = new double[20]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.228704045717805;
   fWeightMatrix0to1[1][0] = 1.1055186321688;
   fWeightMatrix0to1[2][0] = 0.75619744997056;
   fWeightMatrix0to1[3][0] = 0.718585561955307;
   fWeightMatrix0to1[4][0] = -2.03630775085574;
   fWeightMatrix0to1[5][0] = -0.271547806904243;
   fWeightMatrix0to1[6][0] = -0.464266807575937;
   fWeightMatrix0to1[7][0] = 0.862533129514756;
   fWeightMatrix0to1[8][0] = -0.0449777723244438;
   fWeightMatrix0to1[9][0] = -0.881900653483263;
   fWeightMatrix0to1[10][0] = -1.46960242128039;
   fWeightMatrix0to1[11][0] = 0.236367676583149;
   fWeightMatrix0to1[12][0] = -1.1418720381406;
   fWeightMatrix0to1[13][0] = -0.261031153351524;
   fWeightMatrix0to1[14][0] = -0.357025578561049;
   fWeightMatrix0to1[15][0] = 0.872762130949923;
   fWeightMatrix0to1[16][0] = -0.369039868565282;
   fWeightMatrix0to1[17][0] = 1.13444720380965;
   fWeightMatrix0to1[18][0] = -0.536077403721589;
   fWeightMatrix0to1[0][1] = 1.14263624045135;
   fWeightMatrix0to1[1][1] = 1.58529015200857;
   fWeightMatrix0to1[2][1] = -0.32532805919256;
   fWeightMatrix0to1[3][1] = 0.890179872283328;
   fWeightMatrix0to1[4][1] = -0.709354603301182;
   fWeightMatrix0to1[5][1] = -2.28970035234706;
   fWeightMatrix0to1[6][1] = 0.0361713420748903;
   fWeightMatrix0to1[7][1] = 2.19135461592121;
   fWeightMatrix0to1[8][1] = 0.924849796290174;
   fWeightMatrix0to1[9][1] = -1.45242540709543;
   fWeightMatrix0to1[10][1] = 0.678412242485063;
   fWeightMatrix0to1[11][1] = -1.12693670318777;
   fWeightMatrix0to1[12][1] = 1.46577685191992;
   fWeightMatrix0to1[13][1] = -0.618279084541126;
   fWeightMatrix0to1[14][1] = -0.312537733646996;
   fWeightMatrix0to1[15][1] = 0.602323968961279;
   fWeightMatrix0to1[16][1] = -0.0462934695353708;
   fWeightMatrix0to1[17][1] = -1.31076805719428;
   fWeightMatrix0to1[18][1] = 0.96574204336169;
   fWeightMatrix0to1[0][2] = -0.989299046918678;
   fWeightMatrix0to1[1][2] = 0.296005461957202;
   fWeightMatrix0to1[2][2] = 1.06177118394036;
   fWeightMatrix0to1[3][2] = 0.118294417571899;
   fWeightMatrix0to1[4][2] = 1.60136412009648;
   fWeightMatrix0to1[5][2] = -0.12535439218451;
   fWeightMatrix0to1[6][2] = -0.503072112456139;
   fWeightMatrix0to1[7][2] = -0.246270399045895;
   fWeightMatrix0to1[8][2] = 0.809344380653199;
   fWeightMatrix0to1[9][2] = -0.142228995451234;
   fWeightMatrix0to1[10][2] = 1.32961103690587;
   fWeightMatrix0to1[11][2] = 1.07874283303668;
   fWeightMatrix0to1[12][2] = 1.39676743090983;
   fWeightMatrix0to1[13][2] = 0.864459579187031;
   fWeightMatrix0to1[14][2] = -1.45559365050789;
   fWeightMatrix0to1[15][2] = 0.721046091874783;
   fWeightMatrix0to1[16][2] = -1.59926729523478;
   fWeightMatrix0to1[17][2] = -0.915779608319009;
   fWeightMatrix0to1[18][2] = -0.491685480488632;
   fWeightMatrix0to1[0][3] = -2.22977914180508;
   fWeightMatrix0to1[1][3] = 1.56468082379316;
   fWeightMatrix0to1[2][3] = 1.01048707844516;
   fWeightMatrix0to1[3][3] = -1.63966454355204;
   fWeightMatrix0to1[4][3] = -0.531802975225015;
   fWeightMatrix0to1[5][3] = -1.42722078213109;
   fWeightMatrix0to1[6][3] = 1.07920014674865;
   fWeightMatrix0to1[7][3] = 1.49271526898466;
   fWeightMatrix0to1[8][3] = 0.882848931665264;
   fWeightMatrix0to1[9][3] = -0.96070294162993;
   fWeightMatrix0to1[10][3] = -1.00643078005852;
   fWeightMatrix0to1[11][3] = 0.883877297334162;
   fWeightMatrix0to1[12][3] = -1.00120752803406;
   fWeightMatrix0to1[13][3] = -1.3165856232362;
   fWeightMatrix0to1[14][3] = -1.53363622003335;
   fWeightMatrix0to1[15][3] = 1.02148614666359;
   fWeightMatrix0to1[16][3] = 1.42477998815831;
   fWeightMatrix0to1[17][3] = 0.744457394387246;
   fWeightMatrix0to1[18][3] = -0.7378717217458;
   fWeightMatrix0to1[0][4] = -2.14097180015723;
   fWeightMatrix0to1[1][4] = -1.75710584814353;
   fWeightMatrix0to1[2][4] = 1.36227126798493;
   fWeightMatrix0to1[3][4] = 0.146242296771563;
   fWeightMatrix0to1[4][4] = 1.17638733065465;
   fWeightMatrix0to1[5][4] = 0.669862928043493;
   fWeightMatrix0to1[6][4] = 1.51627137927404;
   fWeightMatrix0to1[7][4] = -0.803856111930507;
   fWeightMatrix0to1[8][4] = -0.678139131279074;
   fWeightMatrix0to1[9][4] = -0.631819948234931;
   fWeightMatrix0to1[10][4] = 0.73954540368677;
   fWeightMatrix0to1[11][4] = -0.600716563188971;
   fWeightMatrix0to1[12][4] = -1.73371242790256;
   fWeightMatrix0to1[13][4] = -1.98086462021508;
   fWeightMatrix0to1[14][4] = -0.479459941252069;
   fWeightMatrix0to1[15][4] = 0.189462134337055;
   fWeightMatrix0to1[16][4] = 1.81022723291227;
   fWeightMatrix0to1[17][4] = -2.03519134501082;
   fWeightMatrix0to1[18][4] = -0.657365412788697;
   fWeightMatrix0to1[0][5] = 1.33531629702949;
   fWeightMatrix0to1[1][5] = 0.319737923687539;
   fWeightMatrix0to1[2][5] = -1.17251327472886;
   fWeightMatrix0to1[3][5] = -1.33864483115469;
   fWeightMatrix0to1[4][5] = -0.349428253656429;
   fWeightMatrix0to1[5][5] = -2.94558596746048;
   fWeightMatrix0to1[6][5] = -1.40565241024656;
   fWeightMatrix0to1[7][5] = 0.24041182120408;
   fWeightMatrix0to1[8][5] = 3.33869259072041;
   fWeightMatrix0to1[9][5] = -1.1197587631567;
   fWeightMatrix0to1[10][5] = 1.29596226539394;
   fWeightMatrix0to1[11][5] = -1.06350549336829;
   fWeightMatrix0to1[12][5] = -0.888722127661246;
   fWeightMatrix0to1[13][5] = -0.486788376485257;
   fWeightMatrix0to1[14][5] = 0.208186284756743;
   fWeightMatrix0to1[15][5] = -1.45986392940574;
   fWeightMatrix0to1[16][5] = 0.516326097782328;
   fWeightMatrix0to1[17][5] = -0.000673017703888934;
   fWeightMatrix0to1[18][5] = -0.0510734038459985;
   fWeightMatrix0to1[0][6] = -1.79896136848345;
   fWeightMatrix0to1[1][6] = -0.329602267140593;
   fWeightMatrix0to1[2][6] = 0.953870725909794;
   fWeightMatrix0to1[3][6] = -0.736233231881166;
   fWeightMatrix0to1[4][6] = -0.00596446603168602;
   fWeightMatrix0to1[5][6] = 1.01244914854086;
   fWeightMatrix0to1[6][6] = -1.0736132917342;
   fWeightMatrix0to1[7][6] = 0.00276447260157716;
   fWeightMatrix0to1[8][6] = -0.779055899475076;
   fWeightMatrix0to1[9][6] = 3.91486316161412;
   fWeightMatrix0to1[10][6] = 0.207248556498353;
   fWeightMatrix0to1[11][6] = 0.799267939736852;
   fWeightMatrix0to1[12][6] = -0.527182048935064;
   fWeightMatrix0to1[13][6] = -0.47310301194566;
   fWeightMatrix0to1[14][6] = -2.12339190541829;
   fWeightMatrix0to1[15][6] = 1.37730236722216;
   fWeightMatrix0to1[16][6] = 0.542601822974686;
   fWeightMatrix0to1[17][6] = -1.74243675004138;
   fWeightMatrix0to1[18][6] = 0.0188241209576227;
   fWeightMatrix0to1[0][7] = -1.86218966207128;
   fWeightMatrix0to1[1][7] = 0.51067638224085;
   fWeightMatrix0to1[2][7] = 1.58868205450527;
   fWeightMatrix0to1[3][7] = 1.42106037606711;
   fWeightMatrix0to1[4][7] = -2.35227963620011;
   fWeightMatrix0to1[5][7] = -0.116362757543289;
   fWeightMatrix0to1[6][7] = 2.01138005342092;
   fWeightMatrix0to1[7][7] = 1.14997486927861;
   fWeightMatrix0to1[8][7] = -0.194316156997442;
   fWeightMatrix0to1[9][7] = -1.06887747284764;
   fWeightMatrix0to1[10][7] = -0.857010012412696;
   fWeightMatrix0to1[11][7] = -1.22305734101579;
   fWeightMatrix0to1[12][7] = 1.38695034481018;
   fWeightMatrix0to1[13][7] = 0.599354817323576;
   fWeightMatrix0to1[14][7] = -0.743532135884096;
   fWeightMatrix0to1[15][7] = -0.196823274522321;
   fWeightMatrix0to1[16][7] = 0.459939882301351;
   fWeightMatrix0to1[17][7] = -1.83355278126885;
   fWeightMatrix0to1[18][7] = 0.227321620453927;
   fWeightMatrix0to1[0][8] = 1.22894392644413;
   fWeightMatrix0to1[1][8] = 0.669545668886338;
   fWeightMatrix0to1[2][8] = 0.00323030361747771;
   fWeightMatrix0to1[3][8] = 0.306244912805837;
   fWeightMatrix0to1[4][8] = 0.207630285341397;
   fWeightMatrix0to1[5][8] = 0.543233850335825;
   fWeightMatrix0to1[6][8] = 1.25999207174569;
   fWeightMatrix0to1[7][8] = -1.26271827962622;
   fWeightMatrix0to1[8][8] = -0.363092917390179;
   fWeightMatrix0to1[9][8] = -0.0790394446358657;
   fWeightMatrix0to1[10][8] = 0.153540543520505;
   fWeightMatrix0to1[11][8] = 0.505819761362798;
   fWeightMatrix0to1[12][8] = 0.787880427298459;
   fWeightMatrix0to1[13][8] = -1.20840150204141;
   fWeightMatrix0to1[14][8] = -0.882973220490458;
   fWeightMatrix0to1[15][8] = 1.36595026705891;
   fWeightMatrix0to1[16][8] = -0.449347472063716;
   fWeightMatrix0to1[17][8] = -1.37028683251475;
   fWeightMatrix0to1[18][8] = 0.886842207973412;
   fWeightMatrix0to1[0][9] = 0.539887540008757;
   fWeightMatrix0to1[1][9] = -0.81591876521227;
   fWeightMatrix0to1[2][9] = 1.97712816789339;
   fWeightMatrix0to1[3][9] = 1.31419510666938;
   fWeightMatrix0to1[4][9] = -2.3204767342763;
   fWeightMatrix0to1[5][9] = 0.512494522852147;
   fWeightMatrix0to1[6][9] = 0.551171779838201;
   fWeightMatrix0to1[7][9] = 0.353807640026348;
   fWeightMatrix0to1[8][9] = -1.41254555623435;
   fWeightMatrix0to1[9][9] = -1.5691752252136;
   fWeightMatrix0to1[10][9] = 0.679042227382999;
   fWeightMatrix0to1[11][9] = 1.7082388018304;
   fWeightMatrix0to1[12][9] = -1.94588559602326;
   fWeightMatrix0to1[13][9] = -0.81282909150744;
   fWeightMatrix0to1[14][9] = -0.846168746614555;
   fWeightMatrix0to1[15][9] = 0.418494893904398;
   fWeightMatrix0to1[16][9] = 2.05638115297625;
   fWeightMatrix0to1[17][9] = -0.633435563261373;
   fWeightMatrix0to1[18][9] = -0.385331714695264;
   fWeightMatrix0to1[0][10] = -0.985129425264807;
   fWeightMatrix0to1[1][10] = -0.483715010691337;
   fWeightMatrix0to1[2][10] = 1.2737501754323;
   fWeightMatrix0to1[3][10] = -0.0816282419351711;
   fWeightMatrix0to1[4][10] = -0.12541920107574;
   fWeightMatrix0to1[5][10] = 0.117175707410819;
   fWeightMatrix0to1[6][10] = -1.57845887187086;
   fWeightMatrix0to1[7][10] = 0.0904312457940649;
   fWeightMatrix0to1[8][10] = -0.0275984247132733;
   fWeightMatrix0to1[9][10] = 0.161464890966844;
   fWeightMatrix0to1[10][10] = 0.0763271807012073;
   fWeightMatrix0to1[11][10] = 0.0829385419601894;
   fWeightMatrix0to1[12][10] = 0.153867458215438;
   fWeightMatrix0to1[13][10] = -1.43844981268686;
   fWeightMatrix0to1[14][10] = 1.35682613892603;
   fWeightMatrix0to1[15][10] = 0.714546406338063;
   fWeightMatrix0to1[16][10] = -0.640769716745303;
   fWeightMatrix0to1[17][10] = -0.148000063548687;
   fWeightMatrix0to1[18][10] = 0.417149262762644;
   fWeightMatrix0to1[0][11] = 0.564031867670812;
   fWeightMatrix0to1[1][11] = 1.78321753111181;
   fWeightMatrix0to1[2][11] = 0.360252802467705;
   fWeightMatrix0to1[3][11] = -1.5379257767599;
   fWeightMatrix0to1[4][11] = -1.76346703983433;
   fWeightMatrix0to1[5][11] = 0.068337765997298;
   fWeightMatrix0to1[6][11] = 1.67175338229798;
   fWeightMatrix0to1[7][11] = 0.953730760685081;
   fWeightMatrix0to1[8][11] = 0.346862945160784;
   fWeightMatrix0to1[9][11] = 0.145597548179509;
   fWeightMatrix0to1[10][11] = -1.97703770822634;
   fWeightMatrix0to1[11][11] = -1.32398759654635;
   fWeightMatrix0to1[12][11] = -0.283443066675833;
   fWeightMatrix0to1[13][11] = -1.63201599373349;
   fWeightMatrix0to1[14][11] = 0.675000756678827;
   fWeightMatrix0to1[15][11] = 2.15025648986054;
   fWeightMatrix0to1[16][11] = -0.820857660655982;
   fWeightMatrix0to1[17][11] = 0.238176175434459;
   fWeightMatrix0to1[18][11] = -0.50480021768681;
   fWeightMatrix0to1[0][12] = -1.58992358224964;
   fWeightMatrix0to1[1][12] = -0.338780796172222;
   fWeightMatrix0to1[2][12] = 0.863591618235648;
   fWeightMatrix0to1[3][12] = -0.0399866100329466;
   fWeightMatrix0to1[4][12] = 0.165236843318391;
   fWeightMatrix0to1[5][12] = -0.188834640962273;
   fWeightMatrix0to1[6][12] = 1.86806341493096;
   fWeightMatrix0to1[7][12] = -1.93034267056141;
   fWeightMatrix0to1[8][12] = 0.68439068095603;
   fWeightMatrix0to1[9][12] = -0.597392293349655;
   fWeightMatrix0to1[10][12] = -1.24564931181775;
   fWeightMatrix0to1[11][12] = -1.53507067617514;
   fWeightMatrix0to1[12][12] = -2.0223532568776;
   fWeightMatrix0to1[13][12] = -0.788050862335928;
   fWeightMatrix0to1[14][12] = -1.76080584009938;
   fWeightMatrix0to1[15][12] = -1.14726400701727;
   fWeightMatrix0to1[16][12] = -1.45375478336049;
   fWeightMatrix0to1[17][12] = -0.512911959296067;
   fWeightMatrix0to1[18][12] = -1.02615796941807;
   fWeightMatrix0to1[0][13] = -2.19407607715257;
   fWeightMatrix0to1[1][13] = 1.11998221006144;
   fWeightMatrix0to1[2][13] = -0.264767626542807;
   fWeightMatrix0to1[3][13] = -0.131024074727257;
   fWeightMatrix0to1[4][13] = -1.49079394361468;
   fWeightMatrix0to1[5][13] = 0.289856134286125;
   fWeightMatrix0to1[6][13] = 1.97633755866063;
   fWeightMatrix0to1[7][13] = 0.50679517322102;
   fWeightMatrix0to1[8][13] = -0.161507550030494;
   fWeightMatrix0to1[9][13] = 0.274858577462384;
   fWeightMatrix0to1[10][13] = -1.60647661779968;
   fWeightMatrix0to1[11][13] = -0.998987776661819;
   fWeightMatrix0to1[12][13] = -1.68587795772627;
   fWeightMatrix0to1[13][13] = -0.231715961754065;
   fWeightMatrix0to1[14][13] = -0.0253989472474749;
   fWeightMatrix0to1[15][13] = 1.90862317024016;
   fWeightMatrix0to1[16][13] = 0.0803853569142868;
   fWeightMatrix0to1[17][13] = -0.281049055779092;
   fWeightMatrix0to1[18][13] = -0.658435925992068;
   fWeightMatrix0to1[0][14] = -1.36536423534826;
   fWeightMatrix0to1[1][14] = 1.46879794837344;
   fWeightMatrix0to1[2][14] = 0.528749259801738;
   fWeightMatrix0to1[3][14] = -0.737772319408971;
   fWeightMatrix0to1[4][14] = -0.198170082856661;
   fWeightMatrix0to1[5][14] = 0.287161365431434;
   fWeightMatrix0to1[6][14] = 0.663123821889955;
   fWeightMatrix0to1[7][14] = 0.672122882261907;
   fWeightMatrix0to1[8][14] = -0.24233378808505;
   fWeightMatrix0to1[9][14] = -0.165878934338537;
   fWeightMatrix0to1[10][14] = 2.08951405625909;
   fWeightMatrix0to1[11][14] = 0.641045034299051;
   fWeightMatrix0to1[12][14] = 1.18437283702813;
   fWeightMatrix0to1[13][14] = 0.372822578134231;
   fWeightMatrix0to1[14][14] = 0.555444564680578;
   fWeightMatrix0to1[15][14] = -0.649268421608276;
   fWeightMatrix0to1[16][14] = -1.92745069831623;
   fWeightMatrix0to1[17][14] = 0.114105390027862;
   fWeightMatrix0to1[18][14] = -1.27306302327615;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -0.203514862319659;
   fWeightMatrix1to2[0][1] = -0.213958794383565;
   fWeightMatrix1to2[0][2] = 0.435290079326767;
   fWeightMatrix1to2[0][3] = 0.00551608302348862;
   fWeightMatrix1to2[0][4] = 0.606370796503834;
   fWeightMatrix1to2[0][5] = -0.437753024650311;
   fWeightMatrix1to2[0][6] = 0.472032906295282;
   fWeightMatrix1to2[0][7] = -0.0941994191054162;
   fWeightMatrix1to2[0][8] = -0.351792742312216;
   fWeightMatrix1to2[0][9] = 0.354108378318338;
   fWeightMatrix1to2[0][10] = -0.972863582257997;
   fWeightMatrix1to2[0][11] = 0.315695676114438;
   fWeightMatrix1to2[0][12] = 0.46612692320057;
   fWeightMatrix1to2[0][13] = -1.39349404312935;
   fWeightMatrix1to2[0][14] = -1.14861970921651;
   fWeightMatrix1to2[0][15] = -1.65528971497023;
   fWeightMatrix1to2[0][16] = -0.317642284942869;
   fWeightMatrix1to2[0][17] = 1.44014603249194;
   fWeightMatrix1to2[0][18] = -0.0647412799038704;
   fWeightMatrix1to2[0][19] = 0.311830047414509;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLP::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // nothing to clear
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 1.93987222119e-11;
   fMax_1[0][0] = 0.731256723404;
   fMin_1[1][0] = 2.11151655094e-05;
   fMax_1[1][0] = 0.729348361492;
   fMin_1[2][0] = 1.93987222119e-11;
   fMax_1[2][0] = 0.731256723404;
   fMin_1[0][1] = 0.0111495917663;
   fMax_1[0][1] = 21.9877300262;
   fMin_1[1][1] = 0.134300857782;
   fMax_1[1][1] = 24.9779434204;
   fMin_1[2][1] = 0.0111495917663;
   fMax_1[2][1] = 24.9779434204;
   fMin_1[0][2] = 0.00189490010962;
   fMax_1[0][2] = 14.9983968735;
   fMin_1[1][2] = 0.0220367405564;
   fMax_1[1][2] = 14.9911079407;
   fMin_1[2][2] = 0.00189490010962;
   fMax_1[2][2] = 14.9983968735;
   fMin_1[0][3] = 0;
   fMax_1[0][3] = 0.134104982018;
   fMin_1[1][3] = 0;
   fMax_1[1][3] = 0.137716650963;
   fMin_1[2][3] = 0;
   fMax_1[2][3] = 0.137716650963;
   fMin_1[0][4] = 62.147693634;
   fMax_1[0][4] = 37961.9179688;
   fMin_1[1][4] = 41.2933425903;
   fMax_1[1][4] = 21269.5722656;
   fMin_1[2][4] = 41.2933425903;
   fMax_1[2][4] = 37961.9179688;
   fMin_1[0][5] = -2.57286167145;
   fMax_1[0][5] = 5;
   fMin_1[1][5] = -2.21387171745;
   fMax_1[1][5] = -0.0525252744555;
   fMin_1[2][5] = -2.57286167145;
   fMax_1[2][5] = 5;
   fMin_1[0][6] = 2.30495882034;
   fMax_1[0][6] = 102.738922119;
   fMin_1[1][6] = 2.78237915039;
   fMax_1[1][6] = 49.5175361633;
   fMin_1[2][6] = 2.30495882034;
   fMax_1[2][6] = 102.738922119;
   fMin_1[0][7] = 2.63570382231e-06;
   fMax_1[0][7] = 0.738568007946;
   fMin_1[1][7] = 3.91690700781e-05;
   fMax_1[1][7] = 0.923672735691;
   fMin_1[2][7] = 2.63570382231e-06;
   fMax_1[2][7] = 0.923672735691;
   fMin_1[0][8] = 2.4348450367e-08;
   fMax_1[0][8] = 0.699207723141;
   fMin_1[1][8] = 5.91529897065e-05;
   fMax_1[1][8] = 0.744905769825;
   fMin_1[2][8] = 2.4348450367e-08;
   fMax_1[2][8] = 0.744905769825;
   fMin_1[0][9] = 6.10736776707e-07;
   fMax_1[0][9] = 1.01704800129;
   fMin_1[1][9] = 3.12057891279e-05;
   fMax_1[1][9] = 1.05343544483;
   fMin_1[2][9] = 6.10736776707e-07;
   fMax_1[2][9] = 1.05343544483;
   fMin_1[0][10] = 0.00300450995564;
   fMax_1[0][10] = 1;
   fMin_1[1][10] = 0.0038299348671;
   fMax_1[1][10] = 1;
   fMin_1[2][10] = 0.00300450995564;
   fMax_1[2][10] = 1;
   fMin_1[0][11] = 0.0559116005898;
   fMax_1[0][11] = 72.067237854;
   fMin_1[1][11] = 0.144289746881;
   fMax_1[1][11] = 84.5542831421;
   fMin_1[2][11] = 0.0559116005898;
   fMax_1[2][11] = 84.5542831421;
   fMin_1[0][12] = 0.0131226135418;
   fMax_1[0][12] = 75.9046707153;
   fMin_1[1][12] = 0.146247655153;
   fMax_1[1][12] = 67.7235794067;
   fMin_1[2][12] = 0.0131226135418;
   fMax_1[2][12] = 75.9046707153;
   fMin_1[0][13] = 0.0151327997446;
   fMax_1[0][13] = 79.3785171509;
   fMin_1[1][13] = 0.0453270226717;
   fMax_1[1][13] = 68.506652832;
   fMin_1[2][13] = 0.0151327997446;
   fMax_1[2][13] = 79.3785171509;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 14;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   std::vector<int> indicesGet;
   std::vector<int> indicesPut;

   indicesGet.push_back( 0);
   indicesGet.push_back( 1);
   indicesGet.push_back( 2);
   indicesGet.push_back( 3);
   indicesGet.push_back( 4);
   indicesGet.push_back( 5);
   indicesGet.push_back( 6);
   indicesGet.push_back( 7);
   indicesGet.push_back( 8);
   indicesGet.push_back( 9);
   indicesGet.push_back( 10);
   indicesGet.push_back( 11);
   indicesGet.push_back( 12);
   indicesGet.push_back( 13);
   indicesPut.push_back( 0);
   indicesPut.push_back( 1);
   indicesPut.push_back( 2);
   indicesPut.push_back( 3);
   indicesPut.push_back( 4);
   indicesPut.push_back( 5);
   indicesPut.push_back( 6);
   indicesPut.push_back( 7);
   indicesPut.push_back( 8);
   indicesPut.push_back( 9);
   indicesPut.push_back( 10);
   indicesPut.push_back( 11);
   indicesPut.push_back( 12);
   indicesPut.push_back( 13);

   std::vector<double> dv(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<14;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
