// Class: ReadBDTold
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDTold
TMVA Release   : 4.1.4         [262404]
ROOT Release   : 5.34/07       [336391]
Creator        : pseyfert
Date           : Sat Dec 21 19:39:16 2013
Host           : Linux lxbuild175.cern.ch 2.6.18-308.4.1.el5 #1 SMP Wed Apr 18 16:26:27 CEST 2012 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /auto/sigma0/pseyfert/zoontuple/Bender_v22r7/Phys/Tau23Mu/scripts/TMVA_training_v3
Training events: 41107
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "50" [Number of trees in the forest]
BoostType: "AdaBoost" [Boosting type for the trees in the forest]
AdaBoostBeta: "5.000000e-01" [Parameter for AdaBoost algorithm]
SeparationType: "giniindex" [Separation criterion for node splitting]
nEventsMin: "200" [Minimum number of events required in a leaf node (default: Classification: max(40, N_train/(Nvar^2)/10), Regression: 10)]
nCuts: "20" [Number of steps during node cut optimisation]
PruneMethod: "nopruning" [Method used for pruning (removal) of statistically insignificant branches]
MaxDepth: "3" [Max depth of the decision tree allowed]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
RenormByClass: "False" [Individually re-normalize each event class to the original size after boosting]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2t (Linear,Quadratic or Exponential)]
UseBaggedGrad: "False" [Use only a random subsample of all events for growing the trees in each iteration. (Only valid for GradBoost)]
GradBaggingFraction: "6.000000e-01" [Defines the fraction of events to be used in each iteration when UseBaggedGrad=kTRUE. (Only valid for GradBoost)]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
UseRandomisedTrees: "False" [Choose at each node splitting a random set of variables]
UseNvars: "4" [Number of variables used if randomised tree option is chosen]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split]
UseNTrainEvents: "41107" [Number of randomly picked training events used in randomised (and bagged) trees]
UseWeightedTrees: "True" [Use weighted trees or simple average in classification from the forest]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
PruneStrength: "0.000000e+00" [Pruning strength]
PruneBeforeBoost: "False" [Flag to prune the tree before applying boosting algorithm]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
NNodesMax: "100000" [Max number of nodes in tree]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : Ignore;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!); Randomly pair events with negative and positive weights in leaf node and do not boost them (experimental!) ]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 14
TMath::Exp(-1000*LifeTime)    TMath_Exp__M_1000_T_LifeTime_ TMath::Exp(-1000*LifeTime)    transformed decay time        1                                 'F'    [1.93987222119e-11,0.731256723404]
IPSig                         IPSig                         IPSig                         IP significance               1                                 'F'    [0.0111495917663,24.9779434204]
VertexChi2                    VertexChi2                    VertexChi2                    vertex #chi^{2}               1                                 'F'    [0.00189490010962,14.9983968735]
acos(dira)                    acos_dira_                    acos(dira)                    pointing angle                1                                 'F'    [0,0.137716650963]
pt                            pt                            pt                            p_{T}                         [MeV/c]                           'F'    [41.2933425903,37961.9179688]
Laura_SumBDT                  Laura_SumBDT                  Laura_SumBDT                  Laura_SumBDT                                                    'F'    [-2.57286167145,5]
min(p0_IPSig,min(p1_IPSig,p2_IPSig)) min_p0_IPSig,min_p1_IPSig,p2_IPSig__ min(p0_IPSig,min(p1_IPSig,p2_IPSig)) min. #mu IP significance             1                                        'F'    [2.30495882034,102.738922119]
DOCAone                       DOCAone                       DOCAone                       DOCA (#mu 1 and 2)            mm                                'F'    [2.63570382231e-06,0.923672735691]
DOCAtwo                       DOCAtwo                       DOCAtwo                       DOCA (#mu 2 and 3)            mm                                'F'    [2.4348450367e-08,0.744905769825]
DOCAthree                     DOCAthree                     DOCAthree                     DOCA (#mu 1 and 3)            mm                                'F'    [6.10736776707e-07,1.05343544483]
CDF3                          CDF3                          CDF3                          cone isolation                1                                 'F'    [0.00300450995564,1]
p0_track_MatchChi2            p0_track_MatchChi2            p0_track_MatchChi2            track match #chi^{2} (#mu 1)  1                                 'F'    [0.0559116005898,84.5542831421]
p1_track_MatchChi2            p1_track_MatchChi2            p1_track_MatchChi2            track match #chi^{2} (#mu 2)  1                                 'F'    [0.0131226135418,75.9046707153]
p2_track_MatchChi2            p2_track_MatchChi2            p2_track_MatchChi2            track match #chi^{2} (#mu 3)  1                                 'F'    [0.0151327997446,79.3785171509]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDToldNode
   
#ifndef BDToldNode__def
#define BDToldNode__def
   
class BDToldNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDToldNode ( BDToldNode* left,BDToldNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDToldNode();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDToldNode* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDToldNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDToldNode*   fLeft;     // pointer to the left daughter node
   BDToldNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDToldNode::~BDToldNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDToldNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDToldNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDTold : public IClassifierReader {

 public:

   // constructor
   ReadBDTold( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDTold" ),
        fNvars( 14 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "TMath::Exp(-1000*LifeTime)", "IPSig", "VertexChi2", "acos(dira)", "pt", "Laura_SumBDT", "min(p0_IPSig,min(p1_IPSig,p2_IPSig))", "DOCAone", "DOCAtwo", "DOCAthree", "CDF3", "p0_track_MatchChi2", "p1_track_MatchChi2", "p2_track_MatchChi2" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 1.93987222119052e-11;
      fVmax[0] = 0.731256723403931;
      fVmin[1] = 0.0111495917662978;
      fVmax[1] = 24.9779434204102;
      fVmin[2] = 0.0018949001096189;
      fVmax[2] = 14.9983968734741;
      fVmin[3] = 0;
      fVmax[3] = 0.13771665096283;
      fVmin[4] = 41.293342590332;
      fVmax[4] = 37961.91796875;
      fVmin[5] = -2.57286167144775;
      fVmax[5] = 5;
      fVmin[6] = 2.30495882034302;
      fVmax[6] = 102.738922119141;
      fVmin[7] = 2.63570382230682e-06;
      fVmax[7] = 0.923672735691071;
      fVmin[8] = 2.43484503670288e-08;
      fVmax[8] = 0.744905769824982;
      fVmin[9] = 6.10736776707199e-07;
      fVmax[9] = 1.05343544483185;
      fVmin[10] = 0.00300450995564461;
      fVmax[10] = 1;
      fVmin[11] = 0.0559116005897522;
      fVmax[11] = 84.5542831420898;
      fVmin[12] = 0.0131226135417819;
      fVmax[12] = 75.904670715332;
      fVmin[13] = 0.015132799744606;
      fVmax[13] = 79.3785171508789;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDTold() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[14];
   double fVmax[14];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[14];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDToldNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDTold::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDToldNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDToldNode*)current->GetRight();
         else current=(BDToldNode*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void ReadBDTold::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(1.2764947889322);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 4.00879, 1, 1, 0.949153,-99) , 
NN(
NN(
0, 
0, 
-1, 0.481959, 1, 1, 0.788873,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538377,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.184887,-99) , 
3, 0.0421612, 1, 0, 0.460117,-99) , 
2, 6.43404, 1, 0, 0.678388,-99) , 
3, 0.0196738, 1, 0, 0.923296,-99)    );
  // itree = 1
  fBoostWeights.push_back(0.733515);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -0.769799, 1, 1, 0.939129,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.792398,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498173,-99) , 
5, -0.641336, 1, 0, 0.6598,-99) , 
3, 0.0110478, 1, 0, 0.915563,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.728094,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475441,-99) , 
2, 7.14107, 1, 0, 0.664245,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50846,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.284419,-99) , 
2, 5.00316, 1, 0, 0.396868,-99) , 
0, 0.347309, 1, 0, 0.575109,-99) , 
1, 4.76673, 1, 0, 0.78094,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.557881);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.769799, 1, 1, 0.895023,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.632897,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.286994,-99) , 
11, 18.2597, 1, 0, 0.610658,-99) , 
NN(
0, 
0, 
-1, 0.487369, 1, -1, 0.376248,-99) , 
3, 0.0199698, 1, 0, 0.545091,-99) , 
1, 3.57783, 1, 0, 0.70486,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.415483);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.0106837, 1, 1, 0.932322,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.770396,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455105,-99) , 
2, 6.42352, 1, 0, 0.670229,-99) , 
5, -0.769799, 1, 0, 0.829944,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.656712,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457187,-99) , 
5, -0.5098, 1, 0, 0.573638,-99) , 
NN(
0, 
0, 
-1, 0.522326, 1, -1, 0.4218,-99) , 
6, 7.26868, 0, 0, 0.497607,-99) , 
1, 3.57783, 1, 0, 0.63577,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.321248);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.637171, 1, 1, 0.781301,-99) , 
NN(
NN(
0, 
0, 
-1, 2.53361, 1, 1, 0.546446,-99) , 
NN(
0, 
0, 
-1, 29.4034, 1, -1, 0.395587,-99) , 
11, 12.1586, 1, 0, 0.526489,-99) , 
3, 0.00655794, 1, 0, 0.639998,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.261816);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.00496557, 1, 1, 0.908009,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.679746,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47685,-99) , 
2, 4.28455, 1, 0, 0.570753,-99) , 
5, -0.677119, 1, 0, 0.80757,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.726335,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476269,-99) , 
5, -0.637171, 1, 0, 0.609978,-99) , 
NN(
0, 
0, 
-1, 0.591972, 1, -1, 0.457866,-99) , 
3, 0.00655794, 1, 0, 0.500936,-99) , 
1, 2.38894, 1, 0, 0.575803,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.25188);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.00496557, 1, 1, 0.88368,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.640978,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.422403,-99) , 
5, -0.40671, 1, 0, 0.577523,-99) , 
5, -0.677119, 1, 0, 0.786831,-99) , 
NN(
NN(
0, 
0, 
-1, -0.776474, 1, 1, 0.600749,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525683,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.364315,-99) , 
0, 0.451501, 1, 0, 0.500644,-99) , 
1, 6.69162, 1, 0, 0.547142,-99) , 
1, 2.38894, 1, 0, 0.602717,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.23277);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.00496557, 1, 1, 0.855186,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.626122,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.448916,-99) , 
6, 4.67478, 0, 0, 0.552878,-99) , 
5, -0.677119, 1, 0, 0.754929,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.67788,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463492,-99) , 
2, 4.28268, 1, 0, 0.567856,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542301,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.435498,-99) , 
3, 0.0199698, 0, 0, 0.468225,-99) , 
1, 4.54029, 1, 0, 0.494822,-99) , 
1, 2.38894, 1, 0, 0.55236,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.19559);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.00496557, 1, 1, 0.823915,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.576412,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.318386,-99) , 
11, 12.8403, 1, 0, 0.543801,-99) , 
5, -0.677119, 1, 0, 0.727028,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.561041,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465487,-99) , 
1, 8.84295, 1, 0, 0.523141,-99) , 
NN(
0, 
0, 
-1, 0.0642478, 1, -1, 0.351916,-99) , 
0, 0.59197, 1, 0, 0.511864,-99) , 
1, 2.38894, 1, 0, 0.557709,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.16118);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.00496557, 1, 1, 0.793722,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.599282,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464273,-99) , 
1, 1.70954, 0, 0, 0.507511,-99) , 
5, -0.677119, 1, 0, 0.691622,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.601532,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.31078,-99) , 
12, 16.5266, 1, 0, 0.586476,-99) , 
NN(
0, 
0, 
-1, 0.0879717, 1, -1, 0.475877,-99) , 
0, 0.174109, 1, 0, 0.505725,-99) , 
1, 2.38894, 1, 0, 0.544182,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.175102);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.00496557, 1, 1, 0.766084,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.550236,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.412004,-99) , 
3, 0.00618429, 1, 0, 0.522165,-99) , 
5, -0.677119, 1, 0, 0.676857,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.562155,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47102,-99) , 
5, -0.391159, 1, 0, 0.543478,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516056,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.328373,-99) , 
6, 5.1903, 0, 0, 0.429718,-99) , 
7, 0.0879717, 1, 0, 0.525544,-99) , 
1, 2.38894, 1, 0, 0.556188,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.13218);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.82265,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4686,-99) , 
3, 0.00496557, 1, 0, 0.73326,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523473,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.375304,-99) , 
0, 0.239892, 0, 0, 0.496196,-99) , 
5, -0.677119, 1, 0, 0.644473,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536152,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465507,-99) , 
7, 0.0439875, 1, 0, 0.508035,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.240996,-99) , 
11, 36.2905, 1, 0, 0.503324,-99) , 
1, 2.38894, 1, 0, 0.531386,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.0860542);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.00496557, 1, 1, 0.7243,-99) , 
NN(
0, 
0, 
-1, 12.8403, 1, -1, 0.47521,-99) , 
5, -0.677119, 1, 0, 0.629377,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507666,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.261214,-99) , 
11, 36.2905, 1, 0, 0.503386,-99) , 
NN(
0, 
0, 
-1, 5.4853, 0, -1, 0.335698,-99) , 
12, 18.0825, 1, 0, 0.49728,-99) , 
1, 2.38894, 1, 0, 0.523172,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.0994029);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 5.70488, 1, 1, 0.820629,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.613662,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.383609,-99) , 
5, -0.457433, 1, 0, 0.564141,-99) , 
5, -1.03194, 1, 0, 0.625869,-99) , 
NN(
0, 
0, 
-1, 0.200655, 1, -1, 0.478032,-99) , 
1, 2.38894, 1, 0, 0.506746,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.116662);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.00374342, 1, 1, 0.660356,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55075,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.423686,-99) , 
4, 4953.07, 0, 0, 0.479711,-99) , 
5, -0.637171, 1, 0, 0.581357,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505595,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.433775,-99) , 
0, 0.522329, 1, 0, 0.493174,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.252715,-99) , 
12, 25.3381, 1, 0, 0.488191,-99) , 
3, 0.00655794, 1, 0, 0.523624,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.121267);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.745156,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473158,-99) , 
3, 0.00374342, 1, 0, 0.633722,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535875,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.430199,-99) , 
1, 3.54965, 0, 0, 0.483025,-99) , 
5, -0.637171, 1, 0, 0.567402,-99) , 
NN(
0, 
0, 
-1, 25.3381, 1, -1, 0.470062,-99) , 
3, 0.00655794, 1, 0, 0.506819,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.0870733);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 5.70488, 1, 1, 0.790558,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.581273,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.2561,-99) , 
2, 12.1419, 1, 0, 0.55285,-99) , 
5, -1.03194, 1, 0, 0.607399,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513915,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.303889,-99) , 
11, 36.2905, 1, 0, 0.510388,-99) , 
NN(
0, 
0, 
-1, 0.243116, 1, -1, 0.357385,-99) , 
9, 0.200655, 1, 0, 0.505513,-99) , 
1, 2.38894, 1, 0, 0.52469,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.0679358);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 5.70488, 1, 1, 0.775776,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.559942,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.273038,-99) , 
2, 12.1419, 1, 0, 0.535191,-99) , 
5, -1.03194, 1, 0, 0.589669,-99) , 
NN(
0, 
0, 
-1, 22.6904, 1, -1, 0.485827,-99) , 
1, 2.38894, 1, 0, 0.505206,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.119068);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.639902,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494205,-99) , 
5, -0.769799, 1, 0, 0.554955,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.563071,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454374,-99) , 
2, 7.13705, 0, 0, 0.485759,-99) , 
1, 5.95562, 1, 0, 0.520463,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.232397,-99) , 
12, 28.9242, 1, 0, 0.516307,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.092646);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -1.03194, 1, 1, 0.601083,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.584594,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499368,-99) , 
2, 7.14361, 0, 0, 0.51596,-99) , 
1, 3.15066, 1, 0, 0.538872,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.615526,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.440388,-99) , 
11, 10.2988, 0, 0, 0.465933,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520731,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.353433,-99) , 
4, 5739.05, 0, 0, 0.378629,-99) , 
2, 12.7544, 1, 0, 0.425501,-99) , 
2, 10.7137, 1, 0, 0.525528,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.116686);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 8.10338, 1, 1, 0.553611,-99) , 
NN(
0, 
0, 
-1, 5.84221, 0, -1, 0.453399,-99) , 
2, 9.99956, 1, 0, 0.539524,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.559419,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.363422,-99) , 
12, 23.2501, 1, 0, 0.478838,-99) , 
NN(
0, 
0, 
-1, 2.69661, 0, -1, 0.266754,-99) , 
10, 0.57577, 1, 0, 0.397361,-99) , 
12, 14.4687, 1, 0, 0.531196,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.0875565);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532319,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.401205,-99) , 
12, 14.4687, 1, 0, 0.524674,-99) , 
NN(
0, 
0, 
-1, 3.70645, 0, -1, 0.345733,-99) , 
11, 28.222, 1, 0, 0.519738,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511386,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.316181,-99) , 
1, 2.47373, 0, 0, 0.475369,-99) , 
NN(
0, 
0, 
-1, 0.450634, 0, -1, 0.341185,-99) , 
6, 4.9715, 0, 0, 0.410266,-99) , 
7, 0.131956, 1, 0, 0.512027,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.0598122);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526228,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478065,-99) , 
1, 5.95562, 1, 0, 0.502055,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.294259,-99) , 
12, 28.9242, 1, 0, 0.499195,-99) , 
NN(
0, 
0, 
-1, 30.7887, 1, -1, 0.318431,-99) , 
13, 22.6904, 1, 0, 0.49535,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.0443284);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510303,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.418934,-99) , 
7, 0.131956, 1, 0, 0.503944,-99) , 
NN(
0, 
0, 
-1, 3.31376, 0, -1, 0.383975,-99) , 
11, 24.1983, 1, 0, 0.499456,-99) , 
NN(
0, 
0, 
-1, 30.7887, 1, -1, 0.331551,-99) , 
13, 22.6904, 1, 0, 0.495917,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.0538848);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521927,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477574,-99) , 
2, 2.85837, 1, 0, 0.492586,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.29832,-99) , 
12, 28.9242, 1, 0, 0.489937,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.282334,-99) , 
13, 30.2488, 1, 0, 0.487556,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.0336568);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.578359,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491872,-99) , 
1, 1.20004, 1, 0, 0.496933,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.309721,-99) , 
12, 28.9242, 1, 0, 0.494405,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.293379,-99) , 
13, 30.2488, 1, 0, 0.492123,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.0247552);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.562751,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498047,-99) , 
5, -1.13041, 1, 0, 0.504364,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.316962,-99) , 
12, 28.9242, 1, 0, 0.501848,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.300404,-99) , 
13, 30.2488, 1, 0, 0.499576,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.0393499);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512915,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.417951,-99) , 
11, 24.1983, 1, 0, 0.509346,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.322346,-99) , 
12, 28.9242, 1, 0, 0.506846,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.305632,-99) , 
13, 30.2488, 1, 0, 0.504587,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.0169571);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.619224,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497941,-99) , 
4, 10875.8, 0, 0, 0.500249,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.331001,-99) , 
12, 28.9242, 1, 0, 0.498001,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.314046,-99) , 
13, 30.2488, 1, 0, 0.49595,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.0374892);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52505,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491414,-99) , 
11, 4.07964, 1, 0, 0.504327,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.334766,-99) , 
12, 28.9242, 1, 0, 0.502081,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.317711,-99) , 
13, 30.2488, 1, 0, 0.500032,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.0206358);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.20004, 1, 1, 0.506507,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.343166,-99) , 
12, 28.9242, 1, 0, 0.504355,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.325892,-99) , 
13, 30.2488, 1, 0, 0.502384,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.0781007);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 4787.75, 0, 1, 0.580043,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.556382,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.403769,-99) , 
10, 0.393104, 1, 0, 0.456924,-99) , 
0, 0.0881611, 0, 0, 0.535753,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.560348,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496156,-99) , 
3, 0.0191579, 0, 0, 0.510469,-99) , 
NN(
0, 
0, 
-1, 0.478197, 0, -1, 0.437754,-99) , 
6, 4.58219, 0, 0, 0.489156,-99) , 
6, 11.8701, 0, 0, 0.497473,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.0301553);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.20004, 1, 1, 0.511218,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.359164,-99) , 
12, 28.9242, 1, 0, 0.50924,-99) , 
NN(
0, 
0, 
-1, 0.398588, 0, -1, 0.380447,-99) , 
13, 22.6904, 1, 0, 0.506621,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.0253755);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.559986,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498147,-99) , 
5, -1.13041, 1, 0, 0.50411,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.549188,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.315326,-99) , 
0, 0.243116, 1, 0, 0.409383,-99) , 
9, 0.200655, 1, 0, 0.501292,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.343395,-99) , 
13, 30.2488, 1, 0, 0.499581,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.0514641);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.720255,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451099,-99) , 
3, 0.00511969, 1, 0, 0.556885,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.641489,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496436,-99) , 
4, 10912.4, 0, 0, 0.498993,-99) , 
5, -0.992059, 1, 0, 0.507461,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.619854,-99) , 
NN(
0, 
0, 
-1, 8.34364, 1, -1, 0.346014,-99) , 
0, 0.206067, 1, 0, 0.408615,-99) , 
10, 0.952524, 1, 0, 0.504602,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.0499069);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.644369,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.36857,-99) , 
1, 9.12748, 1, 0, 0.589545,-99) , 
NN(
0, 
0, 
-1, 10912.4, 0, 1, 0.513816,-99) , 
5, -1.23319, 1, 0, 0.518479,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.607654,-99) , 
NN(
0, 
0, 
-1, 8.34364, 1, -1, 0.35775,-99) , 
0, 0.206067, 1, 0, 0.414957,-99) , 
10, 0.952524, 1, 0, 0.515504,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.0394763);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512303,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.338596,-99) , 
13, 30.2488, 1, 0, 0.510449,-99) , 
NN(
0, 
0, 
-1, 2.90655, 0, -1, 0.429446,-99) , 
2, 12.856, 1, 0, 0.506734,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54481,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.320563,-99) , 
0, 0.243116, 1, 0, 0.410959,-99) , 
9, 0.200655, 1, 0, 0.503884,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.0428013);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.04627, 1, 1, 0.510147,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520211,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461076,-99) , 
2, 6.42821, 0, 0, 0.479482,-99) , 
11, 5.80327, 1, 0, 0.497088,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.345703,-99) , 
11, 40.2932, 1, 0, 0.495436,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.0408527);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.587617,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49086,-99) , 
5, -1.23319, 1, 0, 0.496591,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.63998,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.361603,-99) , 
9, 0.066186, 0, 0, 0.4023,-99) , 
10, 0.952524, 1, 0, 0.493852,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527286,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.320628,-99) , 
0, 0.243116, 1, 0, 0.403699,-99) , 
9, 0.200655, 1, 0, 0.49117,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.0242294);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -1.23319, 1, 1, 0.505596,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.630514,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.371086,-99) , 
9, 0.066186, 0, 0, 0.409011,-99) , 
10, 0.952524, 1, 0, 0.502804,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517093,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.329591,-99) , 
0, 0.243116, 1, 0, 0.405244,-99) , 
9, 0.200655, 1, 0, 0.499914,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.0300149);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.555277,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493842,-99) , 
4, 1847.04, 1, 0, 0.499158,-99) , 
NN(
0, 
0, 
-1, 0.44485, 0, -1, 0.393371,-99) , 
13, 22.6904, 1, 0, 0.497046,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511041,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.334967,-99) , 
0, 0.243116, 1, 0, 0.406166,-99) , 
9, 0.200655, 1, 0, 0.494359,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.0322381);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509267,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449519,-99) , 
2, 12.1419, 1, 0, 0.505364,-99) , 
NN(
0, 
0, 
-1, 0.44485, 0, -1, 0.400556,-99) , 
13, 22.6904, 1, 0, 0.503277,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503539,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.341686,-99) , 
0, 0.243116, 1, 0, 0.407315,-99) , 
9, 0.200655, 1, 0, 0.500448,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.0246452);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -1.19759, 1, 1, 0.553846,-99) , 
NN(
0, 
0, 
-1, 0.17594, 1, -1, 0.492028,-99) , 
1, 1.20004, 1, 0, 0.495692,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.362119,-99) , 
12, 28.9242, 1, 0, 0.493982,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.0233496);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.555244,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498983,-99) , 
4, 1847.04, 1, 0, 0.503762,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.582383,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.309592,-99) , 
10, 0.404854, 0, 0, 0.421123,-99) , 
7, 0.17594, 1, 0, 0.501123,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.367831,-99) , 
12, 28.9242, 1, 0, 0.499422,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.0307955);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -1.23319, 1, 1, 0.509341,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.546277,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.35819,-99) , 
0, 0.274756, 1, 0, 0.421211,-99) , 
10, 0.952524, 1, 0, 0.50682,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.559342,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.385885,-99) , 
2, 9.95853, 0, 0, 0.474357,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.325274,-99) , 
8, 0.029659, 0, 0, 0.415962,-99) , 
9, 0.200655, 1, 0, 0.504162,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.0401787);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516178,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486955,-99) , 
1, 5.95562, 1, 0, 0.501359,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.573499,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.311334,-99) , 
10, 0.404854, 0, 0, 0.4186,-99) , 
7, 0.17594, 1, 0, 0.498723,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.367923,-99) , 
12, 28.9242, 1, 0, 0.497057,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.0259272);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -0.953773, 1, 1, 0.534071,-99) , 
NN(
0, 
0, 
-1, 29.0319, 1, -1, 0.492513,-99) , 
2, 1.43013, 1, 0, 0.498886,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.359234,-99) , 
11, 40.2932, 1, 0, 0.497376,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.0250524);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 12681.5, 0, 1, 0.506775,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525189,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.320462,-99) , 
10, 0.57577, 1, 0, 0.44775,-99) , 
12, 14.4687, 1, 0, 0.503381,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.365224,-99) , 
11, 40.2932, 1, 0, 0.501892,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.0200426);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50243,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.419246,-99) , 
10, 0.952524, 1, 0, 0.500043,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.373658,-99) , 
12, 28.9242, 1, 0, 0.498492,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.662232,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494039,-99) , 
2, 9.09364, 1, 0, 0.554446,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.328645,-99) , 
10, 0.404854, 0, 0, 0.421749,-99) , 
7, 0.17594, 1, 0, 0.496032,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.0259192);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.742504,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.414565,-99) , 
9, 0.0269114, 1, 0, 0.58549,-99) , 
NN(
0, 
0, 
-1, 556.517, 0, -1, 0.491299,-99) , 
4, 10875.8, 0, 0, 0.493048,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.36671,-99) , 
11, 40.2932, 1, 0, 0.491688,-99)    );
   return;
};
 
// Clean up
inline void ReadBDTold::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDTold::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
