// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.1.4         [262404]
ROOT Release   : 5.34/07       [336391]
Creator        : pseyfert
Date           : Wed Jan  1 12:54:52 2014
Host           : Linux lxbuild175.cern.ch 2.6.18-308.4.1.el5 #1 SMP Wed Apr 18 16:26:27 CEST 2012 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /auto/sigma0/pseyfert/zoontuple/Bender_v22r7/Phys/Tau23Mu/scripts/TMVA_training_v3
Training events: 38856
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 13
TMath::Exp(-1000*LifeTime)    TMath_Exp__M_1000_T_LifeTime_ TMath::Exp(-1000*LifeTime)    transformed decay time        1                                 'F'    [1.93987222119e-11,0.731256723404]
IPSig                         IPSig                         IPSig                         IP significance               1                                 'F'    [0.0111495917663,21.7485733032]
VertexChi2                    VertexChi2                    VertexChi2                    vertex #chi^{2}               1                                 'F'    [0.00189490010962,14.9983968735]
acos(dira)                    acos_dira_                    acos(dira)                    pointing angle                1                                 'F'    [0,0.137716650963]
pt                            pt                            pt                            p_{T}                         [MeV/c]                           'F'    [41.2933425903,37961.9179688]
min(p0_IPSig,min(p1_IPSig,p2_IPSig)) min_p0_IPSig,min_p1_IPSig,p2_IPSig__ min(p0_IPSig,min(p1_IPSig,p2_IPSig)) min. #mu IP significance             1                                        'F'    [2.30495882034,102.738922119]
DOCAone                       DOCAone                       DOCAone                       DOCA (#mu 1 and 2)            mm                                'F'    [2.63570382231e-06,0.738568007946]
DOCAtwo                       DOCAtwo                       DOCAtwo                       DOCA (#mu 2 and 3)            mm                                'F'    [2.4348450367e-08,0.622791826725]
DOCAthree                     DOCAthree                     DOCAthree                     DOCA (#mu 1 and 3)            mm                                'F'    [6.10736776707e-07,1.01704800129]
CDF3                          CDF3                          CDF3                          cone isolation                1                                 'F'    [0.00300450995564,1]
p0_track_MatchChi2            p0_track_MatchChi2            p0_track_MatchChi2            track match #chi^{2} (#mu 1)  1                                 'F'    [0.0559116005898,76.3943099976]
p1_track_MatchChi2            p1_track_MatchChi2            p1_track_MatchChi2            track match #chi^{2} (#mu 2)  1                                 'F'    [0.0131226135418,75.9046707153]
p2_track_MatchChi2            p2_track_MatchChi2            p2_track_MatchChi2            track match #chi^{2} (#mu 3)  1                                 'F'    [0.0151327997446,79.3785171509]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 13 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "TMath::Exp(-1000*LifeTime)", "IPSig", "VertexChi2", "acos(dira)", "pt", "min(p0_IPSig,min(p1_IPSig,p2_IPSig))", "DOCAone", "DOCAtwo", "DOCAthree", "CDF3", "p0_track_MatchChi2", "p1_track_MatchChi2", "p2_track_MatchChi2" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 0.99999988079071;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 0.99999988079071;
      fVmin[10] = -1;
      fVmax[10] = 1;
      fVmin[11] = -1;
      fVmax[11] = 1;
      fVmin[12] = -1;
      fVmax[12] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][13];
   double fMax_1[3][13];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[13];
   double fVmax[13];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[13];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[19][14];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][19];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 14; fWeights[0] = new double[14]; 
   fLayerSize[1] = 19; fWeights[1] = new double[19]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.343572579778645;
   fWeightMatrix0to1[1][0] = 1.6962286351256;
   fWeightMatrix0to1[2][0] = -0.207764080109829;
   fWeightMatrix0to1[3][0] = 1.51230489874394;
   fWeightMatrix0to1[4][0] = -0.223716916468062;
   fWeightMatrix0to1[5][0] = -0.351948440478385;
   fWeightMatrix0to1[6][0] = -0.282346824500432;
   fWeightMatrix0to1[7][0] = 2.09441204089521;
   fWeightMatrix0to1[8][0] = -1.57496368662042;
   fWeightMatrix0to1[9][0] = -0.893676326000732;
   fWeightMatrix0to1[10][0] = -1.31877632480299;
   fWeightMatrix0to1[11][0] = 0.192300437320068;
   fWeightMatrix0to1[12][0] = -0.134313601134437;
   fWeightMatrix0to1[13][0] = -0.176431682459937;
   fWeightMatrix0to1[14][0] = -0.02882156708934;
   fWeightMatrix0to1[15][0] = -0.0314125149452152;
   fWeightMatrix0to1[16][0] = -0.70038434892565;
   fWeightMatrix0to1[17][0] = 0.794775451309679;
   fWeightMatrix0to1[0][1] = 0.141531801466694;
   fWeightMatrix0to1[1][1] = 1.16267772529176;
   fWeightMatrix0to1[2][1] = -0.486151979382209;
   fWeightMatrix0to1[3][1] = -0.681936962833117;
   fWeightMatrix0to1[4][1] = 1.27096469349313;
   fWeightMatrix0to1[5][1] = -0.00718626566785224;
   fWeightMatrix0to1[6][1] = -0.26823059134159;
   fWeightMatrix0to1[7][1] = 0.0509024485779239;
   fWeightMatrix0to1[8][1] = 1.06943452602489;
   fWeightMatrix0to1[9][1] = -1.01724460729127;
   fWeightMatrix0to1[10][1] = -1.5632076459852;
   fWeightMatrix0to1[11][1] = 0.443728761459166;
   fWeightMatrix0to1[12][1] = 0.987585867337497;
   fWeightMatrix0to1[13][1] = 1.63312586289952;
   fWeightMatrix0to1[14][1] = 0.133247320647966;
   fWeightMatrix0to1[15][1] = -0.21498763835429;
   fWeightMatrix0to1[16][1] = -0.135682990122528;
   fWeightMatrix0to1[17][1] = -1.25267983098589;
   fWeightMatrix0to1[0][2] = -1.34751515191903;
   fWeightMatrix0to1[1][2] = 1.78301657196931;
   fWeightMatrix0to1[2][2] = -0.642603629457425;
   fWeightMatrix0to1[3][2] = 0.96561071263295;
   fWeightMatrix0to1[4][2] = 0.12705517371944;
   fWeightMatrix0to1[5][2] = 0.398962486871004;
   fWeightMatrix0to1[6][2] = 0.730593591577988;
   fWeightMatrix0to1[7][2] = 0.896824972163572;
   fWeightMatrix0to1[8][2] = -1.02021704028841;
   fWeightMatrix0to1[9][2] = -0.393214541654049;
   fWeightMatrix0to1[10][2] = 0.736889535420309;
   fWeightMatrix0to1[11][2] = 0.595120507948613;
   fWeightMatrix0to1[12][2] = 0.932323997069348;
   fWeightMatrix0to1[13][2] = 1.21209676101939;
   fWeightMatrix0to1[14][2] = 0.915745630156091;
   fWeightMatrix0to1[15][2] = 0.515323395655386;
   fWeightMatrix0to1[16][2] = -1.0424296760564;
   fWeightMatrix0to1[17][2] = 0.75158573732259;
   fWeightMatrix0to1[0][3] = -1.8313772251846;
   fWeightMatrix0to1[1][3] = -0.876504791610897;
   fWeightMatrix0to1[2][3] = -1.62468453340461;
   fWeightMatrix0to1[3][3] = -1.98046418923872;
   fWeightMatrix0to1[4][3] = 1.70632389853884;
   fWeightMatrix0to1[5][3] = 0.80173292527986;
   fWeightMatrix0to1[6][3] = -1.07967028174951;
   fWeightMatrix0to1[7][3] = 0.200762172509919;
   fWeightMatrix0to1[8][3] = -0.831593344975494;
   fWeightMatrix0to1[9][3] = -1.14969947915141;
   fWeightMatrix0to1[10][3] = 2.15807983151393;
   fWeightMatrix0to1[11][3] = -0.107672625488511;
   fWeightMatrix0to1[12][3] = 0.216848839335962;
   fWeightMatrix0to1[13][3] = -0.904449085751321;
   fWeightMatrix0to1[14][3] = 1.50376525260726;
   fWeightMatrix0to1[15][3] = -0.193693841217644;
   fWeightMatrix0to1[16][3] = -1.34679485534718;
   fWeightMatrix0to1[17][3] = -1.4629129276866;
   fWeightMatrix0to1[0][4] = 0.639148718321186;
   fWeightMatrix0to1[1][4] = 1.34629018222197;
   fWeightMatrix0to1[2][4] = 0.283502133800707;
   fWeightMatrix0to1[3][4] = -0.522944405206691;
   fWeightMatrix0to1[4][4] = -1.68046488805969;
   fWeightMatrix0to1[5][4] = -1.67320948154225;
   fWeightMatrix0to1[6][4] = 1.02606123097956;
   fWeightMatrix0to1[7][4] = 0.79456710325757;
   fWeightMatrix0to1[8][4] = 1.43954883761251;
   fWeightMatrix0to1[9][4] = 0.261907980675144;
   fWeightMatrix0to1[10][4] = 1.39080442366194;
   fWeightMatrix0to1[11][4] = -0.601813493014486;
   fWeightMatrix0to1[12][4] = -0.995810609986366;
   fWeightMatrix0to1[13][4] = 0.13545519573388;
   fWeightMatrix0to1[14][4] = 2.11976491266965;
   fWeightMatrix0to1[15][4] = -0.849840224165605;
   fWeightMatrix0to1[16][4] = -2.02683472068447;
   fWeightMatrix0to1[17][4] = -1.22655575876181;
   fWeightMatrix0to1[0][5] = -0.322249752567301;
   fWeightMatrix0to1[1][5] = 0.095829117536852;
   fWeightMatrix0to1[2][5] = 1.60747355125685;
   fWeightMatrix0to1[3][5] = -1.60931183361151;
   fWeightMatrix0to1[4][5] = -0.903526698895802;
   fWeightMatrix0to1[5][5] = 1.57531954633691;
   fWeightMatrix0to1[6][5] = -0.790242096163539;
   fWeightMatrix0to1[7][5] = -1.12340212447759;
   fWeightMatrix0to1[8][5] = -2.02894835938718;
   fWeightMatrix0to1[9][5] = 2.03344175567473;
   fWeightMatrix0to1[10][5] = -1.55137401191221;
   fWeightMatrix0to1[11][5] = -1.3430542482499;
   fWeightMatrix0to1[12][5] = 0.225721658642754;
   fWeightMatrix0to1[13][5] = 2.0077360571971;
   fWeightMatrix0to1[14][5] = -0.215845130931618;
   fWeightMatrix0to1[15][5] = 1.39001036868767;
   fWeightMatrix0to1[16][5] = -1.53097435928591;
   fWeightMatrix0to1[17][5] = -0.301226508824961;
   fWeightMatrix0to1[0][6] = -0.0400953306450775;
   fWeightMatrix0to1[1][6] = 0.419491171510952;
   fWeightMatrix0to1[2][6] = -1.66371012438466;
   fWeightMatrix0to1[3][6] = 0.049340631451578;
   fWeightMatrix0to1[4][6] = 0.276555652919408;
   fWeightMatrix0to1[5][6] = 0.574338043389069;
   fWeightMatrix0to1[6][6] = -1.33939725696199;
   fWeightMatrix0to1[7][6] = 1.31411927110639;
   fWeightMatrix0to1[8][6] = -0.239935274180439;
   fWeightMatrix0to1[9][6] = -0.687140292806722;
   fWeightMatrix0to1[10][6] = 0.634532212185039;
   fWeightMatrix0to1[11][6] = -0.450452164269481;
   fWeightMatrix0to1[12][6] = -1.49050875348993;
   fWeightMatrix0to1[13][6] = 0.390952315717229;
   fWeightMatrix0to1[14][6] = 0.553019624083103;
   fWeightMatrix0to1[15][6] = 1.24233147562738;
   fWeightMatrix0to1[16][6] = 0.155215233548719;
   fWeightMatrix0to1[17][6] = 0.502153909948207;
   fWeightMatrix0to1[0][7] = -0.408154204699985;
   fWeightMatrix0to1[1][7] = 0.410815115654397;
   fWeightMatrix0to1[2][7] = -0.676123213091088;
   fWeightMatrix0to1[3][7] = 0.829130788364012;
   fWeightMatrix0to1[4][7] = 1.01504923049416;
   fWeightMatrix0to1[5][7] = -1.64080305925936;
   fWeightMatrix0to1[6][7] = 0.572282749464146;
   fWeightMatrix0to1[7][7] = -0.986249582663824;
   fWeightMatrix0to1[8][7] = -0.515531226495441;
   fWeightMatrix0to1[9][7] = -0.700170969618664;
   fWeightMatrix0to1[10][7] = 1.98290609933301;
   fWeightMatrix0to1[11][7] = -1.1540810024693;
   fWeightMatrix0to1[12][7] = -0.0546838402905692;
   fWeightMatrix0to1[13][7] = 1.65034127644839;
   fWeightMatrix0to1[14][7] = 1.96311417802331;
   fWeightMatrix0to1[15][7] = -0.75103419023306;
   fWeightMatrix0to1[16][7] = -1.99848699584835;
   fWeightMatrix0to1[17][7] = 0.132816160308558;
   fWeightMatrix0to1[0][8] = -1.46624444354333;
   fWeightMatrix0to1[1][8] = 1.77068443843307;
   fWeightMatrix0to1[2][8] = 1.44533809692318;
   fWeightMatrix0to1[3][8] = -0.711684274939216;
   fWeightMatrix0to1[4][8] = 0.366925960305033;
   fWeightMatrix0to1[5][8] = 0.322364727062402;
   fWeightMatrix0to1[6][8] = -1.27979941712631;
   fWeightMatrix0to1[7][8] = 0.806125386329239;
   fWeightMatrix0to1[8][8] = 1.1386533832289;
   fWeightMatrix0to1[9][8] = -0.0637032434677503;
   fWeightMatrix0to1[10][8] = -0.0383678639120902;
   fWeightMatrix0to1[11][8] = 0.719717135189889;
   fWeightMatrix0to1[12][8] = 0.895921019528285;
   fWeightMatrix0to1[13][8] = 0.7480116162122;
   fWeightMatrix0to1[14][8] = 1.32514803872514;
   fWeightMatrix0to1[15][8] = -1.84388964530976;
   fWeightMatrix0to1[16][8] = 0.929834607012371;
   fWeightMatrix0to1[17][8] = 0.416276113526594;
   fWeightMatrix0to1[0][9] = 0.432537032029681;
   fWeightMatrix0to1[1][9] = 0.362082751765217;
   fWeightMatrix0to1[2][9] = 0.247824679469082;
   fWeightMatrix0to1[3][9] = -0.657158026579268;
   fWeightMatrix0to1[4][9] = -0.0626829981928849;
   fWeightMatrix0to1[5][9] = 0.505887928133852;
   fWeightMatrix0to1[6][9] = -0.373734711298013;
   fWeightMatrix0to1[7][9] = -0.313781256401678;
   fWeightMatrix0to1[8][9] = 1.63918869275092;
   fWeightMatrix0to1[9][9] = 0.171708668869971;
   fWeightMatrix0to1[10][9] = -0.379894490315253;
   fWeightMatrix0to1[11][9] = -0.0521000602982798;
   fWeightMatrix0to1[12][9] = 0.239751794917487;
   fWeightMatrix0to1[13][9] = -1.71777934922767;
   fWeightMatrix0to1[14][9] = 0.4645690006538;
   fWeightMatrix0to1[15][9] = 1.13638678834374;
   fWeightMatrix0to1[16][9] = 0.543837805999437;
   fWeightMatrix0to1[17][9] = -0.0602422220356628;
   fWeightMatrix0to1[0][10] = -1.60306059911253;
   fWeightMatrix0to1[1][10] = 1.42290312719206;
   fWeightMatrix0to1[2][10] = 1.42725922789078;
   fWeightMatrix0to1[3][10] = -1.77993274913855;
   fWeightMatrix0to1[4][10] = 0.0366281543711838;
   fWeightMatrix0to1[5][10] = -0.375789377684542;
   fWeightMatrix0to1[6][10] = 0.340926074141611;
   fWeightMatrix0to1[7][10] = 1.85416647158465;
   fWeightMatrix0to1[8][10] = -0.902483096162079;
   fWeightMatrix0to1[9][10] = -0.987684588446898;
   fWeightMatrix0to1[10][10] = -0.786625516566638;
   fWeightMatrix0to1[11][10] = 1.28907963246571;
   fWeightMatrix0to1[12][10] = 1.48032690604045;
   fWeightMatrix0to1[13][10] = 1.36775108781616;
   fWeightMatrix0to1[14][10] = 0.960803421623612;
   fWeightMatrix0to1[15][10] = -1.07713250006372;
   fWeightMatrix0to1[16][10] = -1.87098830330086;
   fWeightMatrix0to1[17][10] = 1.2720261555392;
   fWeightMatrix0to1[0][11] = 0.362131539134799;
   fWeightMatrix0to1[1][11] = -1.14429871231453;
   fWeightMatrix0to1[2][11] = -1.13743521056995;
   fWeightMatrix0to1[3][11] = 0.109043313319614;
   fWeightMatrix0to1[4][11] = 0.173568924290921;
   fWeightMatrix0to1[5][11] = -1.59114799236179;
   fWeightMatrix0to1[6][11] = 1.49701544165785;
   fWeightMatrix0to1[7][11] = 1.48481955789476;
   fWeightMatrix0to1[8][11] = -1.1042742275824;
   fWeightMatrix0to1[9][11] = 0.216741114127718;
   fWeightMatrix0to1[10][11] = 1.64700737842344;
   fWeightMatrix0to1[11][11] = 1.01184339112456;
   fWeightMatrix0to1[12][11] = 0.32017276786928;
   fWeightMatrix0to1[13][11] = 0.20886815817056;
   fWeightMatrix0to1[14][11] = -0.942118646678267;
   fWeightMatrix0to1[15][11] = -1.64752762346225;
   fWeightMatrix0to1[16][11] = 1.049966526831;
   fWeightMatrix0to1[17][11] = 1.1586811909046;
   fWeightMatrix0to1[0][12] = 0.661664922471871;
   fWeightMatrix0to1[1][12] = 0.390795069762076;
   fWeightMatrix0to1[2][12] = 0.979249116919854;
   fWeightMatrix0to1[3][12] = -1.80913927056392;
   fWeightMatrix0to1[4][12] = -1.3839567683448;
   fWeightMatrix0to1[5][12] = 0.0973535674147477;
   fWeightMatrix0to1[6][12] = -1.14325775889753;
   fWeightMatrix0to1[7][12] = 1.09272780661566;
   fWeightMatrix0to1[8][12] = 1.21352190094822;
   fWeightMatrix0to1[9][12] = -0.556998324266819;
   fWeightMatrix0to1[10][12] = 0.983302554320571;
   fWeightMatrix0to1[11][12] = 0.0684896065446086;
   fWeightMatrix0to1[12][12] = -1.71828471528886;
   fWeightMatrix0to1[13][12] = -0.726839394885028;
   fWeightMatrix0to1[14][12] = 1.75710417348198;
   fWeightMatrix0to1[15][12] = -1.18490029348077;
   fWeightMatrix0to1[16][12] = 0.366952236133475;
   fWeightMatrix0to1[17][12] = -0.0779974324199666;
   fWeightMatrix0to1[0][13] = 1.81683024684332;
   fWeightMatrix0to1[1][13] = -2.0101349915537;
   fWeightMatrix0to1[2][13] = 1.52556954640989;
   fWeightMatrix0to1[3][13] = 0.306541092438938;
   fWeightMatrix0to1[4][13] = -1.59671595913453;
   fWeightMatrix0to1[5][13] = -1.53317276972078;
   fWeightMatrix0to1[6][13] = -2.04863543883413;
   fWeightMatrix0to1[7][13] = -0.85714955940471;
   fWeightMatrix0to1[8][13] = -1.2447607533541;
   fWeightMatrix0to1[9][13] = -0.290621513263609;
   fWeightMatrix0to1[10][13] = -2.26407379520535;
   fWeightMatrix0to1[11][13] = -0.491336885197541;
   fWeightMatrix0to1[12][13] = -1.0419151137101;
   fWeightMatrix0to1[13][13] = -1.98943229274686;
   fWeightMatrix0to1[14][13] = 0.339929971318681;
   fWeightMatrix0to1[15][13] = -0.373985919100921;
   fWeightMatrix0to1[16][13] = 0.914991678907592;
   fWeightMatrix0to1[17][13] = -1.2947722625759;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -0.0117743505872848;
   fWeightMatrix1to2[0][1] = 1.55067702671144;
   fWeightMatrix1to2[0][2] = 0.147268082219714;
   fWeightMatrix1to2[0][3] = -0.0411235310841066;
   fWeightMatrix1to2[0][4] = 0.223336009660417;
   fWeightMatrix1to2[0][5] = 0.000344257622207727;
   fWeightMatrix1to2[0][6] = 0.0145320653042804;
   fWeightMatrix1to2[0][7] = -1.45810641237114;
   fWeightMatrix1to2[0][8] = -0.00115366578941019;
   fWeightMatrix1to2[0][9] = 0.476370747726588;
   fWeightMatrix1to2[0][10] = 1.45004514702241;
   fWeightMatrix1to2[0][11] = -0.0489200247533129;
   fWeightMatrix1to2[0][12] = -0.0667665772656173;
   fWeightMatrix1to2[0][13] = -0.260529430811228;
   fWeightMatrix1to2[0][14] = -1.34494177676214;
   fWeightMatrix1to2[0][15] = 0.785128234232547;
   fWeightMatrix1to2[0][16] = 0.643943409425708;
   fWeightMatrix1to2[0][17] = 0.118523287561612;
   fWeightMatrix1to2[0][18] = -0.826301488570363;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLP::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // nothing to clear
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 1.93987222119e-11;
   fMax_1[0][0] = 0.731256723404;
   fMin_1[1][0] = 2.11151655094e-05;
   fMax_1[1][0] = 0.726359844208;
   fMin_1[2][0] = 1.93987222119e-11;
   fMax_1[2][0] = 0.731256723404;
   fMin_1[0][1] = 0.0111495917663;
   fMax_1[0][1] = 21.7485733032;
   fMin_1[1][1] = 0.134300857782;
   fMax_1[1][1] = 20.9987621307;
   fMin_1[2][1] = 0.0111495917663;
   fMax_1[2][1] = 21.7485733032;
   fMin_1[0][2] = 0.00189490010962;
   fMax_1[0][2] = 14.9983968735;
   fMin_1[1][2] = 0.0220367405564;
   fMax_1[1][2] = 14.9877176285;
   fMin_1[2][2] = 0.00189490010962;
   fMax_1[2][2] = 14.9983968735;
   fMin_1[0][3] = 0;
   fMax_1[0][3] = 0.134104982018;
   fMin_1[1][3] = 0;
   fMax_1[1][3] = 0.137716650963;
   fMin_1[2][3] = 0;
   fMax_1[2][3] = 0.137716650963;
   fMin_1[0][4] = 62.147693634;
   fMax_1[0][4] = 37961.9179688;
   fMin_1[1][4] = 41.2933425903;
   fMax_1[1][4] = 21269.5722656;
   fMin_1[2][4] = 41.2933425903;
   fMax_1[2][4] = 37961.9179688;
   fMin_1[0][5] = 2.30495882034;
   fMax_1[0][5] = 102.738922119;
   fMin_1[1][5] = 2.78237915039;
   fMax_1[1][5] = 49.5175361633;
   fMin_1[2][5] = 2.30495882034;
   fMax_1[2][5] = 102.738922119;
   fMin_1[0][6] = 2.63570382231e-06;
   fMax_1[0][6] = 0.738568007946;
   fMin_1[1][6] = 3.91690700781e-05;
   fMax_1[1][6] = 0.731490552425;
   fMin_1[2][6] = 2.63570382231e-06;
   fMax_1[2][6] = 0.738568007946;
   fMin_1[0][7] = 2.4348450367e-08;
   fMax_1[0][7] = 0.622791826725;
   fMin_1[1][7] = 7.34744171496e-05;
   fMax_1[1][7] = 0.365254282951;
   fMin_1[2][7] = 2.4348450367e-08;
   fMax_1[2][7] = 0.622791826725;
   fMin_1[0][8] = 6.10736776707e-07;
   fMax_1[0][8] = 1.01704800129;
   fMin_1[1][8] = 3.12057891279e-05;
   fMax_1[1][8] = 0.672129392624;
   fMin_1[2][8] = 6.10736776707e-07;
   fMax_1[2][8] = 1.01704800129;
   fMin_1[0][9] = 0.00300450995564;
   fMax_1[0][9] = 1;
   fMin_1[1][9] = 0.0038299348671;
   fMax_1[1][9] = 1;
   fMin_1[2][9] = 0.00300450995564;
   fMax_1[2][9] = 1;
   fMin_1[0][10] = 0.0559116005898;
   fMax_1[0][10] = 72.067237854;
   fMin_1[1][10] = 0.151803418994;
   fMax_1[1][10] = 76.3943099976;
   fMin_1[2][10] = 0.0559116005898;
   fMax_1[2][10] = 76.3943099976;
   fMin_1[0][11] = 0.0131226135418;
   fMax_1[0][11] = 75.9046707153;
   fMin_1[1][11] = 0.146247655153;
   fMax_1[1][11] = 67.7235794067;
   fMin_1[2][11] = 0.0131226135418;
   fMax_1[2][11] = 75.9046707153;
   fMin_1[0][12] = 0.0151327997446;
   fMax_1[0][12] = 79.3785171509;
   fMin_1[1][12] = 0.0453270226717;
   fMax_1[1][12] = 68.506652832;
   fMin_1[2][12] = 0.0151327997446;
   fMax_1[2][12] = 79.3785171509;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 13;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   std::vector<int> indicesGet;
   std::vector<int> indicesPut;

   indicesGet.push_back( 0);
   indicesGet.push_back( 1);
   indicesGet.push_back( 2);
   indicesGet.push_back( 3);
   indicesGet.push_back( 4);
   indicesGet.push_back( 5);
   indicesGet.push_back( 6);
   indicesGet.push_back( 7);
   indicesGet.push_back( 8);
   indicesGet.push_back( 9);
   indicesGet.push_back( 10);
   indicesGet.push_back( 11);
   indicesGet.push_back( 12);
   indicesPut.push_back( 0);
   indicesPut.push_back( 1);
   indicesPut.push_back( 2);
   indicesPut.push_back( 3);
   indicesPut.push_back( 4);
   indicesPut.push_back( 5);
   indicesPut.push_back( 6);
   indicesPut.push_back( 7);
   indicesPut.push_back( 8);
   indicesPut.push_back( 9);
   indicesPut.push_back( 10);
   indicesPut.push_back( 11);
   indicesPut.push_back( 12);

   std::vector<double> dv(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<13;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
