// Class: ReadMLPCJ
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLPCJ
TMVA Release   : 4.1.4         [262404]
ROOT Release   : 5.34/07       [336391]
Creator        : pseyfert
Date           : Fri Dec 20 21:36:58 2013
Host           : Linux lxbuild175.cern.ch 2.6.18-308.4.1.el5 #1 SMP Wed Apr 18 16:26:27 CEST 2012 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /auto/sigma0/pseyfert/zoontuple/Bender_v22r7/Phys/Tau23Mu/scripts/TMVA_training_v3
Training events: 41107
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 16
TMath::Exp(-1000*LifeTime)    TMath_Exp__M_1000_T_LifeTime_ TMath::Exp(-1000*LifeTime)    transformed decay time        1                                 'F'    [1.93987222119e-11,0.731256723404]
IPSig                         IPSig                         IPSig                         IP significance               1                                 'F'    [0.0111495917663,24.9779434204]
VertexChi2                    VertexChi2                    VertexChi2                    vertex #chi^{2}               1                                 'F'    [0.00189490010962,14.9983968735]
acos(dira)                    acos_dira_                    acos(dira)                    pointing angle                1                                 'F'    [0,0.137716650963]
pt                            pt                            pt                            p_{T}                         [MeV/c]                           'F'    [41.2933425903,37961.9179688]
min(p0_IPSig,min(p1_IPSig,p2_IPSig)) min_p0_IPSig,min_p1_IPSig,p2_IPSig__ min(p0_IPSig,min(p1_IPSig,p2_IPSig)) min. #mu IP significance             1                                        'F'    [2.30495882034,102.738922119]
DOCAone                       DOCAone                       DOCAone                       DOCA (#mu 1 and 2)            mm                                'F'    [2.63570382231e-06,0.923672735691]
DOCAtwo                       DOCAtwo                       DOCAtwo                       DOCA (#mu 2 and 3)            mm                                'F'    [2.4348450367e-08,0.744905769825]
DOCAthree                     DOCAthree                     DOCAthree                     DOCA (#mu 1 and 3)            mm                                'F'    [6.10736776707e-07,1.05343544483]
isolationd                    isolationd                    isolationd                    isolationd                                                      'F'    [0,7]
isolatione                    isolatione                    isolatione                    isolatione                                                      'F'    [0,8]
isolationf                    isolationf                    isolationf                    isolationf                                                      'F'    [0,8]
CDF3                          CDF3                          CDF3                          cone isolation                1                                 'F'    [0.00300450995564,1]
p0_track_MatchChi2            p0_track_MatchChi2            p0_track_MatchChi2            track match #chi^{2} (#mu 1)  1                                 'F'    [0.0559116005898,84.5542831421]
p1_track_MatchChi2            p1_track_MatchChi2            p1_track_MatchChi2            track match #chi^{2} (#mu 2)  1                                 'F'    [0.0131226135418,75.9046707153]
p2_track_MatchChi2            p2_track_MatchChi2            p2_track_MatchChi2            track match #chi^{2} (#mu 3)  1                                 'F'    [0.0151327997446,79.3785171509]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLPCJ : public IClassifierReader {

 public:

   // constructor
   ReadMLPCJ( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLPCJ" ),
        fNvars( 16 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "TMath::Exp(-1000*LifeTime)", "IPSig", "VertexChi2", "acos(dira)", "pt", "min(p0_IPSig,min(p1_IPSig,p2_IPSig))", "DOCAone", "DOCAtwo", "DOCAthree", "isolationd", "isolatione", "isolationf", "CDF3", "p0_track_MatchChi2", "p1_track_MatchChi2", "p2_track_MatchChi2" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 0.99999988079071;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 0.99999988079071;
      fVmin[6] = -1;
      fVmax[6] = 0.99999988079071;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;
      fVmin[11] = -1;
      fVmax[11] = 1;
      fVmin[12] = -1;
      fVmax[12] = 0.99999988079071;
      fVmin[13] = -1;
      fVmax[13] = 1;
      fVmin[14] = -1;
      fVmax[14] = 1;
      fVmin[15] = -1;
      fVmax[15] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';
      fType[14] = 'F';
      fType[15] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLPCJ() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][16];
   double fMax_1[3][16];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[16];
   double fVmax[16];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[16];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[22][17];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][22];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLPCJ::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 17; fWeights[0] = new double[17]; 
   fLayerSize[1] = 22; fWeights[1] = new double[22]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -1.52740481707542;
   fWeightMatrix0to1[1][0] = 1.78100289069334;
   fWeightMatrix0to1[2][0] = 0.834925545601704;
   fWeightMatrix0to1[3][0] = 1.82566110836598;
   fWeightMatrix0to1[4][0] = -0.690520459018248;
   fWeightMatrix0to1[5][0] = -0.411221419491019;
   fWeightMatrix0to1[6][0] = 0.249428065813246;
   fWeightMatrix0to1[7][0] = 1.83868277180022;
   fWeightMatrix0to1[8][0] = -1.1777263781695;
   fWeightMatrix0to1[9][0] = 0.0469867390368516;
   fWeightMatrix0to1[10][0] = -1.31115842519477;
   fWeightMatrix0to1[11][0] = 1.34006246576098;
   fWeightMatrix0to1[12][0] = -1.17480412243034;
   fWeightMatrix0to1[13][0] = 0.164127085559893;
   fWeightMatrix0to1[14][0] = 1.84722502082919;
   fWeightMatrix0to1[15][0] = 0.738072827006935;
   fWeightMatrix0to1[16][0] = -0.474795420169254;
   fWeightMatrix0to1[17][0] = 2.91517025627511;
   fWeightMatrix0to1[18][0] = -0.941386431278638;
   fWeightMatrix0to1[19][0] = 1.38508260218412;
   fWeightMatrix0to1[20][0] = -0.676623572716196;
   fWeightMatrix0to1[0][1] = -1.66614283658089;
   fWeightMatrix0to1[1][1] = 0.3379139358995;
   fWeightMatrix0to1[2][1] = -0.0460345105979289;
   fWeightMatrix0to1[3][1] = -4.8517550788632;
   fWeightMatrix0to1[4][1] = 0.684962885568714;
   fWeightMatrix0to1[5][1] = 6.30144442206355;
   fWeightMatrix0to1[6][1] = -0.655060403362173;
   fWeightMatrix0to1[7][1] = -1.58263936193912;
   fWeightMatrix0to1[8][1] = -2.91676270868447;
   fWeightMatrix0to1[9][1] = 0.815059028173297;
   fWeightMatrix0to1[10][1] = 1.63829862430676;
   fWeightMatrix0to1[11][1] = 0.212737464597077;
   fWeightMatrix0to1[12][1] = -0.224711345374915;
   fWeightMatrix0to1[13][1] = 0.330187553867839;
   fWeightMatrix0to1[14][1] = 1.54495065261262;
   fWeightMatrix0to1[15][1] = -1.41523310748543;
   fWeightMatrix0to1[16][1] = 1.73528971967695;
   fWeightMatrix0to1[17][1] = -1.16070327340814;
   fWeightMatrix0to1[18][1] = -2.16195709807635;
   fWeightMatrix0to1[19][1] = 1.19997605154894;
   fWeightMatrix0to1[20][1] = 2.6834558655558;
   fWeightMatrix0to1[0][2] = 0.550128731221891;
   fWeightMatrix0to1[1][2] = 2.70680805185409;
   fWeightMatrix0to1[2][2] = -0.753209942387014;
   fWeightMatrix0to1[3][2] = -1.17626122725358;
   fWeightMatrix0to1[4][2] = 1.49614894170205;
   fWeightMatrix0to1[5][2] = 0.0442255582962284;
   fWeightMatrix0to1[6][2] = 1.70600914003963;
   fWeightMatrix0to1[7][2] = 1.0733263531596;
   fWeightMatrix0to1[8][2] = 0.559929743756365;
   fWeightMatrix0to1[9][2] = 0.848104253647213;
   fWeightMatrix0to1[10][2] = -1.37709093113316;
   fWeightMatrix0to1[11][2] = 1.44217734539695;
   fWeightMatrix0to1[12][2] = -1.76478138178812;
   fWeightMatrix0to1[13][2] = 0.190147807330809;
   fWeightMatrix0to1[14][2] = -0.775994598450827;
   fWeightMatrix0to1[15][2] = -1.79550501313186;
   fWeightMatrix0to1[16][2] = 1.03206029789778;
   fWeightMatrix0to1[17][2] = 1.11368002603448;
   fWeightMatrix0to1[18][2] = -0.145967512034979;
   fWeightMatrix0to1[19][2] = 0.37831278841928;
   fWeightMatrix0to1[20][2] = -1.1344330201738;
   fWeightMatrix0to1[0][3] = 0.248731338051375;
   fWeightMatrix0to1[1][3] = 3.56044988657476;
   fWeightMatrix0to1[2][3] = -0.486550440959699;
   fWeightMatrix0to1[3][3] = -1.41616134138508;
   fWeightMatrix0to1[4][3] = 0.730106289936812;
   fWeightMatrix0to1[5][3] = 1.3638714575971;
   fWeightMatrix0to1[6][3] = -1.13216980157779;
   fWeightMatrix0to1[7][3] = -0.798811628136646;
   fWeightMatrix0to1[8][3] = 0.72582654945337;
   fWeightMatrix0to1[9][3] = 1.38062602825295;
   fWeightMatrix0to1[10][3] = 1.42363073163638;
   fWeightMatrix0to1[11][3] = 1.42285274366106;
   fWeightMatrix0to1[12][3] = -0.396746438035722;
   fWeightMatrix0to1[13][3] = -2.64586023635109;
   fWeightMatrix0to1[14][3] = -0.582966533429343;
   fWeightMatrix0to1[15][3] = 1.06248983166163;
   fWeightMatrix0to1[16][3] = 0.814174344974136;
   fWeightMatrix0to1[17][3] = 2.09453924660837;
   fWeightMatrix0to1[18][3] = 0.351466246160088;
   fWeightMatrix0to1[19][3] = 0.989397056033806;
   fWeightMatrix0to1[20][3] = 0.206947949228039;
   fWeightMatrix0to1[0][4] = -1.0062902805428;
   fWeightMatrix0to1[1][4] = 0.646302930387152;
   fWeightMatrix0to1[2][4] = 0.807265720323701;
   fWeightMatrix0to1[3][4] = -0.806124226649713;
   fWeightMatrix0to1[4][4] = -1.5782742359902;
   fWeightMatrix0to1[5][4] = -0.529278974744502;
   fWeightMatrix0to1[6][4] = -0.12051201759433;
   fWeightMatrix0to1[7][4] = -0.22199354640663;
   fWeightMatrix0to1[8][4] = 1.56231738833177;
   fWeightMatrix0to1[9][4] = -2.3109430002901;
   fWeightMatrix0to1[10][4] = -0.518084751587501;
   fWeightMatrix0to1[11][4] = 1.81728990981642;
   fWeightMatrix0to1[12][4] = -0.949308165382867;
   fWeightMatrix0to1[13][4] = -0.165677944203956;
   fWeightMatrix0to1[14][4] = -0.643076922899675;
   fWeightMatrix0to1[15][4] = 0.153348417926078;
   fWeightMatrix0to1[16][4] = -1.29480126448923;
   fWeightMatrix0to1[17][4] = -0.712700178764015;
   fWeightMatrix0to1[18][4] = 1.10303713366036;
   fWeightMatrix0to1[19][4] = 1.65830273551095;
   fWeightMatrix0to1[20][4] = -1.7128531945726;
   fWeightMatrix0to1[0][5] = 5.49453562210296;
   fWeightMatrix0to1[1][5] = -2.47848613824292;
   fWeightMatrix0to1[2][5] = -1.14991458782821;
   fWeightMatrix0to1[3][5] = 0.550435605296104;
   fWeightMatrix0to1[4][5] = 1.7511935240679;
   fWeightMatrix0to1[5][5] = -4.26640864276244;
   fWeightMatrix0to1[6][5] = -0.350251804390643;
   fWeightMatrix0to1[7][5] = 0.270236264310081;
   fWeightMatrix0to1[8][5] = 0.187635207119046;
   fWeightMatrix0to1[9][5] = -1.67443198507209;
   fWeightMatrix0to1[10][5] = 2.07242841829968;
   fWeightMatrix0to1[11][5] = 0.353295301833621;
   fWeightMatrix0to1[12][5] = -1.07047236940058;
   fWeightMatrix0to1[13][5] = 5.16331211365397;
   fWeightMatrix0to1[14][5] = -3.85905027241922;
   fWeightMatrix0to1[15][5] = -1.53622804952986;
   fWeightMatrix0to1[16][5] = 0.755320177883933;
   fWeightMatrix0to1[17][5] = -1.25887626559399;
   fWeightMatrix0to1[18][5] = 3.0426726337124;
   fWeightMatrix0to1[19][5] = 0.766853389652613;
   fWeightMatrix0to1[20][5] = -0.0261546389942064;
   fWeightMatrix0to1[0][6] = -3.10885081749365;
   fWeightMatrix0to1[1][6] = 0.55472936617363;
   fWeightMatrix0to1[2][6] = -2.11199725547978;
   fWeightMatrix0to1[3][6] = 0.510703034329116;
   fWeightMatrix0to1[4][6] = -1.02059391624235;
   fWeightMatrix0to1[5][6] = -1.99508211693673;
   fWeightMatrix0to1[6][6] = 0.295976179178821;
   fWeightMatrix0to1[7][6] = -2.05279576878086;
   fWeightMatrix0to1[8][6] = -1.57354027844431;
   fWeightMatrix0to1[9][6] = 1.33958582114239;
   fWeightMatrix0to1[10][6] = 2.19832092055612;
   fWeightMatrix0to1[11][6] = -2.18243692480226;
   fWeightMatrix0to1[12][6] = 0.248472059074352;
   fWeightMatrix0to1[13][6] = -1.47934606530905;
   fWeightMatrix0to1[14][6] = 1.51048160862864;
   fWeightMatrix0to1[15][6] = 0.190826858054245;
   fWeightMatrix0to1[16][6] = -0.784190421190341;
   fWeightMatrix0to1[17][6] = 0.201614841171538;
   fWeightMatrix0to1[18][6] = -2.28790087487806;
   fWeightMatrix0to1[19][6] = 1.57074706196747;
   fWeightMatrix0to1[20][6] = 1.8292387636503;
   fWeightMatrix0to1[0][7] = -1.55519214010997;
   fWeightMatrix0to1[1][7] = 0.785164762949655;
   fWeightMatrix0to1[2][7] = -0.0538503182179584;
   fWeightMatrix0to1[3][7] = 0.122651031044463;
   fWeightMatrix0to1[4][7] = -0.70652738457316;
   fWeightMatrix0to1[5][7] = -1.1409430046579;
   fWeightMatrix0to1[6][7] = -0.736367972411618;
   fWeightMatrix0to1[7][7] = -0.717129530406326;
   fWeightMatrix0to1[8][7] = -0.572783852986716;
   fWeightMatrix0to1[9][7] = 1.20194527415213;
   fWeightMatrix0to1[10][7] = 0.890458536406942;
   fWeightMatrix0to1[11][7] = 0.806167415074574;
   fWeightMatrix0to1[12][7] = -1.58353834087687;
   fWeightMatrix0to1[13][7] = -0.784203716711192;
   fWeightMatrix0to1[14][7] = 1.73914615170892;
   fWeightMatrix0to1[15][7] = 0.557509720082434;
   fWeightMatrix0to1[16][7] = 1.21063102204175;
   fWeightMatrix0to1[17][7] = 0.652663866572652;
   fWeightMatrix0to1[18][7] = 1.55841910154675;
   fWeightMatrix0to1[19][7] = -0.61389879318819;
   fWeightMatrix0to1[20][7] = -0.0951291871878791;
   fWeightMatrix0to1[0][8] = -3.49104079779761;
   fWeightMatrix0to1[1][8] = -0.997944978494168;
   fWeightMatrix0to1[2][8] = 1.21815640109023;
   fWeightMatrix0to1[3][8] = 0.457877246691029;
   fWeightMatrix0to1[4][8] = -4.29341482759598;
   fWeightMatrix0to1[5][8] = 1.39359012361819;
   fWeightMatrix0to1[6][8] = 1.77878731966676;
   fWeightMatrix0to1[7][8] = -2.57540792666832;
   fWeightMatrix0to1[8][8] = 1.79128990122087;
   fWeightMatrix0to1[9][8] = 0.410118625355397;
   fWeightMatrix0to1[10][8] = 0.885574720040839;
   fWeightMatrix0to1[11][8] = -1.9150445355917;
   fWeightMatrix0to1[12][8] = -1.62486787945699;
   fWeightMatrix0to1[13][8] = 1.14171393212473;
   fWeightMatrix0to1[14][8] = 0.473620350028828;
   fWeightMatrix0to1[15][8] = -1.7163915266475;
   fWeightMatrix0to1[16][8] = 0.521894732791892;
   fWeightMatrix0to1[17][8] = -1.21749707192913;
   fWeightMatrix0to1[18][8] = 1.49096117455047;
   fWeightMatrix0to1[19][8] = 1.76901981461817;
   fWeightMatrix0to1[20][8] = -0.768511206818789;
   fWeightMatrix0to1[0][9] = -0.397886061345239;
   fWeightMatrix0to1[1][9] = 0.365314659705293;
   fWeightMatrix0to1[2][9] = 0.758773575942756;
   fWeightMatrix0to1[3][9] = 1.2178405963185;
   fWeightMatrix0to1[4][9] = 0.994661292511394;
   fWeightMatrix0to1[5][9] = 2.05743432184959;
   fWeightMatrix0to1[6][9] = -1.03051547474369;
   fWeightMatrix0to1[7][9] = -2.05182296952277;
   fWeightMatrix0to1[8][9] = 1.7788230567567;
   fWeightMatrix0to1[9][9] = 0.336313610683382;
   fWeightMatrix0to1[10][9] = -1.0230693066227;
   fWeightMatrix0to1[11][9] = -0.348225748123391;
   fWeightMatrix0to1[12][9] = 0.238393238945183;
   fWeightMatrix0to1[13][9] = -0.606563758835689;
   fWeightMatrix0to1[14][9] = -2.48740488060671;
   fWeightMatrix0to1[15][9] = 1.61453821562509;
   fWeightMatrix0to1[16][9] = 1.43413027085947;
   fWeightMatrix0to1[17][9] = 0.186459043254697;
   fWeightMatrix0to1[18][9] = -0.80433346311223;
   fWeightMatrix0to1[19][9] = 1.62588674604639;
   fWeightMatrix0to1[20][9] = 0.998166884807136;
   fWeightMatrix0to1[0][10] = 0.614777902491684;
   fWeightMatrix0to1[1][10] = -0.253844154000691;
   fWeightMatrix0to1[2][10] = -2.08841432821028;
   fWeightMatrix0to1[3][10] = 0.771618740618993;
   fWeightMatrix0to1[4][10] = 2.35691887872057;
   fWeightMatrix0to1[5][10] = 2.80658691099066;
   fWeightMatrix0to1[6][10] = 0.995019076176601;
   fWeightMatrix0to1[7][10] = 0.150479415925461;
   fWeightMatrix0to1[8][10] = 1.44342171010598;
   fWeightMatrix0to1[9][10] = -1.28428392653289;
   fWeightMatrix0to1[10][10] = -0.95037882402548;
   fWeightMatrix0to1[11][10] = -0.0028578883528301;
   fWeightMatrix0to1[12][10] = -1.46304901177919;
   fWeightMatrix0to1[13][10] = 0.345999663656838;
   fWeightMatrix0to1[14][10] = 1.68341025943593;
   fWeightMatrix0to1[15][10] = -1.1651918321541;
   fWeightMatrix0to1[16][10] = 1.40772877930843;
   fWeightMatrix0to1[17][10] = 0.113462607812171;
   fWeightMatrix0to1[18][10] = -2.99371028435093;
   fWeightMatrix0to1[19][10] = -1.08826664333557;
   fWeightMatrix0to1[20][10] = 0.651131612498448;
   fWeightMatrix0to1[0][11] = 0.770379833647889;
   fWeightMatrix0to1[1][11] = 1.05036630502889;
   fWeightMatrix0to1[2][11] = -1.31268146312313;
   fWeightMatrix0to1[3][11] = 1.63533969529464;
   fWeightMatrix0to1[4][11] = 0.258791582943182;
   fWeightMatrix0to1[5][11] = 3.63465773778213;
   fWeightMatrix0to1[6][11] = 0.238758586254736;
   fWeightMatrix0to1[7][11] = -1.42601682273986;
   fWeightMatrix0to1[8][11] = 0.654019594642827;
   fWeightMatrix0to1[9][11] = -1.80237575378198;
   fWeightMatrix0to1[10][11] = -0.0784767075401127;
   fWeightMatrix0to1[11][11] = -1.88665540837772;
   fWeightMatrix0to1[12][11] = -1.56715156383996;
   fWeightMatrix0to1[13][11] = -0.683570997330381;
   fWeightMatrix0to1[14][11] = 0.977668493024298;
   fWeightMatrix0to1[15][11] = -0.946126720662029;
   fWeightMatrix0to1[16][11] = -0.899338638890618;
   fWeightMatrix0to1[17][11] = -0.0645419003187321;
   fWeightMatrix0to1[18][11] = -2.50701333591812;
   fWeightMatrix0to1[19][11] = 0.146583855852859;
   fWeightMatrix0to1[20][11] = -0.765168922376384;
   fWeightMatrix0to1[0][12] = -0.0092720213123194;
   fWeightMatrix0to1[1][12] = 0.476050448701092;
   fWeightMatrix0to1[2][12] = 1.12049726571053;
   fWeightMatrix0to1[3][12] = 0.848595808043165;
   fWeightMatrix0to1[4][12] = 0.260174010586468;
   fWeightMatrix0to1[5][12] = -0.342852399196809;
   fWeightMatrix0to1[6][12] = -0.307066238640046;
   fWeightMatrix0to1[7][12] = -1.44230694566768;
   fWeightMatrix0to1[8][12] = 1.21743705987503;
   fWeightMatrix0to1[9][12] = 1.24006436022989;
   fWeightMatrix0to1[10][12] = 1.5598942996584;
   fWeightMatrix0to1[11][12] = -0.552635092184696;
   fWeightMatrix0to1[12][12] = 0.182520536334976;
   fWeightMatrix0to1[13][12] = 0.67508712568949;
   fWeightMatrix0to1[14][12] = -1.17238669307868;
   fWeightMatrix0to1[15][12] = 1.28173693055828;
   fWeightMatrix0to1[16][12] = 1.04178929737017;
   fWeightMatrix0to1[17][12] = 0.185806708326517;
   fWeightMatrix0to1[18][12] = -0.778426206577745;
   fWeightMatrix0to1[19][12] = 0.875053987454528;
   fWeightMatrix0to1[20][12] = 0.639183262028226;
   fWeightMatrix0to1[0][13] = 0.322175137442646;
   fWeightMatrix0to1[1][13] = -1.05477777914633;
   fWeightMatrix0to1[2][13] = -0.615123072438023;
   fWeightMatrix0to1[3][13] = -0.510463153967821;
   fWeightMatrix0to1[4][13] = -0.0863452159446993;
   fWeightMatrix0to1[5][13] = -0.067323065738071;
   fWeightMatrix0to1[6][13] = -0.30888638381641;
   fWeightMatrix0to1[7][13] = 0.109966289105926;
   fWeightMatrix0to1[8][13] = -0.586540048957198;
   fWeightMatrix0to1[9][13] = -0.415490191888417;
   fWeightMatrix0to1[10][13] = -0.202707728670019;
   fWeightMatrix0to1[11][13] = -1.32235508401374;
   fWeightMatrix0to1[12][13] = -1.47325633001467;
   fWeightMatrix0to1[13][13] = -4.03555395789268;
   fWeightMatrix0to1[14][13] = 4.45930927826114;
   fWeightMatrix0to1[15][13] = -1.84782671994847;
   fWeightMatrix0to1[16][13] = 1.85672744856631;
   fWeightMatrix0to1[17][13] = -3.29915285473189;
   fWeightMatrix0to1[18][13] = -0.0712944064877604;
   fWeightMatrix0to1[19][13] = -1.10656633458397;
   fWeightMatrix0to1[20][13] = -0.550470695682733;
   fWeightMatrix0to1[0][14] = -0.659129738991888;
   fWeightMatrix0to1[1][14] = -0.837916154302512;
   fWeightMatrix0to1[2][14] = 0.017763169592371;
   fWeightMatrix0to1[3][14] = 0.635397157228849;
   fWeightMatrix0to1[4][14] = -1.26570259014488;
   fWeightMatrix0to1[5][14] = -0.364557717692419;
   fWeightMatrix0to1[6][14] = -2.65540303077856;
   fWeightMatrix0to1[7][14] = -0.838864472941983;
   fWeightMatrix0to1[8][14] = 3.51158000662555;
   fWeightMatrix0to1[9][14] = -0.225326773938709;
   fWeightMatrix0to1[10][14] = 0.580796196808929;
   fWeightMatrix0to1[11][14] = -0.806540605827694;
   fWeightMatrix0to1[12][14] = -1.26244484329158;
   fWeightMatrix0to1[13][14] = -0.679596140859468;
   fWeightMatrix0to1[14][14] = -0.574552703731263;
   fWeightMatrix0to1[15][14] = -1.33104401345712;
   fWeightMatrix0to1[16][14] = 1.51882649921336;
   fWeightMatrix0to1[17][14] = -2.24387267309951;
   fWeightMatrix0to1[18][14] = -0.431493120332773;
   fWeightMatrix0to1[19][14] = 1.74964236600357;
   fWeightMatrix0to1[20][14] = -1.38282562174036;
   fWeightMatrix0to1[0][15] = 1.97437940535821;
   fWeightMatrix0to1[1][15] = 0.644911291362885;
   fWeightMatrix0to1[2][15] = -1.84435326193074;
   fWeightMatrix0to1[3][15] = 1.08028815472023;
   fWeightMatrix0to1[4][15] = 2.64848940317986;
   fWeightMatrix0to1[5][15] = -0.669712654344987;
   fWeightMatrix0to1[6][15] = -0.780624806703332;
   fWeightMatrix0to1[7][15] = -0.0987912039466361;
   fWeightMatrix0to1[8][15] = -2.81762884437819;
   fWeightMatrix0to1[9][15] = 0.0571773776106247;
   fWeightMatrix0to1[10][15] = 2.22002444935829;
   fWeightMatrix0to1[11][15] = 0.693119415112186;
   fWeightMatrix0to1[12][15] = 1.46409380700025;
   fWeightMatrix0to1[13][15] = -0.815264470626995;
   fWeightMatrix0to1[14][15] = 2.23043344859354;
   fWeightMatrix0to1[15][15] = -1.89958540561368;
   fWeightMatrix0to1[16][15] = 1.34387251102314;
   fWeightMatrix0to1[17][15] = 0.873598485210038;
   fWeightMatrix0to1[18][15] = -0.261050770363391;
   fWeightMatrix0to1[19][15] = -0.0645841697221367;
   fWeightMatrix0to1[20][15] = 0.60136000315453;
   fWeightMatrix0to1[0][16] = -0.156294320317738;
   fWeightMatrix0to1[1][16] = 0.511235182109557;
   fWeightMatrix0to1[2][16] = 0.635203778453328;
   fWeightMatrix0to1[3][16] = -1.14887357271998;
   fWeightMatrix0to1[4][16] = -0.898688658053023;
   fWeightMatrix0to1[5][16] = 7.60012625781515;
   fWeightMatrix0to1[6][16] = 2.31066765239172;
   fWeightMatrix0to1[7][16] = -1.47501725976156;
   fWeightMatrix0to1[8][16] = 0.533635587562136;
   fWeightMatrix0to1[9][16] = -1.24923982748274;
   fWeightMatrix0to1[10][16] = -0.84656241153079;
   fWeightMatrix0to1[11][16] = 0.430166799430876;
   fWeightMatrix0to1[12][16] = 0.321916389324407;
   fWeightMatrix0to1[13][16] = -2.42579108564982;
   fWeightMatrix0to1[14][16] = 2.60237152266434;
   fWeightMatrix0to1[15][16] = 1.59963440963044;
   fWeightMatrix0to1[16][16] = -0.119562073606602;
   fWeightMatrix0to1[17][16] = -0.340432758924258;
   fWeightMatrix0to1[18][16] = -3.4313541504021;
   fWeightMatrix0to1[19][16] = -1.4597907636587;
   fWeightMatrix0to1[20][16] = -1.82183344606845;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 0.899180276400109;
   fWeightMatrix1to2[0][1] = -0.39624266659991;
   fWeightMatrix1to2[0][2] = 0.0598150141863439;
   fWeightMatrix1to2[0][3] = 0.63479324854024;
   fWeightMatrix1to2[0][4] = -0.81130328692859;
   fWeightMatrix1to2[0][5] = -1.33225692918391;
   fWeightMatrix1to2[0][6] = -1.98018836254688;
   fWeightMatrix1to2[0][7] = 1.94947801508609;
   fWeightMatrix1to2[0][8] = -1.2162904410946;
   fWeightMatrix1to2[0][9] = -0.360171613777988;
   fWeightMatrix1to2[0][10] = -0.614053139345153;
   fWeightMatrix1to2[0][11] = -0.891293450509735;
   fWeightMatrix1to2[0][12] = -0.984473820894849;
   fWeightMatrix1to2[0][13] = 0.553233328867375;
   fWeightMatrix1to2[0][14] = -0.581974370307871;
   fWeightMatrix1to2[0][15] = -0.69174239228029;
   fWeightMatrix1to2[0][16] = 0.448950207020972;
   fWeightMatrix1to2[0][17] = 0.816493878536522;
   fWeightMatrix1to2[0][18] = 0.793113178136178;
   fWeightMatrix1to2[0][19] = -0.495317964060254;
   fWeightMatrix1to2[0][20] = 0.809064484081303;
   fWeightMatrix1to2[0][21] = 2.27960167236981;
}

inline double ReadMLPCJ::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLPCJ::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLPCJ::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadMLPCJ::Clear() 
{
   // nothing to clear
}
   inline double ReadMLPCJ::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLPCJ::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 1.93987222119e-11;
   fMax_1[0][0] = 0.731256723404;
   fMin_1[1][0] = 2.11151655094e-05;
   fMax_1[1][0] = 0.729348361492;
   fMin_1[2][0] = 1.93987222119e-11;
   fMax_1[2][0] = 0.731256723404;
   fMin_1[0][1] = 0.0111495917663;
   fMax_1[0][1] = 21.9877300262;
   fMin_1[1][1] = 0.134300857782;
   fMax_1[1][1] = 24.9779434204;
   fMin_1[2][1] = 0.0111495917663;
   fMax_1[2][1] = 24.9779434204;
   fMin_1[0][2] = 0.00189490010962;
   fMax_1[0][2] = 14.9983968735;
   fMin_1[1][2] = 0.0220367405564;
   fMax_1[1][2] = 14.9911079407;
   fMin_1[2][2] = 0.00189490010962;
   fMax_1[2][2] = 14.9983968735;
   fMin_1[0][3] = 0;
   fMax_1[0][3] = 0.134104982018;
   fMin_1[1][3] = 0;
   fMax_1[1][3] = 0.137716650963;
   fMin_1[2][3] = 0;
   fMax_1[2][3] = 0.137716650963;
   fMin_1[0][4] = 62.147693634;
   fMax_1[0][4] = 37961.9179688;
   fMin_1[1][4] = 41.2933425903;
   fMax_1[1][4] = 21269.5722656;
   fMin_1[2][4] = 41.2933425903;
   fMax_1[2][4] = 37961.9179688;
   fMin_1[0][5] = 2.30495882034;
   fMax_1[0][5] = 102.738922119;
   fMin_1[1][5] = 2.78237915039;
   fMax_1[1][5] = 49.5175361633;
   fMin_1[2][5] = 2.30495882034;
   fMax_1[2][5] = 102.738922119;
   fMin_1[0][6] = 2.63570382231e-06;
   fMax_1[0][6] = 0.738568007946;
   fMin_1[1][6] = 3.91690700781e-05;
   fMax_1[1][6] = 0.923672735691;
   fMin_1[2][6] = 2.63570382231e-06;
   fMax_1[2][6] = 0.923672735691;
   fMin_1[0][7] = 2.4348450367e-08;
   fMax_1[0][7] = 0.699207723141;
   fMin_1[1][7] = 5.91529897065e-05;
   fMax_1[1][7] = 0.744905769825;
   fMin_1[2][7] = 2.4348450367e-08;
   fMax_1[2][7] = 0.744905769825;
   fMin_1[0][8] = 6.10736776707e-07;
   fMax_1[0][8] = 1.01704800129;
   fMin_1[1][8] = 3.12057891279e-05;
   fMax_1[1][8] = 1.05343544483;
   fMin_1[2][8] = 6.10736776707e-07;
   fMax_1[2][8] = 1.05343544483;
   fMin_1[0][9] = 0;
   fMax_1[0][9] = 6;
   fMin_1[1][9] = 0;
   fMax_1[1][9] = 7;
   fMin_1[2][9] = 0;
   fMax_1[2][9] = 7;
   fMin_1[0][10] = 0;
   fMax_1[0][10] = 6;
   fMin_1[1][10] = 0;
   fMax_1[1][10] = 8;
   fMin_1[2][10] = 0;
   fMax_1[2][10] = 8;
   fMin_1[0][11] = 0;
   fMax_1[0][11] = 7;
   fMin_1[1][11] = 0;
   fMax_1[1][11] = 8;
   fMin_1[2][11] = 0;
   fMax_1[2][11] = 8;
   fMin_1[0][12] = 0.00300450995564;
   fMax_1[0][12] = 1;
   fMin_1[1][12] = 0.0038299348671;
   fMax_1[1][12] = 1;
   fMin_1[2][12] = 0.00300450995564;
   fMax_1[2][12] = 1;
   fMin_1[0][13] = 0.0559116005898;
   fMax_1[0][13] = 72.067237854;
   fMin_1[1][13] = 0.144289746881;
   fMax_1[1][13] = 84.5542831421;
   fMin_1[2][13] = 0.0559116005898;
   fMax_1[2][13] = 84.5542831421;
   fMin_1[0][14] = 0.0131226135418;
   fMax_1[0][14] = 75.9046707153;
   fMin_1[1][14] = 0.146247655153;
   fMax_1[1][14] = 67.7235794067;
   fMin_1[2][14] = 0.0131226135418;
   fMax_1[2][14] = 75.9046707153;
   fMin_1[0][15] = 0.0151327997446;
   fMax_1[0][15] = 79.3785171509;
   fMin_1[1][15] = 0.0453270226717;
   fMax_1[1][15] = 68.506652832;
   fMin_1[2][15] = 0.0151327997446;
   fMax_1[2][15] = 79.3785171509;
}

//_______________________________________________________________________
inline void ReadMLPCJ::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 16;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   std::vector<int> indicesGet;
   std::vector<int> indicesPut;

   indicesGet.push_back( 0);
   indicesGet.push_back( 1);
   indicesGet.push_back( 2);
   indicesGet.push_back( 3);
   indicesGet.push_back( 4);
   indicesGet.push_back( 5);
   indicesGet.push_back( 6);
   indicesGet.push_back( 7);
   indicesGet.push_back( 8);
   indicesGet.push_back( 9);
   indicesGet.push_back( 10);
   indicesGet.push_back( 11);
   indicesGet.push_back( 12);
   indicesGet.push_back( 13);
   indicesGet.push_back( 14);
   indicesGet.push_back( 15);
   indicesPut.push_back( 0);
   indicesPut.push_back( 1);
   indicesPut.push_back( 2);
   indicesPut.push_back( 3);
   indicesPut.push_back( 4);
   indicesPut.push_back( 5);
   indicesPut.push_back( 6);
   indicesPut.push_back( 7);
   indicesPut.push_back( 8);
   indicesPut.push_back( 9);
   indicesPut.push_back( 10);
   indicesPut.push_back( 11);
   indicesPut.push_back( 12);
   indicesPut.push_back( 13);
   indicesPut.push_back( 14);
   indicesPut.push_back( 15);

   std::vector<double> dv(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<16;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLPCJ::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLPCJ::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
