// Class: ReadMLPMSE
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLPMSE
TMVA Release   : 4.1.4         [262404]
ROOT Release   : 5.34/07       [336391]
Creator        : pseyfert
Date           : Thu Dec 12 16:58:59 2013
Host           : Linux lxbuild175.cern.ch 2.6.18-308.4.1.el5 #1 SMP Wed Apr 18 16:26:27 CEST 2012 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /auto/sigma0/pseyfert/zoontuple/Bender_v22r7/Phys/Tau23Mu/scripts/TMVA_training
Training events: 52358
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 14
TMath::Exp(-1000*LifeTime)    TMath_Exp__M_1000_T_LifeTime_ TMath::Exp(-1000*LifeTime)    transformed decay time        1                                 'F'    [1.93987222119e-11,0.731256723404]
IPSig                         IPSig                         IPSig                         IP significance               1                                 'F'    [0.0111495917663,24.9779434204]
VertexChi2                    VertexChi2                    VertexChi2                    vertex #chi^{2}               1                                 'F'    [0.000802233349532,14.9983968735]
acos(dira)                    acos_dira_                    acos(dira)                    pointing angle                1                                 'F'    [0,0.137716650963]
pt                            pt                            pt                            p_{T}                         [MeV/c]                           'F'    [41.2933425903,55240.3476562]
Laura_SumBDT                  Laura_SumBDT                  Laura_SumBDT                  Laura_SumBDT                                                    'F'    [-2.57286167145,5]
min(p0_IPSig,min(p1_IPSig,p2_IPSig)) min_p0_IPSig,min_p1_IPSig,p2_IPSig__ min(p0_IPSig,min(p1_IPSig,p2_IPSig)) min. #mu IP significance             1                                        'F'    [2.30495882034,102.738922119]
DOCAone                       DOCAone                       DOCAone                       DOCA (#mu 1 and 2)            mm                                'F'    [2.63570382231e-06,0.923672735691]
DOCAtwo                       DOCAtwo                       DOCAtwo                       DOCA (#mu 2 and 3)            mm                                'F'    [2.4348450367e-08,0.744905769825]
DOCAthree                     DOCAthree                     DOCAthree                     DOCA (#mu 1 and 3)            mm                                'F'    [6.10736776707e-07,1.05343544483]
CDF3                          CDF3                          CDF3                          cone isolation                1                                 'F'    [0.00300450995564,1]
p0_track_MatchChi2            p0_track_MatchChi2            p0_track_MatchChi2            track match #chi^{2} (#mu 1)  1                                 'F'    [0.0438715070486,84.5542831421]
p1_track_MatchChi2            p1_track_MatchChi2            p1_track_MatchChi2            track match #chi^{2} (#mu 2)  1                                 'F'    [0.0131226135418,75.9046707153]
p2_track_MatchChi2            p2_track_MatchChi2            p2_track_MatchChi2            track match #chi^{2} (#mu 3)  1                                 'F'    [0.0151327997446,79.3785171509]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLPMSE : public IClassifierReader {

 public:

   // constructor
   ReadMLPMSE( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLPMSE" ),
        fNvars( 14 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "TMath::Exp(-1000*LifeTime)", "IPSig", "VertexChi2", "acos(dira)", "pt", "Laura_SumBDT", "min(p0_IPSig,min(p1_IPSig,p2_IPSig))", "DOCAone", "DOCAtwo", "DOCAthree", "CDF3", "p0_track_MatchChi2", "p1_track_MatchChi2", "p2_track_MatchChi2" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 0.99999988079071;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 0.99999988079071;
      fVmin[7] = -1;
      fVmax[7] = 0.99999988079071;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 0.99999988079071;
      fVmin[11] = -1;
      fVmax[11] = 1;
      fVmin[12] = -1;
      fVmax[12] = 1;
      fVmin[13] = -1;
      fVmax[13] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLPMSE() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][14];
   double fMax_1[3][14];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[14];
   double fVmax[14];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[14];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[20][15];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][20];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLPMSE::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 15; fWeights[0] = new double[15]; 
   fLayerSize[1] = 20; fWeights[1] = new double[20]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.150425268769368;
   fWeightMatrix0to1[1][0] = 0.107519354050832;
   fWeightMatrix0to1[2][0] = 1.13568892850905;
   fWeightMatrix0to1[3][0] = 1.31821840823732;
   fWeightMatrix0to1[4][0] = -1.65436819924918;
   fWeightMatrix0to1[5][0] = 0.00718255671915879;
   fWeightMatrix0to1[6][0] = -0.515456826439245;
   fWeightMatrix0to1[7][0] = 2.08286146657731;
   fWeightMatrix0to1[8][0] = -0.344471389442023;
   fWeightMatrix0to1[9][0] = -1.48321767418509;
   fWeightMatrix0to1[10][0] = -1.36955126689671;
   fWeightMatrix0to1[11][0] = 0.506227089535052;
   fWeightMatrix0to1[12][0] = -1.15957169059334;
   fWeightMatrix0to1[13][0] = -0.177020652175773;
   fWeightMatrix0to1[14][0] = -0.486091265664379;
   fWeightMatrix0to1[15][0] = 0.881844174526972;
   fWeightMatrix0to1[16][0] = -0.420094071501541;
   fWeightMatrix0to1[17][0] = 1.22165966530756;
   fWeightMatrix0to1[18][0] = -0.241431104960552;
   fWeightMatrix0to1[0][1] = 1.14759589448633;
   fWeightMatrix0to1[1][1] = 0.190769243978192;
   fWeightMatrix0to1[2][1] = -0.302880414154664;
   fWeightMatrix0to1[3][1] = 1.28129882091124;
   fWeightMatrix0to1[4][1] = 0.505374172698385;
   fWeightMatrix0to1[5][1] = -2.88513937457513;
   fWeightMatrix0to1[6][1] = -0.000591918047624357;
   fWeightMatrix0to1[7][1] = 1.63250136213082;
   fWeightMatrix0to1[8][1] = -2.65674135630069;
   fWeightMatrix0to1[9][1] = -2.46799751408027;
   fWeightMatrix0to1[10][1] = 0.0663429980401018;
   fWeightMatrix0to1[11][1] = -0.156152628931109;
   fWeightMatrix0to1[12][1] = 1.50199677829623;
   fWeightMatrix0to1[13][1] = -0.622864325716479;
   fWeightMatrix0to1[14][1] = -0.299026810544379;
   fWeightMatrix0to1[15][1] = 0.582128288677974;
   fWeightMatrix0to1[16][1] = -0.080821455201663;
   fWeightMatrix0to1[17][1] = -1.25257784585296;
   fWeightMatrix0to1[18][1] = 0.494599857850444;
   fWeightMatrix0to1[0][2] = -1.02622928811091;
   fWeightMatrix0to1[1][2] = 0.587002460329337;
   fWeightMatrix0to1[2][2] = 0.773142599905593;
   fWeightMatrix0to1[3][2] = 0.762691353302126;
   fWeightMatrix0to1[4][2] = 1.56053165649475;
   fWeightMatrix0to1[5][2] = 0.245168715768719;
   fWeightMatrix0to1[6][2] = -0.567536682098127;
   fWeightMatrix0to1[7][2] = -1.65390490937286;
   fWeightMatrix0to1[8][2] = -0.228121850573207;
   fWeightMatrix0to1[9][2] = -0.235911411838762;
   fWeightMatrix0to1[10][2] = 1.45767163093573;
   fWeightMatrix0to1[11][2] = 0.0284436447865057;
   fWeightMatrix0to1[12][2] = 1.44428860246112;
   fWeightMatrix0to1[13][2] = 1.00112383286801;
   fWeightMatrix0to1[14][2] = -1.46857931811343;
   fWeightMatrix0to1[15][2] = 0.741325489622503;
   fWeightMatrix0to1[16][2] = -1.64190924805395;
   fWeightMatrix0to1[17][2] = -0.950921803745286;
   fWeightMatrix0to1[18][2] = -0.279910590737774;
   fWeightMatrix0to1[0][3] = -2.38631202223451;
   fWeightMatrix0to1[1][3] = 1.69963454798493;
   fWeightMatrix0to1[2][3] = 0.934106982746482;
   fWeightMatrix0to1[3][3] = -0.953718997089967;
   fWeightMatrix0to1[4][3] = 1.00805470524631;
   fWeightMatrix0to1[5][3] = -1.03734554811789;
   fWeightMatrix0to1[6][3] = 0.993216541978205;
   fWeightMatrix0to1[7][3] = 1.39839986178586;
   fWeightMatrix0to1[8][3] = -1.06533442959281;
   fWeightMatrix0to1[9][3] = -0.580910677469995;
   fWeightMatrix0to1[10][3] = -1.57791934490182;
   fWeightMatrix0to1[11][3] = 0.929818891913905;
   fWeightMatrix0to1[12][3] = -0.950594836279067;
   fWeightMatrix0to1[13][3] = -1.25455961808931;
   fWeightMatrix0to1[14][3] = -1.52704524684913;
   fWeightMatrix0to1[15][3] = 1.09911298776167;
   fWeightMatrix0to1[16][3] = 1.32670145427883;
   fWeightMatrix0to1[17][3] = 0.785073077842745;
   fWeightMatrix0to1[18][3] = -0.725873693242518;
   fWeightMatrix0to1[0][4] = -2.00985809786007;
   fWeightMatrix0to1[1][4] = -2.03608699110955;
   fWeightMatrix0to1[2][4] = 1.45994704925969;
   fWeightMatrix0to1[3][4] = 1.17154614446407;
   fWeightMatrix0to1[4][4] = 2.54438433975438;
   fWeightMatrix0to1[5][4] = 0.615563879696388;
   fWeightMatrix0to1[6][4] = 1.51411373436624;
   fWeightMatrix0to1[7][4] = -0.375096996772847;
   fWeightMatrix0to1[8][4] = 0.402358804633955;
   fWeightMatrix0to1[9][4] = -0.085574377789726;
   fWeightMatrix0to1[10][4] = 0.794953607289329;
   fWeightMatrix0to1[11][4] = -0.620217696513679;
   fWeightMatrix0to1[12][4] = -1.74495529883818;
   fWeightMatrix0to1[13][4] = -2.0959273710872;
   fWeightMatrix0to1[14][4] = -0.457073921432795;
   fWeightMatrix0to1[15][4] = 0.175035365296194;
   fWeightMatrix0to1[16][4] = 1.99131354481342;
   fWeightMatrix0to1[17][4] = -1.98652124789314;
   fWeightMatrix0to1[18][4] = -1.00794954886738;
   fWeightMatrix0to1[0][5] = 1.3489135434142;
   fWeightMatrix0to1[1][5] = 3.11337052672132;
   fWeightMatrix0to1[2][5] = -1.21127037855441;
   fWeightMatrix0to1[3][5] = -1.04784569860448;
   fWeightMatrix0to1[4][5] = 0.487160096280808;
   fWeightMatrix0to1[5][5] = -2.53518746947492;
   fWeightMatrix0to1[6][5] = -1.43586290704495;
   fWeightMatrix0to1[7][5] = 0.763868283790126;
   fWeightMatrix0to1[8][5] = -0.913333017538875;
   fWeightMatrix0to1[9][5] = -0.738200271104178;
   fWeightMatrix0to1[10][5] = 1.4431695245338;
   fWeightMatrix0to1[11][5] = -1.23386725976001;
   fWeightMatrix0to1[12][5] = -0.869550854538847;
   fWeightMatrix0to1[13][5] = -0.41767400638676;
   fWeightMatrix0to1[14][5] = 0.222595223050255;
   fWeightMatrix0to1[15][5] = -1.49448911021223;
   fWeightMatrix0to1[16][5] = 0.523989643367899;
   fWeightMatrix0to1[17][5] = 0.0321499709014665;
   fWeightMatrix0to1[18][5] = 0.563483983655161;
   fWeightMatrix0to1[0][6] = -1.77798612814967;
   fWeightMatrix0to1[1][6] = -0.365726307650502;
   fWeightMatrix0to1[2][6] = 1.00428118564761;
   fWeightMatrix0to1[3][6] = -0.253855570579548;
   fWeightMatrix0to1[4][6] = 1.46335532718175;
   fWeightMatrix0to1[5][6] = 0.815478077593776;
   fWeightMatrix0to1[6][6] = -1.09663408125287;
   fWeightMatrix0to1[7][6] = 0.400121831665366;
   fWeightMatrix0to1[8][6] = 1.05281511359943;
   fWeightMatrix0to1[9][6] = 3.35142286235541;
   fWeightMatrix0to1[10][6] = 0.250436462180205;
   fWeightMatrix0to1[11][6] = 0.327153704968124;
   fWeightMatrix0to1[12][6] = -0.465017964411926;
   fWeightMatrix0to1[13][6] = -0.454876872637149;
   fWeightMatrix0to1[14][6] = -2.07007058472359;
   fWeightMatrix0to1[15][6] = 1.34308693424079;
   fWeightMatrix0to1[16][6] = 0.545225935308921;
   fWeightMatrix0to1[17][6] = -1.76401682318809;
   fWeightMatrix0to1[18][6] = 0.16934728121243;
   fWeightMatrix0to1[0][7] = -1.89260866877824;
   fWeightMatrix0to1[1][7] = 0.409407862881903;
   fWeightMatrix0to1[2][7] = 1.71219611931501;
   fWeightMatrix0to1[3][7] = 2.16746488051073;
   fWeightMatrix0to1[4][7] = -1.16431095947605;
   fWeightMatrix0to1[5][7] = -0.103076740091877;
   fWeightMatrix0to1[6][7] = 2.00367843160606;
   fWeightMatrix0to1[7][7] = 1.88810177415003;
   fWeightMatrix0to1[8][7] = -0.130044113895215;
   fWeightMatrix0to1[9][7] = -1.37510529431109;
   fWeightMatrix0to1[10][7] = -0.683942555663753;
   fWeightMatrix0to1[11][7] = -0.828705784723901;
   fWeightMatrix0to1[12][7] = 1.44942783152736;
   fWeightMatrix0to1[13][7] = 0.608329169435396;
   fWeightMatrix0to1[14][7] = -0.709051573474305;
   fWeightMatrix0to1[15][7] = -0.213535367360231;
   fWeightMatrix0to1[16][7] = 0.493315078708458;
   fWeightMatrix0to1[17][7] = -1.84068084483948;
   fWeightMatrix0to1[18][7] = 0.0951953967182466;
   fWeightMatrix0to1[0][8] = 1.24541754635097;
   fWeightMatrix0to1[1][8] = 0.557568232605041;
   fWeightMatrix0to1[2][8] = 0.129086215646567;
   fWeightMatrix0to1[3][8] = 0.734118020314202;
   fWeightMatrix0to1[4][8] = 1.62465688025277;
   fWeightMatrix0to1[5][8] = 0.390961617540635;
   fWeightMatrix0to1[6][8] = 1.33399779714913;
   fWeightMatrix0to1[7][8] = -1.15672306540832;
   fWeightMatrix0to1[8][8] = 0.567453288420874;
   fWeightMatrix0to1[9][8] = -0.0805002771966455;
   fWeightMatrix0to1[10][8] = 0.128196626578136;
   fWeightMatrix0to1[11][8] = 0.690657895851507;
   fWeightMatrix0to1[12][8] = 0.849689857330232;
   fWeightMatrix0to1[13][8] = -1.16581377338201;
   fWeightMatrix0to1[14][8] = -0.838545336238377;
   fWeightMatrix0to1[15][8] = 1.33900279887036;
   fWeightMatrix0to1[16][8] = -0.488842206892822;
   fWeightMatrix0to1[17][8] = -0.952956339906099;
   fWeightMatrix0to1[18][8] = 1.27477808804576;
   fWeightMatrix0to1[0][9] = 0.368432003259772;
   fWeightMatrix0to1[1][9] = -1.47308237079864;
   fWeightMatrix0to1[2][9] = 1.90427725411353;
   fWeightMatrix0to1[3][9] = 2.24228064408538;
   fWeightMatrix0to1[4][9] = -1.1670559042599;
   fWeightMatrix0to1[5][9] = -0.177827304162306;
   fWeightMatrix0to1[6][9] = 0.519031016416026;
   fWeightMatrix0to1[7][9] = 0.643908118604287;
   fWeightMatrix0to1[8][9] = -0.107736626612806;
   fWeightMatrix0to1[9][9] = -1.8405496222614;
   fWeightMatrix0to1[10][9] = 0.733064786395714;
   fWeightMatrix0to1[11][9] = 1.71381854917567;
   fWeightMatrix0to1[12][9] = -1.88322987578839;
   fWeightMatrix0to1[13][9] = -0.802848376263968;
   fWeightMatrix0to1[14][9] = -0.790494842994037;
   fWeightMatrix0to1[15][9] = 0.417057451031276;
   fWeightMatrix0to1[16][9] = 2.08271169370202;
   fWeightMatrix0to1[17][9] = -0.896812629453106;
   fWeightMatrix0to1[18][9] = -0.279250498407356;
   fWeightMatrix0to1[0][10] = -1.13248547147306;
   fWeightMatrix0to1[1][10] = -0.351418490836416;
   fWeightMatrix0to1[2][10] = 1.35917628592577;
   fWeightMatrix0to1[3][10] = 1.05529392340213;
   fWeightMatrix0to1[4][10] = -0.0202053107713915;
   fWeightMatrix0to1[5][10] = 0.131819099718816;
   fWeightMatrix0to1[6][10] = -1.58682278808459;
   fWeightMatrix0to1[7][10] = 1.40943099482071;
   fWeightMatrix0to1[8][10] = 0.138634225542471;
   fWeightMatrix0to1[9][10] = 0.0373069754797861;
   fWeightMatrix0to1[10][10] = -0.108489645265853;
   fWeightMatrix0to1[11][10] = -0.215466530019743;
   fWeightMatrix0to1[12][10] = 0.20086726436162;
   fWeightMatrix0to1[13][10] = -1.53839339371279;
   fWeightMatrix0to1[14][10] = 1.41492223909529;
   fWeightMatrix0to1[15][10] = 0.714557261997111;
   fWeightMatrix0to1[16][10] = -0.513568709452259;
   fWeightMatrix0to1[17][10] = -0.476286815907934;
   fWeightMatrix0to1[18][10] = 0.379159923266629;
   fWeightMatrix0to1[0][11] = 0.498680336550098;
   fWeightMatrix0to1[1][11] = 0.896921834990758;
   fWeightMatrix0to1[2][11] = 0.34433812595808;
   fWeightMatrix0to1[3][11] = -1.23279107737169;
   fWeightMatrix0to1[4][11] = -0.338679773094988;
   fWeightMatrix0to1[5][11] = 0.851087325267124;
   fWeightMatrix0to1[6][11] = 1.60469966910377;
   fWeightMatrix0to1[7][11] = 1.52469058359606;
   fWeightMatrix0to1[8][11] = -0.745265752171321;
   fWeightMatrix0to1[9][11] = 0.480842505371768;
   fWeightMatrix0to1[10][11] = -1.8471715177965;
   fWeightMatrix0to1[11][11] = 0.0206897214675819;
   fWeightMatrix0to1[12][11] = -0.222035776784165;
   fWeightMatrix0to1[13][11] = -1.58581942442819;
   fWeightMatrix0to1[14][11] = 0.744046830361731;
   fWeightMatrix0to1[15][11] = 2.15230857181771;
   fWeightMatrix0to1[16][11] = -0.843066609239896;
   fWeightMatrix0to1[17][11] = 0.272401690914636;
   fWeightMatrix0to1[18][11] = -0.452567377271496;
   fWeightMatrix0to1[0][12] = -1.49444475938388;
   fWeightMatrix0to1[1][12] = 0.403710766753728;
   fWeightMatrix0to1[2][12] = 0.923376910950977;
   fWeightMatrix0to1[3][12] = 0.960267508005998;
   fWeightMatrix0to1[4][12] = 1.4667176062649;
   fWeightMatrix0to1[5][12] = -0.0115031851986201;
   fWeightMatrix0to1[6][12] = 1.88345697766827;
   fWeightMatrix0to1[7][12] = -1.25809763113186;
   fWeightMatrix0to1[8][12] = -0.327501415362508;
   fWeightMatrix0to1[9][12] = -0.526359844378498;
   fWeightMatrix0to1[10][12] = -1.43102202238388;
   fWeightMatrix0to1[11][12] = -0.772837336274382;
   fWeightMatrix0to1[12][12] = -2.05786896106466;
   fWeightMatrix0to1[13][12] = -0.798590179795197;
   fWeightMatrix0to1[14][12] = -1.81664493010389;
   fWeightMatrix0to1[15][12] = -1.18555262445672;
   fWeightMatrix0to1[16][12] = -1.46802198237917;
   fWeightMatrix0to1[17][12] = -0.507143076806783;
   fWeightMatrix0to1[18][12] = -1.18204294610157;
   fWeightMatrix0to1[0][13] = -2.32406225682598;
   fWeightMatrix0to1[1][13] = 1.17240445358396;
   fWeightMatrix0to1[2][13] = -0.1150101940543;
   fWeightMatrix0to1[3][13] = 0.73778561850983;
   fWeightMatrix0to1[4][13] = -0.363328300141314;
   fWeightMatrix0to1[5][13] = 0.501799021776949;
   fWeightMatrix0to1[6][13] = 1.91805123132651;
   fWeightMatrix0to1[7][13] = 1.45586407896356;
   fWeightMatrix0to1[8][13] = 0.567579390149939;
   fWeightMatrix0to1[9][13] = 0.279180931011974;
   fWeightMatrix0to1[10][13] = -1.67643595202136;
   fWeightMatrix0to1[11][13] = -0.610743745084481;
   fWeightMatrix0to1[12][13] = -1.60217143617384;
   fWeightMatrix0to1[13][13] = -0.213245157834178;
   fWeightMatrix0to1[14][13] = 0.0441617694365703;
   fWeightMatrix0to1[15][13] = 1.96307430512457;
   fWeightMatrix0to1[16][13] = 0.0572444238874624;
   fWeightMatrix0to1[17][13] = -0.14683295893761;
   fWeightMatrix0to1[18][13] = -0.608417829153667;
   fWeightMatrix0to1[0][14] = -1.33113222405231;
   fWeightMatrix0to1[1][14] = 1.12462122162686;
   fWeightMatrix0to1[2][14] = 0.428748753019604;
   fWeightMatrix0to1[3][14] = -1.55072294247261;
   fWeightMatrix0to1[4][14] = -1.82319274959832;
   fWeightMatrix0to1[5][14] = 0.27297200040302;
   fWeightMatrix0to1[6][14] = 0.683782662237255;
   fWeightMatrix0to1[7][14] = 0.140539034252079;
   fWeightMatrix0to1[8][14] = -1.07995906643891;
   fWeightMatrix0to1[9][14] = -0.15695621524635;
   fWeightMatrix0to1[10][14] = 2.01298124638196;
   fWeightMatrix0to1[11][14] = 0.484274673031198;
   fWeightMatrix0to1[12][14] = 1.1151365038019;
   fWeightMatrix0to1[13][14] = 0.357079899555914;
   fWeightMatrix0to1[14][14] = 0.501870725473048;
   fWeightMatrix0to1[15][14] = -0.617967846928883;
   fWeightMatrix0to1[16][14] = -1.89367201680157;
   fWeightMatrix0to1[17][14] = -0.0217015325594026;
   fWeightMatrix0to1[18][14] = -1.46750945875342;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -0.452577548038976;
   fWeightMatrix1to2[0][1] = -0.308851874083546;
   fWeightMatrix1to2[0][2] = 1.37337664627843;
   fWeightMatrix1to2[0][3] = -1.03660455625031;
   fWeightMatrix1to2[0][4] = 0.234028005762933;
   fWeightMatrix1to2[0][5] = -0.308911082822523;
   fWeightMatrix1to2[0][6] = 0.273474095426008;
   fWeightMatrix1to2[0][7] = -0.138781997307297;
   fWeightMatrix1to2[0][8] = 0.300318447351294;
   fWeightMatrix1to2[0][9] = 0.259539027450982;
   fWeightMatrix1to2[0][10] = -1.20103913384678;
   fWeightMatrix1to2[0][11] = 0.037415256190522;
   fWeightMatrix1to2[0][12] = 0.741383178656077;
   fWeightMatrix1to2[0][13] = -1.48642646328468;
   fWeightMatrix1to2[0][14] = -1.1146273305513;
   fWeightMatrix1to2[0][15] = -1.81984311445223;
   fWeightMatrix1to2[0][16] = -0.695651960775242;
   fWeightMatrix1to2[0][17] = 1.66285668860123;
   fWeightMatrix1to2[0][18] = -0.0429501864402135;
   fWeightMatrix1to2[0][19] = 0.500515199288966;
}

inline double ReadMLPMSE::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLPMSE::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLPMSE::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLPMSE::Clear() 
{
   // nothing to clear
}
   inline double ReadMLPMSE::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLPMSE::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 1.93987222119e-11;
   fMax_1[0][0] = 0.731256723404;
   fMin_1[1][0] = 2.11151655094e-05;
   fMax_1[1][0] = 0.729348361492;
   fMin_1[2][0] = 1.93987222119e-11;
   fMax_1[2][0] = 0.731256723404;
   fMin_1[0][1] = 0.0111495917663;
   fMax_1[0][1] = 21.9877300262;
   fMin_1[1][1] = 0.134300857782;
   fMax_1[1][1] = 24.9779434204;
   fMin_1[2][1] = 0.0111495917663;
   fMax_1[2][1] = 24.9779434204;
   fMin_1[0][2] = 0.000802233349532;
   fMax_1[0][2] = 14.9983968735;
   fMin_1[1][2] = 0.0220367405564;
   fMax_1[1][2] = 14.9911079407;
   fMin_1[2][2] = 0.000802233349532;
   fMax_1[2][2] = 14.9983968735;
   fMin_1[0][3] = 0;
   fMax_1[0][3] = 0.134104982018;
   fMin_1[1][3] = 0;
   fMax_1[1][3] = 0.137716650963;
   fMin_1[2][3] = 0;
   fMax_1[2][3] = 0.137716650963;
   fMin_1[0][4] = 62.147693634;
   fMax_1[0][4] = 55240.3476562;
   fMin_1[1][4] = 41.2933425903;
   fMax_1[1][4] = 21269.5722656;
   fMin_1[2][4] = 41.2933425903;
   fMax_1[2][4] = 55240.3476562;
   fMin_1[0][5] = -2.57286167145;
   fMax_1[0][5] = 5;
   fMin_1[1][5] = -2.21387171745;
   fMax_1[1][5] = -0.0525252744555;
   fMin_1[2][5] = -2.57286167145;
   fMax_1[2][5] = 5;
   fMin_1[0][6] = 2.30495882034;
   fMax_1[0][6] = 102.738922119;
   fMin_1[1][6] = 2.78237915039;
   fMax_1[1][6] = 51.1214294434;
   fMin_1[2][6] = 2.30495882034;
   fMax_1[2][6] = 102.738922119;
   fMin_1[0][7] = 2.63570382231e-06;
   fMax_1[0][7] = 0.815600574017;
   fMin_1[1][7] = 3.91690700781e-05;
   fMax_1[1][7] = 0.923672735691;
   fMin_1[2][7] = 2.63570382231e-06;
   fMax_1[2][7] = 0.923672735691;
   fMin_1[0][8] = 2.4348450367e-08;
   fMax_1[0][8] = 0.699207723141;
   fMin_1[1][8] = 4.24376266892e-05;
   fMax_1[1][8] = 0.744905769825;
   fMin_1[2][8] = 2.4348450367e-08;
   fMax_1[2][8] = 0.744905769825;
   fMin_1[0][9] = 6.10736776707e-07;
   fMax_1[0][9] = 1.01704800129;
   fMin_1[1][9] = 3.12057891279e-05;
   fMax_1[1][9] = 1.05343544483;
   fMin_1[2][9] = 6.10736776707e-07;
   fMax_1[2][9] = 1.05343544483;
   fMin_1[0][10] = 0.00300450995564;
   fMax_1[0][10] = 1;
   fMin_1[1][10] = 0.0038299348671;
   fMax_1[1][10] = 1;
   fMin_1[2][10] = 0.00300450995564;
   fMax_1[2][10] = 1;
   fMin_1[0][11] = 0.0438715070486;
   fMax_1[0][11] = 77.6154556274;
   fMin_1[1][11] = 0.144289746881;
   fMax_1[1][11] = 84.5542831421;
   fMin_1[2][11] = 0.0438715070486;
   fMax_1[2][11] = 84.5542831421;
   fMin_1[0][12] = 0.0131226135418;
   fMax_1[0][12] = 75.9046707153;
   fMin_1[1][12] = 0.146247655153;
   fMax_1[1][12] = 67.7235794067;
   fMin_1[2][12] = 0.0131226135418;
   fMax_1[2][12] = 75.9046707153;
   fMin_1[0][13] = 0.0151327997446;
   fMax_1[0][13] = 79.3785171509;
   fMin_1[1][13] = 0.0453270226717;
   fMax_1[1][13] = 68.506652832;
   fMin_1[2][13] = 0.0151327997446;
   fMax_1[2][13] = 79.3785171509;
}

//_______________________________________________________________________
inline void ReadMLPMSE::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 14;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   std::vector<int> indicesGet;
   std::vector<int> indicesPut;

   indicesGet.push_back( 0);
   indicesGet.push_back( 1);
   indicesGet.push_back( 2);
   indicesGet.push_back( 3);
   indicesGet.push_back( 4);
   indicesGet.push_back( 5);
   indicesGet.push_back( 6);
   indicesGet.push_back( 7);
   indicesGet.push_back( 8);
   indicesGet.push_back( 9);
   indicesGet.push_back( 10);
   indicesGet.push_back( 11);
   indicesGet.push_back( 12);
   indicesGet.push_back( 13);
   indicesPut.push_back( 0);
   indicesPut.push_back( 1);
   indicesPut.push_back( 2);
   indicesPut.push_back( 3);
   indicesPut.push_back( 4);
   indicesPut.push_back( 5);
   indicesPut.push_back( 6);
   indicesPut.push_back( 7);
   indicesPut.push_back( 8);
   indicesPut.push_back( 9);
   indicesPut.push_back( 10);
   indicesPut.push_back( 11);
   indicesPut.push_back( 12);
   indicesPut.push_back( 13);

   std::vector<double> dv(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<14;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLPMSE::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLPMSE::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
