// Class: ReadMLPCJ
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLPCJ
TMVA Release   : 4.1.4         [262404]
ROOT Release   : 5.34/07       [336391]
Creator        : pseyfert
Date           : Sat Dec 21 19:39:19 2013
Host           : Linux lxbuild175.cern.ch 2.6.18-308.4.1.el5 #1 SMP Wed Apr 18 16:26:27 CEST 2012 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /auto/sigma0/pseyfert/zoontuple/Bender_v22r7/Phys/Tau23Mu/scripts/TMVA_training_v3
Training events: 41107
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 13
TMath::Exp(-1000*LifeTime)    TMath_Exp__M_1000_T_LifeTime_ TMath::Exp(-1000*LifeTime)    transformed decay time        1                                 'F'    [1.93987222119e-11,0.731256723404]
IPSig                         IPSig                         IPSig                         IP significance               1                                 'F'    [0.0111495917663,24.9779434204]
VertexChi2                    VertexChi2                    VertexChi2                    vertex #chi^{2}               1                                 'F'    [0.00189490010962,14.9983968735]
acos(dira)                    acos_dira_                    acos(dira)                    pointing angle                1                                 'F'    [0,0.137716650963]
pt                            pt                            pt                            p_{T}                         [MeV/c]                           'F'    [41.2933425903,37961.9179688]
min(p0_IPSig,min(p1_IPSig,p2_IPSig)) min_p0_IPSig,min_p1_IPSig,p2_IPSig__ min(p0_IPSig,min(p1_IPSig,p2_IPSig)) min. #mu IP significance             1                                        'F'    [2.30495882034,102.738922119]
DOCAone                       DOCAone                       DOCAone                       DOCA (#mu 1 and 2)            mm                                'F'    [2.63570382231e-06,0.923672735691]
DOCAtwo                       DOCAtwo                       DOCAtwo                       DOCA (#mu 2 and 3)            mm                                'F'    [2.4348450367e-08,0.744905769825]
DOCAthree                     DOCAthree                     DOCAthree                     DOCA (#mu 1 and 3)            mm                                'F'    [6.10736776707e-07,1.05343544483]
CDF3                          CDF3                          CDF3                          cone isolation                1                                 'F'    [0.00300450995564,1]
p0_track_MatchChi2            p0_track_MatchChi2            p0_track_MatchChi2            track match #chi^{2} (#mu 1)  1                                 'F'    [0.0559116005898,84.5542831421]
p1_track_MatchChi2            p1_track_MatchChi2            p1_track_MatchChi2            track match #chi^{2} (#mu 2)  1                                 'F'    [0.0131226135418,75.9046707153]
p2_track_MatchChi2            p2_track_MatchChi2            p2_track_MatchChi2            track match #chi^{2} (#mu 3)  1                                 'F'    [0.0151327997446,79.3785171509]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLPCJ : public IClassifierReader {

 public:

   // constructor
   ReadMLPCJ( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLPCJ" ),
        fNvars( 13 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "TMath::Exp(-1000*LifeTime)", "IPSig", "VertexChi2", "acos(dira)", "pt", "min(p0_IPSig,min(p1_IPSig,p2_IPSig))", "DOCAone", "DOCAtwo", "DOCAthree", "CDF3", "p0_track_MatchChi2", "p1_track_MatchChi2", "p2_track_MatchChi2" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 0.99999988079071;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 0.99999988079071;
      fVmin[6] = -1;
      fVmax[6] = 0.99999988079071;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 0.99999988079071;
      fVmin[10] = -1;
      fVmax[10] = 1;
      fVmin[11] = -1;
      fVmax[11] = 1;
      fVmin[12] = -1;
      fVmax[12] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLPCJ() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][13];
   double fMax_1[3][13];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[13];
   double fVmax[13];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[13];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[19][14];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][19];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLPCJ::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 14; fWeights[0] = new double[14]; 
   fLayerSize[1] = 19; fWeights[1] = new double[19]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -2.54700478053674;
   fWeightMatrix0to1[1][0] = 1.11704852722777;
   fWeightMatrix0to1[2][0] = -1.04031431515344;
   fWeightMatrix0to1[3][0] = 2.2802586467375;
   fWeightMatrix0to1[4][0] = -0.99952925570912;
   fWeightMatrix0to1[5][0] = -0.233089981401194;
   fWeightMatrix0to1[6][0] = -1.06674702760054;
   fWeightMatrix0to1[7][0] = 0.656356139536571;
   fWeightMatrix0to1[8][0] = -1.67184517533455;
   fWeightMatrix0to1[9][0] = -0.230499153761936;
   fWeightMatrix0to1[10][0] = -1.46977676768786;
   fWeightMatrix0to1[11][0] = 0.0463378138759318;
   fWeightMatrix0to1[12][0] = -0.727377530583022;
   fWeightMatrix0to1[13][0] = -0.117848307210798;
   fWeightMatrix0to1[14][0] = 1.58172439391642;
   fWeightMatrix0to1[15][0] = 0.277813061836587;
   fWeightMatrix0to1[16][0] = 0.0105829399123739;
   fWeightMatrix0to1[17][0] = 1.86044598109155;
   fWeightMatrix0to1[0][1] = -0.340701950946645;
   fWeightMatrix0to1[1][1] = 0.170002964510045;
   fWeightMatrix0to1[2][1] = 0.123799112146455;
   fWeightMatrix0to1[3][1] = -0.799768696951459;
   fWeightMatrix0to1[4][1] = -0.874514632781928;
   fWeightMatrix0to1[5][1] = 1.96179708121243;
   fWeightMatrix0to1[6][1] = -2.071034461395;
   fWeightMatrix0to1[7][1] = 0.797646247645832;
   fWeightMatrix0to1[8][1] = 1.6843100595421;
   fWeightMatrix0to1[9][1] = -0.986019849101761;
   fWeightMatrix0to1[10][1] = -1.56787117517673;
   fWeightMatrix0to1[11][1] = 0.176496719874083;
   fWeightMatrix0to1[12][1] = 0.790919924887637;
   fWeightMatrix0to1[13][1] = 1.61660100314414;
   fWeightMatrix0to1[14][1] = 1.74919575476151;
   fWeightMatrix0to1[15][1] = -8.54314957268413;
   fWeightMatrix0to1[16][1] = -0.451663000565236;
   fWeightMatrix0to1[17][1] = -1.77424755512017;
   fWeightMatrix0to1[0][2] = -1.50266875014809;
   fWeightMatrix0to1[1][2] = 2.25655961679822;
   fWeightMatrix0to1[2][2] = -1.67382044125256;
   fWeightMatrix0to1[3][2] = 1.13941050775932;
   fWeightMatrix0to1[4][2] = 1.03910435492485;
   fWeightMatrix0to1[5][2] = -0.817272957412916;
   fWeightMatrix0to1[6][2] = 0.901493637683812;
   fWeightMatrix0to1[7][2] = -0.924242077865339;
   fWeightMatrix0to1[8][2] = -1.24660199884407;
   fWeightMatrix0to1[9][2] = -1.44457864950395;
   fWeightMatrix0to1[10][2] = 0.615504962244498;
   fWeightMatrix0to1[11][2] = -0.663718004470092;
   fWeightMatrix0to1[12][2] = -0.30489632938874;
   fWeightMatrix0to1[13][2] = 1.25052703333562;
   fWeightMatrix0to1[14][2] = 0.193253916036567;
   fWeightMatrix0to1[15][2] = 0.0220301979357162;
   fWeightMatrix0to1[16][2] = -0.360721474536303;
   fWeightMatrix0to1[17][2] = 0.974336703211963;
   fWeightMatrix0to1[0][3] = -0.39121436014382;
   fWeightMatrix0to1[1][3] = -1.20657378614002;
   fWeightMatrix0to1[2][3] = -2.32831349733406;
   fWeightMatrix0to1[3][3] = -1.06521039179324;
   fWeightMatrix0to1[4][3] = 2.05209059377754;
   fWeightMatrix0to1[5][3] = 0.691003806718901;
   fWeightMatrix0to1[6][3] = -1.22696428633894;
   fWeightMatrix0to1[7][3] = -0.294702358951279;
   fWeightMatrix0to1[8][3] = -0.305467456212523;
   fWeightMatrix0to1[9][3] = 0.880002871785473;
   fWeightMatrix0to1[10][3] = 2.20022377369057;
   fWeightMatrix0to1[11][3] = 0.249987888159701;
   fWeightMatrix0to1[12][3] = -1.46149922131151;
   fWeightMatrix0to1[13][3] = -0.921735144842997;
   fWeightMatrix0to1[14][3] = 0.138398097840177;
   fWeightMatrix0to1[15][3] = -2.72041201608748;
   fWeightMatrix0to1[16][3] = -1.35714005790757;
   fWeightMatrix0to1[17][3] = -1.9000728525842;
   fWeightMatrix0to1[0][4] = 0.727484497741278;
   fWeightMatrix0to1[1][4] = 1.0708168118202;
   fWeightMatrix0to1[2][4] = -0.5888972851399;
   fWeightMatrix0to1[3][4] = -0.45956556272864;
   fWeightMatrix0to1[4][4] = -0.987487243777561;
   fWeightMatrix0to1[5][4] = -1.46705760207353;
   fWeightMatrix0to1[6][4] = 0.0679929679037223;
   fWeightMatrix0to1[7][4] = 0.129705550826117;
   fWeightMatrix0to1[8][4] = 1.56778609084586;
   fWeightMatrix0to1[9][4] = 0.173296706392154;
   fWeightMatrix0to1[10][4] = 1.40742764158952;
   fWeightMatrix0to1[11][4] = -0.343373495694851;
   fWeightMatrix0to1[12][4] = 0.769647245937224;
   fWeightMatrix0to1[13][4] = 0.133725040098752;
   fWeightMatrix0to1[14][4] = 1.05258718170387;
   fWeightMatrix0to1[15][4] = -0.124068977470978;
   fWeightMatrix0to1[16][4] = -0.34688105295068;
   fWeightMatrix0to1[17][4] = -1.42359477590707;
   fWeightMatrix0to1[0][5] = 0.660811313393143;
   fWeightMatrix0to1[1][5] = -0.132619112257849;
   fWeightMatrix0to1[2][5] = 5.6283996011964;
   fWeightMatrix0to1[3][5] = -1.72820828027588;
   fWeightMatrix0to1[4][5] = 0.619872740456766;
   fWeightMatrix0to1[5][5] = 1.38976609653183;
   fWeightMatrix0to1[6][5] = 2.00891266733766;
   fWeightMatrix0to1[7][5] = -5.32505049400649;
   fWeightMatrix0to1[8][5] = -1.08480183281797;
   fWeightMatrix0to1[9][5] = 2.46839883475621;
   fWeightMatrix0to1[10][5] = -1.48435128149176;
   fWeightMatrix0to1[11][5] = -0.995325257603219;
   fWeightMatrix0to1[12][5] = 0.506157878665022;
   fWeightMatrix0to1[13][5] = 1.97055180769176;
   fWeightMatrix0to1[14][5] = -1.18120861042947;
   fWeightMatrix0to1[15][5] = 5.08470124508224;
   fWeightMatrix0to1[16][5] = 1.08615611529328;
   fWeightMatrix0to1[17][5] = -0.70865307132051;
   fWeightMatrix0to1[0][6] = 0.101187828312997;
   fWeightMatrix0to1[1][6] = -0.330704570329524;
   fWeightMatrix0to1[2][6] = -0.985762972956559;
   fWeightMatrix0to1[3][6] = 0.451544483627135;
   fWeightMatrix0to1[4][6] = -1.29189022904843;
   fWeightMatrix0to1[5][6] = 0.887712732910657;
   fWeightMatrix0to1[6][6] = -3.77126865869775;
   fWeightMatrix0to1[7][6] = 1.16233013670542;
   fWeightMatrix0to1[8][6] = 1.81885473129988;
   fWeightMatrix0to1[9][6] = -2.16548949203844;
   fWeightMatrix0to1[10][6] = 0.782486231775346;
   fWeightMatrix0to1[11][6] = -0.257791336258908;
   fWeightMatrix0to1[12][6] = -1.71480662116004;
   fWeightMatrix0to1[13][6] = 0.477207574040384;
   fWeightMatrix0to1[14][6] = 2.01792946505287;
   fWeightMatrix0to1[15][6] = 1.00145519763791;
   fWeightMatrix0to1[16][6] = -0.908935925304047;
   fWeightMatrix0to1[17][6] = -1.27530497399861;
   fWeightMatrix0to1[0][7] = -0.0790736604603052;
   fWeightMatrix0to1[1][7] = 0.804585196811663;
   fWeightMatrix0to1[2][7] = -1.22118487459127;
   fWeightMatrix0to1[3][7] = 1.16189282814284;
   fWeightMatrix0to1[4][7] = -0.658988220402648;
   fWeightMatrix0to1[5][7] = -1.30442153330866;
   fWeightMatrix0to1[6][7] = -0.297885145870324;
   fWeightMatrix0to1[7][7] = 1.076322649941;
   fWeightMatrix0to1[8][7] = -0.552527184412223;
   fWeightMatrix0to1[9][7] = 2.30525491375623;
   fWeightMatrix0to1[10][7] = 1.7678338754311;
   fWeightMatrix0to1[11][7] = -1.85251326030009;
   fWeightMatrix0to1[12][7] = -0.975221689705466;
   fWeightMatrix0to1[13][7] = 1.73746906952207;
   fWeightMatrix0to1[14][7] = 1.95614432745669;
   fWeightMatrix0to1[15][7] = 0.221869880570029;
   fWeightMatrix0to1[16][7] = -1.38992798849204;
   fWeightMatrix0to1[17][7] = -0.28744763011808;
   fWeightMatrix0to1[0][8] = -0.926215732310286;
   fWeightMatrix0to1[1][8] = 1.85661852033476;
   fWeightMatrix0to1[2][8] = 0.840185627319221;
   fWeightMatrix0to1[3][8] = -0.343028449111157;
   fWeightMatrix0to1[4][8] = -3.14113887165428;
   fWeightMatrix0to1[5][8] = 0.219366729460053;
   fWeightMatrix0to1[6][8] = -1.72482349343341;
   fWeightMatrix0to1[7][8] = 0.907447934578111;
   fWeightMatrix0to1[8][8] = 1.16750657609259;
   fWeightMatrix0to1[9][8] = 0.4827165651451;
   fWeightMatrix0to1[10][8] = -0.163224046693259;
   fWeightMatrix0to1[11][8] = 0.658987228214512;
   fWeightMatrix0to1[12][8] = 2.21899342138862;
   fWeightMatrix0to1[13][8] = 0.768916098638301;
   fWeightMatrix0to1[14][8] = 0.0190030013311532;
   fWeightMatrix0to1[15][8] = -1.11283021900998;
   fWeightMatrix0to1[16][8] = 2.05230526656809;
   fWeightMatrix0to1[17][8] = -0.47530006051194;
   fWeightMatrix0to1[0][9] = 0.379465513090004;
   fWeightMatrix0to1[1][9] = 0.951840214507991;
   fWeightMatrix0to1[2][9] = -0.00970941333448327;
   fWeightMatrix0to1[3][9] = -0.797563472323441;
   fWeightMatrix0to1[4][9] = -0.155871699580047;
   fWeightMatrix0to1[5][9] = -0.309746269753894;
   fWeightMatrix0to1[6][9] = -0.548357363023279;
   fWeightMatrix0to1[7][9] = -0.596511227486989;
   fWeightMatrix0to1[8][9] = 1.38885885673049;
   fWeightMatrix0to1[9][9] = -0.577789986861656;
   fWeightMatrix0to1[10][9] = -0.147932904208671;
   fWeightMatrix0to1[11][9] = 1.0269021596784;
   fWeightMatrix0to1[12][9] = 1.59056270732684;
   fWeightMatrix0to1[13][9] = -1.69707134245198;
   fWeightMatrix0to1[14][9] = 1.03596061903725;
   fWeightMatrix0to1[15][9] = 0.418290607073142;
   fWeightMatrix0to1[16][9] = 0.833929668821543;
   fWeightMatrix0to1[17][9] = -0.0595850671628613;
   fWeightMatrix0to1[0][10] = -2.62939457520776;
   fWeightMatrix0to1[1][10] = 1.48195806861719;
   fWeightMatrix0to1[2][10] = 1.12864298771681;
   fWeightMatrix0to1[3][10] = -2.03491305604293;
   fWeightMatrix0to1[4][10] = 0.17070212586238;
   fWeightMatrix0to1[5][10] = -0.172468325081613;
   fWeightMatrix0to1[6][10] = 1.37321556801681;
   fWeightMatrix0to1[7][10] = 2.64359620596691;
   fWeightMatrix0to1[8][10] = -1.06007914282314;
   fWeightMatrix0to1[9][10] = -2.69445525851264;
   fWeightMatrix0to1[10][10] = -0.666052291897942;
   fWeightMatrix0to1[11][10] = 1.11956629888394;
   fWeightMatrix0to1[12][10] = 1.12881516763835;
   fWeightMatrix0to1[13][10] = 1.35162849876295;
   fWeightMatrix0to1[14][10] = 0.323984285482415;
   fWeightMatrix0to1[15][10] = 0.194760744601925;
   fWeightMatrix0to1[16][10] = -3.58588533930369;
   fWeightMatrix0to1[17][10] = 1.70618620653629;
   fWeightMatrix0to1[0][11] = -0.943479799957605;
   fWeightMatrix0to1[1][11] = -1.53131439531055;
   fWeightMatrix0to1[2][11] = -2.63409967806666;
   fWeightMatrix0to1[3][11] = 0.221087500636084;
   fWeightMatrix0to1[4][11] = 0.544575545536707;
   fWeightMatrix0to1[5][11] = -2.35715716811481;
   fWeightMatrix0to1[6][11] = 3.34239584220711;
   fWeightMatrix0to1[7][11] = 1.25345487508562;
   fWeightMatrix0to1[8][11] = -1.52103881901787;
   fWeightMatrix0to1[9][11] = -1.1155745155522;
   fWeightMatrix0to1[10][11] = 1.85188177795435;
   fWeightMatrix0to1[11][11] = 1.34502352802411;
   fWeightMatrix0to1[12][11] = 2.40594637391911;
   fWeightMatrix0to1[13][11] = 0.200855200279255;
   fWeightMatrix0to1[14][11] = -1.80468645236022;
   fWeightMatrix0to1[15][11] = 0.612920337584104;
   fWeightMatrix0to1[16][11] = 2.90582268978909;
   fWeightMatrix0to1[17][11] = 2.30548211864513;
   fWeightMatrix0to1[0][12] = 1.47281093781794;
   fWeightMatrix0to1[1][12] = 0.327263305254248;
   fWeightMatrix0to1[2][12] = 1.30928235356959;
   fWeightMatrix0to1[3][12] = -1.28161229545182;
   fWeightMatrix0to1[4][12] = 1.31877396977849;
   fWeightMatrix0to1[5][12] = -1.03650601457527;
   fWeightMatrix0to1[6][12] = -2.0779121902088;
   fWeightMatrix0to1[7][12] = 0.635567001295566;
   fWeightMatrix0to1[8][12] = 0.788423909383551;
   fWeightMatrix0to1[9][12] = -1.83833873087549;
   fWeightMatrix0to1[10][12] = 1.02197202365967;
   fWeightMatrix0to1[11][12] = 0.362869287639028;
   fWeightMatrix0to1[12][12] = -3.13038300333428;
   fWeightMatrix0to1[13][12] = -0.776807410635355;
   fWeightMatrix0to1[14][12] = 1.48436394475941;
   fWeightMatrix0to1[15][12] = -0.357120703822463;
   fWeightMatrix0to1[16][12] = 0.49349525104479;
   fWeightMatrix0to1[17][12] = 0.54040778216245;
   fWeightMatrix0to1[0][13] = 1.51512355787393;
   fWeightMatrix0to1[1][13] = -1.73608076154613;
   fWeightMatrix0to1[2][13] = 1.97527028282524;
   fWeightMatrix0to1[3][13] = 0.0489742859853575;
   fWeightMatrix0to1[4][13] = -3.17855261087188;
   fWeightMatrix0to1[5][13] = -1.6527556606039;
   fWeightMatrix0to1[6][13] = -2.44581691375216;
   fWeightMatrix0to1[7][13] = 0.545458346835825;
   fWeightMatrix0to1[8][13] = -1.36267063437474;
   fWeightMatrix0to1[9][13] = -2.64547838191872;
   fWeightMatrix0to1[10][13] = -2.33862006321524;
   fWeightMatrix0to1[11][13] = -0.359146492848937;
   fWeightMatrix0to1[12][13] = -1.19509064406634;
   fWeightMatrix0to1[13][13] = -1.97543385410894;
   fWeightMatrix0to1[14][13] = 0.924321051406524;
   fWeightMatrix0to1[15][13] = -3.68162496187426;
   fWeightMatrix0to1[16][13] = 0.213687442514618;
   fWeightMatrix0to1[17][13] = -0.812600759771962;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 1.54523812346368;
   fWeightMatrix1to2[0][1] = 1.69995350515305;
   fWeightMatrix1to2[0][2] = 0.817833069109195;
   fWeightMatrix1to2[0][3] = 0.377686338086652;
   fWeightMatrix1to2[0][4] = -1.08420306185844;
   fWeightMatrix1to2[0][5] = -0.621494759557404;
   fWeightMatrix1to2[0][6] = 0.550757487332624;
   fWeightMatrix1to2[0][7] = -0.854441306358868;
   fWeightMatrix1to2[0][8] = 0.660678896048627;
   fWeightMatrix1to2[0][9] = 0.474630781119191;
   fWeightMatrix1to2[0][10] = 1.25021094475289;
   fWeightMatrix1to2[0][11] = 0.57126158817345;
   fWeightMatrix1to2[0][12] = -0.802039297124022;
   fWeightMatrix1to2[0][13] = -0.597089926082029;
   fWeightMatrix1to2[0][14] = -2.45914376317897;
   fWeightMatrix1to2[0][15] = 1.21819223345402;
   fWeightMatrix1to2[0][16] = 0.242867221891161;
   fWeightMatrix1to2[0][17] = -0.468379830987698;
   fWeightMatrix1to2[0][18] = -0.677959548261347;
}

inline double ReadMLPCJ::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLPCJ::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLPCJ::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadMLPCJ::Clear() 
{
   // nothing to clear
}
   inline double ReadMLPCJ::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLPCJ::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 1.93987222119e-11;
   fMax_1[0][0] = 0.731256723404;
   fMin_1[1][0] = 2.11151655094e-05;
   fMax_1[1][0] = 0.729348361492;
   fMin_1[2][0] = 1.93987222119e-11;
   fMax_1[2][0] = 0.731256723404;
   fMin_1[0][1] = 0.0111495917663;
   fMax_1[0][1] = 21.9877300262;
   fMin_1[1][1] = 0.134300857782;
   fMax_1[1][1] = 24.9779434204;
   fMin_1[2][1] = 0.0111495917663;
   fMax_1[2][1] = 24.9779434204;
   fMin_1[0][2] = 0.00189490010962;
   fMax_1[0][2] = 14.9983968735;
   fMin_1[1][2] = 0.0220367405564;
   fMax_1[1][2] = 14.9911079407;
   fMin_1[2][2] = 0.00189490010962;
   fMax_1[2][2] = 14.9983968735;
   fMin_1[0][3] = 0;
   fMax_1[0][3] = 0.134104982018;
   fMin_1[1][3] = 0;
   fMax_1[1][3] = 0.137716650963;
   fMin_1[2][3] = 0;
   fMax_1[2][3] = 0.137716650963;
   fMin_1[0][4] = 62.147693634;
   fMax_1[0][4] = 37961.9179688;
   fMin_1[1][4] = 41.2933425903;
   fMax_1[1][4] = 21269.5722656;
   fMin_1[2][4] = 41.2933425903;
   fMax_1[2][4] = 37961.9179688;
   fMin_1[0][5] = 2.30495882034;
   fMax_1[0][5] = 102.738922119;
   fMin_1[1][5] = 2.78237915039;
   fMax_1[1][5] = 49.5175361633;
   fMin_1[2][5] = 2.30495882034;
   fMax_1[2][5] = 102.738922119;
   fMin_1[0][6] = 2.63570382231e-06;
   fMax_1[0][6] = 0.738568007946;
   fMin_1[1][6] = 3.91690700781e-05;
   fMax_1[1][6] = 0.923672735691;
   fMin_1[2][6] = 2.63570382231e-06;
   fMax_1[2][6] = 0.923672735691;
   fMin_1[0][7] = 2.4348450367e-08;
   fMax_1[0][7] = 0.699207723141;
   fMin_1[1][7] = 5.91529897065e-05;
   fMax_1[1][7] = 0.744905769825;
   fMin_1[2][7] = 2.4348450367e-08;
   fMax_1[2][7] = 0.744905769825;
   fMin_1[0][8] = 6.10736776707e-07;
   fMax_1[0][8] = 1.01704800129;
   fMin_1[1][8] = 3.12057891279e-05;
   fMax_1[1][8] = 1.05343544483;
   fMin_1[2][8] = 6.10736776707e-07;
   fMax_1[2][8] = 1.05343544483;
   fMin_1[0][9] = 0.00300450995564;
   fMax_1[0][9] = 1;
   fMin_1[1][9] = 0.0038299348671;
   fMax_1[1][9] = 1;
   fMin_1[2][9] = 0.00300450995564;
   fMax_1[2][9] = 1;
   fMin_1[0][10] = 0.0559116005898;
   fMax_1[0][10] = 72.067237854;
   fMin_1[1][10] = 0.144289746881;
   fMax_1[1][10] = 84.5542831421;
   fMin_1[2][10] = 0.0559116005898;
   fMax_1[2][10] = 84.5542831421;
   fMin_1[0][11] = 0.0131226135418;
   fMax_1[0][11] = 75.9046707153;
   fMin_1[1][11] = 0.146247655153;
   fMax_1[1][11] = 67.7235794067;
   fMin_1[2][11] = 0.0131226135418;
   fMax_1[2][11] = 75.9046707153;
   fMin_1[0][12] = 0.0151327997446;
   fMax_1[0][12] = 79.3785171509;
   fMin_1[1][12] = 0.0453270226717;
   fMax_1[1][12] = 68.506652832;
   fMin_1[2][12] = 0.0151327997446;
   fMax_1[2][12] = 79.3785171509;
}

//_______________________________________________________________________
inline void ReadMLPCJ::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 13;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   std::vector<int> indicesGet;
   std::vector<int> indicesPut;

   indicesGet.push_back( 0);
   indicesGet.push_back( 1);
   indicesGet.push_back( 2);
   indicesGet.push_back( 3);
   indicesGet.push_back( 4);
   indicesGet.push_back( 5);
   indicesGet.push_back( 6);
   indicesGet.push_back( 7);
   indicesGet.push_back( 8);
   indicesGet.push_back( 9);
   indicesGet.push_back( 10);
   indicesGet.push_back( 11);
   indicesGet.push_back( 12);
   indicesPut.push_back( 0);
   indicesPut.push_back( 1);
   indicesPut.push_back( 2);
   indicesPut.push_back( 3);
   indicesPut.push_back( 4);
   indicesPut.push_back( 5);
   indicesPut.push_back( 6);
   indicesPut.push_back( 7);
   indicesPut.push_back( 8);
   indicesPut.push_back( 9);
   indicesPut.push_back( 10);
   indicesPut.push_back( 11);
   indicesPut.push_back( 12);

   std::vector<double> dv(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<13;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLPCJ::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLPCJ::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
