// Class: ReadMLPCJ
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLPCJ
TMVA Release   : 4.1.4         [262404]
ROOT Release   : 5.34/07       [336391]
Creator        : pseyfert
Date           : Sat Dec 21 19:42:18 2013
Host           : Linux lxbuild175.cern.ch 2.6.18-308.4.1.el5 #1 SMP Wed Apr 18 16:26:27 CEST 2012 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /auto/sigma0/pseyfert/zoontuple/Bender_v22r7/Phys/Tau23Mu/scripts/TMVA_training_v3
Training events: 41107
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 16
TMath::Exp(-1000*LifeTime)    TMath_Exp__M_1000_T_LifeTime_ TMath::Exp(-1000*LifeTime)    transformed decay time        1                                 'F'    [1.93987222119e-11,0.731256723404]
IPSig                         IPSig                         IPSig                         IP significance               1                                 'F'    [0.0111495917663,24.9779434204]
VertexChi2                    VertexChi2                    VertexChi2                    vertex #chi^{2}               1                                 'F'    [0.00189490010962,14.9983968735]
acos(dira)                    acos_dira_                    acos(dira)                    pointing angle                1                                 'F'    [0,0.137716650963]
pt                            pt                            pt                            p_{T}                         [MeV/c]                           'F'    [41.2933425903,37961.9179688]
min(p0_IPSig,min(p1_IPSig,p2_IPSig)) min_p0_IPSig,min_p1_IPSig,p2_IPSig__ min(p0_IPSig,min(p1_IPSig,p2_IPSig)) min. #mu IP significance             1                                        'F'    [2.30495882034,102.738922119]
DOCAone                       DOCAone                       DOCAone                       DOCA (#mu 1 and 2)            mm                                'F'    [2.63570382231e-06,0.923672735691]
DOCAtwo                       DOCAtwo                       DOCAtwo                       DOCA (#mu 2 and 3)            mm                                'F'    [2.4348450367e-08,0.744905769825]
DOCAthree                     DOCAthree                     DOCAthree                     DOCA (#mu 1 and 3)            mm                                'F'    [6.10736776707e-07,1.05343544483]
isolationd                    isolationd                    isolationd                    isolationd                                                      'F'    [0,7]
isolatione                    isolatione                    isolatione                    isolatione                                                      'F'    [0,8]
isolationf                    isolationf                    isolationf                    isolationf                                                      'F'    [0,8]
CDF3                          CDF3                          CDF3                          cone isolation                1                                 'F'    [0.00300450995564,1]
p0_track_MatchChi2            p0_track_MatchChi2            p0_track_MatchChi2            track match #chi^{2} (#mu 1)  1                                 'F'    [0.0559116005898,84.5542831421]
p1_track_MatchChi2            p1_track_MatchChi2            p1_track_MatchChi2            track match #chi^{2} (#mu 2)  1                                 'F'    [0.0131226135418,75.9046707153]
p2_track_MatchChi2            p2_track_MatchChi2            p2_track_MatchChi2            track match #chi^{2} (#mu 3)  1                                 'F'    [0.0151327997446,79.3785171509]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLPCJ : public IClassifierReader {

 public:

   // constructor
   ReadMLPCJ( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLPCJ" ),
        fNvars( 16 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "TMath::Exp(-1000*LifeTime)", "IPSig", "VertexChi2", "acos(dira)", "pt", "min(p0_IPSig,min(p1_IPSig,p2_IPSig))", "DOCAone", "DOCAtwo", "DOCAthree", "isolationd", "isolatione", "isolationf", "CDF3", "p0_track_MatchChi2", "p1_track_MatchChi2", "p2_track_MatchChi2" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 0.99999988079071;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 0.99999988079071;
      fVmin[6] = -1;
      fVmax[6] = 0.99999988079071;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;
      fVmin[11] = -1;
      fVmax[11] = 1;
      fVmin[12] = -1;
      fVmax[12] = 0.99999988079071;
      fVmin[13] = -1;
      fVmax[13] = 1;
      fVmin[14] = -1;
      fVmax[14] = 1;
      fVmin[15] = -1;
      fVmax[15] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';
      fType[14] = 'F';
      fType[15] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLPCJ() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][16];
   double fMax_1[3][16];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[16];
   double fVmax[16];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[16];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[22][17];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][22];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLPCJ::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 17; fWeights[0] = new double[17]; 
   fLayerSize[1] = 22; fWeights[1] = new double[22]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -1.7680346802765;
   fWeightMatrix0to1[1][0] = 1.44337652753988;
   fWeightMatrix0to1[2][0] = 0.846009384950408;
   fWeightMatrix0to1[3][0] = 2.4315648074354;
   fWeightMatrix0to1[4][0] = -0.874268875311872;
   fWeightMatrix0to1[5][0] = -0.38859402126024;
   fWeightMatrix0to1[6][0] = 0.172944098004512;
   fWeightMatrix0to1[7][0] = 1.83308965601653;
   fWeightMatrix0to1[8][0] = -1.01791078974526;
   fWeightMatrix0to1[9][0] = -0.0191697347128775;
   fWeightMatrix0to1[10][0] = -1.3138153129528;
   fWeightMatrix0to1[11][0] = 0.81953113294065;
   fWeightMatrix0to1[12][0] = -1.17126962122753;
   fWeightMatrix0to1[13][0] = 0.401176210392422;
   fWeightMatrix0to1[14][0] = 2.25602371466834;
   fWeightMatrix0to1[15][0] = 0.725140866929254;
   fWeightMatrix0to1[16][0] = -0.489577689576084;
   fWeightMatrix0to1[17][0] = 1.75784009472879;
   fWeightMatrix0to1[18][0] = -0.517077669238823;
   fWeightMatrix0to1[19][0] = 1.38502132714438;
   fWeightMatrix0to1[20][0] = -0.763188359937737;
   fWeightMatrix0to1[0][1] = -1.64388406220662;
   fWeightMatrix0to1[1][1] = 0.170031901662824;
   fWeightMatrix0to1[2][1] = -0.0433499680107742;
   fWeightMatrix0to1[3][1] = -4.02348575680157;
   fWeightMatrix0to1[4][1] = 0.577806768099236;
   fWeightMatrix0to1[5][1] = 6.2259687271994;
   fWeightMatrix0to1[6][1] = -0.71642101996561;
   fWeightMatrix0to1[7][1] = -1.60374291471925;
   fWeightMatrix0to1[8][1] = -2.49836121478983;
   fWeightMatrix0to1[9][1] = 0.759931194642316;
   fWeightMatrix0to1[10][1] = 1.71539053917351;
   fWeightMatrix0to1[11][1] = -0.184728763079602;
   fWeightMatrix0to1[12][1] = -0.227421036108771;
   fWeightMatrix0to1[13][1] = -0.00308561767879528;
   fWeightMatrix0to1[14][1] = 1.15485345141578;
   fWeightMatrix0to1[15][1] = -1.41955784010908;
   fWeightMatrix0to1[16][1] = 1.73413213016355;
   fWeightMatrix0to1[17][1] = -3.07589170745827;
   fWeightMatrix0to1[18][1] = -1.77459654690531;
   fWeightMatrix0to1[19][1] = 1.20059761519342;
   fWeightMatrix0to1[20][1] = 2.13350709513625;
   fWeightMatrix0to1[0][2] = 0.63041372450044;
   fWeightMatrix0to1[1][2] = 1.82715226027918;
   fWeightMatrix0to1[2][2] = -0.738024866134092;
   fWeightMatrix0to1[3][2] = -1.04978141373804;
   fWeightMatrix0to1[4][2] = 1.39905486586848;
   fWeightMatrix0to1[5][2] = -0.0137094956701573;
   fWeightMatrix0to1[6][2] = 1.72682620210157;
   fWeightMatrix0to1[7][2] = 1.0637108180798;
   fWeightMatrix0to1[8][2] = 0.612576943939453;
   fWeightMatrix0to1[9][2] = 1.01177873298944;
   fWeightMatrix0to1[10][2] = -1.45995326706403;
   fWeightMatrix0to1[11][2] = 1.27918872664274;
   fWeightMatrix0to1[12][2] = -1.76800220024266;
   fWeightMatrix0to1[13][2] = 0.241845079542988;
   fWeightMatrix0to1[14][2] = -0.725010768748221;
   fWeightMatrix0to1[15][2] = -1.78764847703482;
   fWeightMatrix0to1[16][2] = 1.07563295800559;
   fWeightMatrix0to1[17][2] = 1.33407384431539;
   fWeightMatrix0to1[18][2] = -0.889750303108079;
   fWeightMatrix0to1[19][2] = 0.376929752497374;
   fWeightMatrix0to1[20][2] = -0.784299019111089;
   fWeightMatrix0to1[0][3] = -0.0723406611064698;
   fWeightMatrix0to1[1][3] = 3.05042135303068;
   fWeightMatrix0to1[2][3] = -0.47831760570439;
   fWeightMatrix0to1[3][3] = -1.34321697531751;
   fWeightMatrix0to1[4][3] = 0.913079516509093;
   fWeightMatrix0to1[5][3] = 1.37207986764025;
   fWeightMatrix0to1[6][3] = -1.18378761872042;
   fWeightMatrix0to1[7][3] = -0.815030191360057;
   fWeightMatrix0to1[8][3] = 0.653198155391343;
   fWeightMatrix0to1[9][3] = 1.07218230703871;
   fWeightMatrix0to1[10][3] = 1.45319560008237;
   fWeightMatrix0to1[11][3] = 1.46404900039068;
   fWeightMatrix0to1[12][3] = -0.394267119520339;
   fWeightMatrix0to1[13][3] = -2.211230710904;
   fWeightMatrix0to1[14][3] = -0.681634286014107;
   fWeightMatrix0to1[15][3] = 1.04876001225267;
   fWeightMatrix0to1[16][3] = 0.807418634313424;
   fWeightMatrix0to1[17][3] = 0.795708726883267;
   fWeightMatrix0to1[18][3] = 1.12264962999102;
   fWeightMatrix0to1[19][3] = 0.990064799556892;
   fWeightMatrix0to1[20][3] = 0.31177900964729;
   fWeightMatrix0to1[0][4] = -0.554432193401023;
   fWeightMatrix0to1[1][4] = 0.734065310685289;
   fWeightMatrix0to1[2][4] = 0.790322805037216;
   fWeightMatrix0to1[3][4] = -0.580487262344487;
   fWeightMatrix0to1[4][4] = -1.80811852321457;
   fWeightMatrix0to1[5][4] = -0.178853931135097;
   fWeightMatrix0to1[6][4] = -0.176341104741494;
   fWeightMatrix0to1[7][4] = -0.232197449121926;
   fWeightMatrix0to1[8][4] = 1.32481969308313;
   fWeightMatrix0to1[9][4] = -2.1911441804329;
   fWeightMatrix0to1[10][4] = -0.664455770864162;
   fWeightMatrix0to1[11][4] = 1.65178791993119;
   fWeightMatrix0to1[12][4] = -0.953283512727007;
   fWeightMatrix0to1[13][4] = -0.190094214239862;
   fWeightMatrix0to1[14][4] = -0.99205998896878;
   fWeightMatrix0to1[15][4] = 0.139638848268616;
   fWeightMatrix0to1[16][4] = -1.29917571520731;
   fWeightMatrix0to1[17][4] = -0.700204098550813;
   fWeightMatrix0to1[18][4] = 0.918360556021092;
   fWeightMatrix0to1[19][4] = 1.66032890988089;
   fWeightMatrix0to1[20][4] = -2.32137438248532;
   fWeightMatrix0to1[0][5] = 5.02117272835938;
   fWeightMatrix0to1[1][5] = -2.53216931324236;
   fWeightMatrix0to1[2][5] = -1.16508437165277;
   fWeightMatrix0to1[3][5] = 0.42656811003531;
   fWeightMatrix0to1[4][5] = 1.72547335725345;
   fWeightMatrix0to1[5][5] = -4.12138656461365;
   fWeightMatrix0to1[6][5] = -0.355958920079932;
   fWeightMatrix0to1[7][5] = 0.25732119221587;
   fWeightMatrix0to1[8][5] = 0.158732503809755;
   fWeightMatrix0to1[9][5] = -1.52959107639055;
   fWeightMatrix0to1[10][5] = 1.88500261384428;
   fWeightMatrix0to1[11][5] = 0.190280938894412;
   fWeightMatrix0to1[12][5] = -1.07490182075917;
   fWeightMatrix0to1[13][5] = 5.2304993809018;
   fWeightMatrix0to1[14][5] = -3.1095237390695;
   fWeightMatrix0to1[15][5] = -1.54819352877831;
   fWeightMatrix0to1[16][5] = 0.759516656569594;
   fWeightMatrix0to1[17][5] = 0.353553136095931;
   fWeightMatrix0to1[18][5] = 2.75554467518611;
   fWeightMatrix0to1[19][5] = 0.769259292063616;
   fWeightMatrix0to1[20][5] = -0.361675455634454;
   fWeightMatrix0to1[0][6] = -3.25958857109368;
   fWeightMatrix0to1[1][6] = 1.03430942195616;
   fWeightMatrix0to1[2][6] = -2.12275252069335;
   fWeightMatrix0to1[3][6] = 0.218540790835068;
   fWeightMatrix0to1[4][6] = -1.18988137819917;
   fWeightMatrix0to1[5][6] = -1.41886769169272;
   fWeightMatrix0to1[6][6] = 0.309808433628064;
   fWeightMatrix0to1[7][6] = -2.03908003603529;
   fWeightMatrix0to1[8][6] = -1.68339014691404;
   fWeightMatrix0to1[9][6] = 1.2321157860689;
   fWeightMatrix0to1[10][6] = 2.20598482630125;
   fWeightMatrix0to1[11][6] = -2.30757744041742;
   fWeightMatrix0to1[12][6] = 0.244254810906036;
   fWeightMatrix0to1[13][6] = -1.16258434671372;
   fWeightMatrix0to1[14][6] = 0.86631693702186;
   fWeightMatrix0to1[15][6] = 0.182162696885212;
   fWeightMatrix0to1[16][6] = -0.775721665505948;
   fWeightMatrix0to1[17][6] = 0.573833562337093;
   fWeightMatrix0to1[18][6] = -2.4293102081631;
   fWeightMatrix0to1[19][6] = 1.57045860703486;
   fWeightMatrix0to1[20][6] = 1.52085854528632;
   fWeightMatrix0to1[0][7] = -1.59611374968117;
   fWeightMatrix0to1[1][7] = 0.5233671207154;
   fWeightMatrix0to1[2][7] = -0.0577747638211653;
   fWeightMatrix0to1[3][7] = -0.493116401140239;
   fWeightMatrix0to1[4][7] = -0.773490002001533;
   fWeightMatrix0to1[5][7] = -0.761528933083519;
   fWeightMatrix0to1[6][7] = -0.716562935575143;
   fWeightMatrix0to1[7][7] = -0.727126176849014;
   fWeightMatrix0to1[8][7] = -0.539066097164499;
   fWeightMatrix0to1[9][7] = 1.23972214737393;
   fWeightMatrix0to1[10][7] = 0.749359328397414;
   fWeightMatrix0to1[11][7] = 0.840937126695104;
   fWeightMatrix0to1[12][7] = -1.58675708177085;
   fWeightMatrix0to1[13][7] = -0.721238722375794;
   fWeightMatrix0to1[14][7] = 1.83521439168298;
   fWeightMatrix0to1[15][7] = 0.542710155090811;
   fWeightMatrix0to1[16][7] = 1.22081725203226;
   fWeightMatrix0to1[17][7] = 0.830695585103584;
   fWeightMatrix0to1[18][7] = 1.54056984626647;
   fWeightMatrix0to1[19][7] = -0.611747414202958;
   fWeightMatrix0to1[20][7] = 0.137115895365924;
   fWeightMatrix0to1[0][8] = -2.96390843339923;
   fWeightMatrix0to1[1][8] = -0.910290995621011;
   fWeightMatrix0to1[2][8] = 1.20265510304554;
   fWeightMatrix0to1[3][8] = 0.437485388329219;
   fWeightMatrix0to1[4][8] = -3.89242973631962;
   fWeightMatrix0to1[5][8] = 0.937384055403486;
   fWeightMatrix0to1[6][8] = 1.8189854289395;
   fWeightMatrix0to1[7][8] = -2.55665829160633;
   fWeightMatrix0to1[8][8] = 1.80976781857815;
   fWeightMatrix0to1[9][8] = 0.296736102220003;
   fWeightMatrix0to1[10][8] = 0.824319867371032;
   fWeightMatrix0to1[11][8] = -2.12321994176548;
   fWeightMatrix0to1[12][8] = -1.62959063536592;
   fWeightMatrix0to1[13][8] = 0.473480618367516;
   fWeightMatrix0to1[14][8] = 0.427259768478855;
   fWeightMatrix0to1[15][8] = -1.72512919964482;
   fWeightMatrix0to1[16][8] = 0.526745821970578;
   fWeightMatrix0to1[17][8] = -0.117764989154064;
   fWeightMatrix0to1[18][8] = 1.35538043675908;
   fWeightMatrix0to1[19][8] = 1.76880608219183;
   fWeightMatrix0to1[20][8] = -0.819290559329823;
   fWeightMatrix0to1[0][9] = -0.282576958818318;
   fWeightMatrix0to1[1][9] = 0.391912176116441;
   fWeightMatrix0to1[2][9] = 0.755919151013168;
   fWeightMatrix0to1[3][9] = 1.19356301257327;
   fWeightMatrix0to1[4][9] = 0.888785513649059;
   fWeightMatrix0to1[5][9] = 1.7603913920185;
   fWeightMatrix0to1[6][9] = -1.16393856421726;
   fWeightMatrix0to1[7][9] = -2.03364308019491;
   fWeightMatrix0to1[8][9] = 1.71548484474833;
   fWeightMatrix0to1[9][9] = 0.34048877594906;
   fWeightMatrix0to1[10][9] = -1.18298993261433;
   fWeightMatrix0to1[11][9] = -0.343907129108047;
   fWeightMatrix0to1[12][9] = 0.237682395561209;
   fWeightMatrix0to1[13][9] = -0.480460045987637;
   fWeightMatrix0to1[14][9] = -2.26763804360839;
   fWeightMatrix0to1[15][9] = 1.59937814005095;
   fWeightMatrix0to1[16][9] = 1.42219569770169;
   fWeightMatrix0to1[17][9] = -1.35063289577316;
   fWeightMatrix0to1[18][9] = -0.916209364201851;
   fWeightMatrix0to1[19][9] = 1.62768198323065;
   fWeightMatrix0to1[20][9] = 1.15978789194769;
   fWeightMatrix0to1[0][10] = 0.682468658964049;
   fWeightMatrix0to1[1][10] = -0.833063338172481;
   fWeightMatrix0to1[2][10] = -2.08315292089556;
   fWeightMatrix0to1[3][10] = 1.40666660576689;
   fWeightMatrix0to1[4][10] = 2.42120950118689;
   fWeightMatrix0to1[5][10] = 2.92177897093049;
   fWeightMatrix0to1[6][10] = 1.12835452553793;
   fWeightMatrix0to1[7][10] = 0.148191596375688;
   fWeightMatrix0to1[8][10] = 1.53959874082284;
   fWeightMatrix0to1[9][10] = -1.30308793438092;
   fWeightMatrix0to1[10][10] = -1.10755963587016;
   fWeightMatrix0to1[11][10] = 0.0553155282897459;
   fWeightMatrix0to1[12][10] = -1.46039121194026;
   fWeightMatrix0to1[13][10] = 0.058580327881821;
   fWeightMatrix0to1[14][10] = 1.42336851384536;
   fWeightMatrix0to1[15][10] = -1.17926569335188;
   fWeightMatrix0to1[16][10] = 1.39307988869063;
   fWeightMatrix0to1[17][10] = -0.714880912162658;
   fWeightMatrix0to1[18][10] = -2.76086904441585;
   fWeightMatrix0to1[19][10] = -1.08607656768992;
   fWeightMatrix0to1[20][10] = 0.80891537880583;
   fWeightMatrix0to1[0][11] = 0.977641780846523;
   fWeightMatrix0to1[1][11] = 1.55470973055383;
   fWeightMatrix0to1[2][11] = -1.31792333561062;
   fWeightMatrix0to1[3][11] = 2.31516192004522;
   fWeightMatrix0to1[4][11] = 0.28861339065658;
   fWeightMatrix0to1[5][11] = 2.9241742326434;
   fWeightMatrix0to1[6][11] = 0.282403126000871;
   fWeightMatrix0to1[7][11] = -1.42508309513511;
   fWeightMatrix0to1[8][11] = 0.510714755203039;
   fWeightMatrix0to1[9][11] = -1.87832442676855;
   fWeightMatrix0to1[10][11] = -0.229236671605848;
   fWeightMatrix0to1[11][11] = -1.63686675068004;
   fWeightMatrix0to1[12][11] = -1.5592996910222;
   fWeightMatrix0to1[13][11] = -0.194532455848678;
   fWeightMatrix0to1[14][11] = 0.993164922568639;
   fWeightMatrix0to1[15][11] = -0.959995573260938;
   fWeightMatrix0to1[16][11] = -0.910214235333239;
   fWeightMatrix0to1[17][11] = -0.437434883694345;
   fWeightMatrix0to1[18][11] = -2.08793399795652;
   fWeightMatrix0to1[19][11] = 0.148558789015815;
   fWeightMatrix0to1[20][11] = -0.13107545732789;
   fWeightMatrix0to1[0][12] = 0.0850410319156514;
   fWeightMatrix0to1[1][12] = 0.250041337098252;
   fWeightMatrix0to1[2][12] = 1.10703984842175;
   fWeightMatrix0to1[3][12] = 0.518556000324576;
   fWeightMatrix0to1[4][12] = 0.393525618749678;
   fWeightMatrix0to1[5][12] = -0.237554174122699;
   fWeightMatrix0to1[6][12] = -0.297341200746473;
   fWeightMatrix0to1[7][12] = -1.46891477412802;
   fWeightMatrix0to1[8][12] = 1.08205915387234;
   fWeightMatrix0to1[9][12] = 0.913870587709166;
   fWeightMatrix0to1[10][12] = 1.37261547149542;
   fWeightMatrix0to1[11][12] = -0.704003836274047;
   fWeightMatrix0to1[12][12] = 0.177292116353012;
   fWeightMatrix0to1[13][12] = 0.795471981545755;
   fWeightMatrix0to1[14][12] = -0.897736191477889;
   fWeightMatrix0to1[15][12] = 1.2727278422623;
   fWeightMatrix0to1[16][12] = 1.03838314894485;
   fWeightMatrix0to1[17][12] = -1.54242605591866;
   fWeightMatrix0to1[18][12] = -1.09444754806092;
   fWeightMatrix0to1[19][12] = 0.873740794961075;
   fWeightMatrix0to1[20][12] = 0.915455283196922;
   fWeightMatrix0to1[0][13] = 0.753235895973216;
   fWeightMatrix0to1[1][13] = -1.29698516210582;
   fWeightMatrix0to1[2][13] = -0.625124209322999;
   fWeightMatrix0to1[3][13] = -0.94273796044553;
   fWeightMatrix0to1[4][13] = -0.131914556578846;
   fWeightMatrix0to1[5][13] = 0.0247353523693982;
   fWeightMatrix0to1[6][13] = -0.51252369957986;
   fWeightMatrix0to1[7][13] = 0.0992297127007036;
   fWeightMatrix0to1[8][13] = -0.625656270959329;
   fWeightMatrix0to1[9][13] = -0.468612779024645;
   fWeightMatrix0to1[10][13] = -0.343541641627431;
   fWeightMatrix0to1[11][13] = -1.63689583046594;
   fWeightMatrix0to1[12][13] = -1.47412114448661;
   fWeightMatrix0to1[13][13] = -4.80329078733813;
   fWeightMatrix0to1[14][13] = 3.90770454941042;
   fWeightMatrix0to1[15][13] = -1.84532387756229;
   fWeightMatrix0to1[16][13] = 1.84331902186153;
   fWeightMatrix0to1[17][13] = -3.05248192016861;
   fWeightMatrix0to1[18][13] = -1.08333712376669;
   fWeightMatrix0to1[19][13] = -1.104448818499;
   fWeightMatrix0to1[20][13] = -0.150419040819959;
   fWeightMatrix0to1[0][14] = -0.673320201177466;
   fWeightMatrix0to1[1][14] = -0.90079016891381;
   fWeightMatrix0to1[2][14] = 0.00768901707330631;
   fWeightMatrix0to1[3][14] = 0.713548404328117;
   fWeightMatrix0to1[4][14] = -1.0718483188489;
   fWeightMatrix0to1[5][14] = -0.293497800287214;
   fWeightMatrix0to1[6][14] = -2.63909591590717;
   fWeightMatrix0to1[7][14] = -0.848173392724714;
   fWeightMatrix0to1[8][14] = 3.62218739349969;
   fWeightMatrix0to1[9][14] = -0.0863543572151872;
   fWeightMatrix0to1[10][14] = 0.426742979790854;
   fWeightMatrix0to1[11][14] = -0.581120998898565;
   fWeightMatrix0to1[12][14] = -1.26615216923326;
   fWeightMatrix0to1[13][14] = -0.659956026976659;
   fWeightMatrix0to1[14][14] = -0.14705037364598;
   fWeightMatrix0to1[15][14] = -1.34482754775846;
   fWeightMatrix0to1[16][14] = 1.51114501826686;
   fWeightMatrix0to1[17][14] = -1.09853326943082;
   fWeightMatrix0to1[18][14] = -0.909822351620276;
   fWeightMatrix0to1[19][14] = 1.75068834019796;
   fWeightMatrix0to1[20][14] = -0.92137162393163;
   fWeightMatrix0to1[0][15] = 1.65875754692923;
   fWeightMatrix0to1[1][15] = 1.0528813851919;
   fWeightMatrix0to1[2][15] = -1.85493528863656;
   fWeightMatrix0to1[3][15] = 1.40632333965009;
   fWeightMatrix0to1[4][15] = 2.6940947753575;
   fWeightMatrix0to1[5][15] = -0.402354139455985;
   fWeightMatrix0to1[6][15] = -0.675897391013188;
   fWeightMatrix0to1[7][15] = -0.11533654988045;
   fWeightMatrix0to1[8][15] = -2.71878189612537;
   fWeightMatrix0to1[9][15] = 0.280141444069235;
   fWeightMatrix0to1[10][15] = 2.36741897918713;
   fWeightMatrix0to1[11][15] = 0.874876487107228;
   fWeightMatrix0to1[12][15] = 1.4608040271565;
   fWeightMatrix0to1[13][15] = -0.776416983659751;
   fWeightMatrix0to1[14][15] = 2.68440539750823;
   fWeightMatrix0to1[15][15] = -1.90615650955524;
   fWeightMatrix0to1[16][15] = 1.34342842496316;
   fWeightMatrix0to1[17][15] = -0.551782704932483;
   fWeightMatrix0to1[18][15] = 0.790166124737158;
   fWeightMatrix0to1[19][15] = -0.0623060214269883;
   fWeightMatrix0to1[20][15] = 0.48900022689638;
   fWeightMatrix0to1[0][16] = 0.105083475153126;
   fWeightMatrix0to1[1][16] = 0.364928947453877;
   fWeightMatrix0to1[2][16] = 0.650057017756974;
   fWeightMatrix0to1[3][16] = -0.925792908427479;
   fWeightMatrix0to1[4][16] = -0.85857412077408;
   fWeightMatrix0to1[5][16] = 7.77239429512534;
   fWeightMatrix0to1[6][16] = 2.29321667561074;
   fWeightMatrix0to1[7][16] = -1.46168778565072;
   fWeightMatrix0to1[8][16] = 0.391222589047234;
   fWeightMatrix0to1[9][16] = -1.22716560439586;
   fWeightMatrix0to1[10][16] = -0.687064715601715;
   fWeightMatrix0to1[11][16] = 0.217381881086526;
   fWeightMatrix0to1[12][16] = 0.326479259959603;
   fWeightMatrix0to1[13][16] = -2.7080794523269;
   fWeightMatrix0to1[14][16] = 2.34473610292138;
   fWeightMatrix0to1[15][16] = 1.6153187627055;
   fWeightMatrix0to1[16][16] = -0.119050231771644;
   fWeightMatrix0to1[17][16] = -0.147272235660962;
   fWeightMatrix0to1[18][16] = -2.97277051737776;
   fWeightMatrix0to1[19][16] = -1.46229621367321;
   fWeightMatrix0to1[20][16] = -1.70183040107397;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 0.836124433343571;
   fWeightMatrix1to2[0][1] = -0.549733605582885;
   fWeightMatrix1to2[0][2] = 0.0139763199800978;
   fWeightMatrix1to2[0][3] = 0.69145911918577;
   fWeightMatrix1to2[0][4] = -0.78955884561571;
   fWeightMatrix1to2[0][5] = -1.57996310285737;
   fWeightMatrix1to2[0][6] = -2.18241166216581;
   fWeightMatrix1to2[0][7] = 1.81763558421298;
   fWeightMatrix1to2[0][8] = -1.31198203548856;
   fWeightMatrix1to2[0][9] = -0.213234532780991;
   fWeightMatrix1to2[0][10] = -0.779288486673212;
   fWeightMatrix1to2[0][11] = -0.76626922437761;
   fWeightMatrix1to2[0][12] = -1.03076332908695;
   fWeightMatrix1to2[0][13] = 0.640247519868214;
   fWeightMatrix1to2[0][14] = -0.606421626115588;
   fWeightMatrix1to2[0][15] = -0.7253573041197;
   fWeightMatrix1to2[0][16] = 0.550485378110255;
   fWeightMatrix1to2[0][17] = 1.32623632630985;
   fWeightMatrix1to2[0][18] = 0.628618804402971;
   fWeightMatrix1to2[0][19] = -0.446670489752221;
   fWeightMatrix1to2[0][20] = 1.13409286070464;
   fWeightMatrix1to2[0][21] = 2.23288759649471;
}

inline double ReadMLPCJ::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLPCJ::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLPCJ::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadMLPCJ::Clear() 
{
   // nothing to clear
}
   inline double ReadMLPCJ::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLPCJ::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 1.93987222119e-11;
   fMax_1[0][0] = 0.731256723404;
   fMin_1[1][0] = 2.11151655094e-05;
   fMax_1[1][0] = 0.729348361492;
   fMin_1[2][0] = 1.93987222119e-11;
   fMax_1[2][0] = 0.731256723404;
   fMin_1[0][1] = 0.0111495917663;
   fMax_1[0][1] = 21.9877300262;
   fMin_1[1][1] = 0.134300857782;
   fMax_1[1][1] = 24.9779434204;
   fMin_1[2][1] = 0.0111495917663;
   fMax_1[2][1] = 24.9779434204;
   fMin_1[0][2] = 0.00189490010962;
   fMax_1[0][2] = 14.9983968735;
   fMin_1[1][2] = 0.0220367405564;
   fMax_1[1][2] = 14.9911079407;
   fMin_1[2][2] = 0.00189490010962;
   fMax_1[2][2] = 14.9983968735;
   fMin_1[0][3] = 0;
   fMax_1[0][3] = 0.134104982018;
   fMin_1[1][3] = 0;
   fMax_1[1][3] = 0.137716650963;
   fMin_1[2][3] = 0;
   fMax_1[2][3] = 0.137716650963;
   fMin_1[0][4] = 62.147693634;
   fMax_1[0][4] = 37961.9179688;
   fMin_1[1][4] = 41.2933425903;
   fMax_1[1][4] = 21269.5722656;
   fMin_1[2][4] = 41.2933425903;
   fMax_1[2][4] = 37961.9179688;
   fMin_1[0][5] = 2.30495882034;
   fMax_1[0][5] = 102.738922119;
   fMin_1[1][5] = 2.78237915039;
   fMax_1[1][5] = 49.5175361633;
   fMin_1[2][5] = 2.30495882034;
   fMax_1[2][5] = 102.738922119;
   fMin_1[0][6] = 2.63570382231e-06;
   fMax_1[0][6] = 0.738568007946;
   fMin_1[1][6] = 3.91690700781e-05;
   fMax_1[1][6] = 0.923672735691;
   fMin_1[2][6] = 2.63570382231e-06;
   fMax_1[2][6] = 0.923672735691;
   fMin_1[0][7] = 2.4348450367e-08;
   fMax_1[0][7] = 0.699207723141;
   fMin_1[1][7] = 5.91529897065e-05;
   fMax_1[1][7] = 0.744905769825;
   fMin_1[2][7] = 2.4348450367e-08;
   fMax_1[2][7] = 0.744905769825;
   fMin_1[0][8] = 6.10736776707e-07;
   fMax_1[0][8] = 1.01704800129;
   fMin_1[1][8] = 3.12057891279e-05;
   fMax_1[1][8] = 1.05343544483;
   fMin_1[2][8] = 6.10736776707e-07;
   fMax_1[2][8] = 1.05343544483;
   fMin_1[0][9] = 0;
   fMax_1[0][9] = 6;
   fMin_1[1][9] = 0;
   fMax_1[1][9] = 7;
   fMin_1[2][9] = 0;
   fMax_1[2][9] = 7;
   fMin_1[0][10] = 0;
   fMax_1[0][10] = 6;
   fMin_1[1][10] = 0;
   fMax_1[1][10] = 8;
   fMin_1[2][10] = 0;
   fMax_1[2][10] = 8;
   fMin_1[0][11] = 0;
   fMax_1[0][11] = 7;
   fMin_1[1][11] = 0;
   fMax_1[1][11] = 8;
   fMin_1[2][11] = 0;
   fMax_1[2][11] = 8;
   fMin_1[0][12] = 0.00300450995564;
   fMax_1[0][12] = 1;
   fMin_1[1][12] = 0.0038299348671;
   fMax_1[1][12] = 1;
   fMin_1[2][12] = 0.00300450995564;
   fMax_1[2][12] = 1;
   fMin_1[0][13] = 0.0559116005898;
   fMax_1[0][13] = 72.067237854;
   fMin_1[1][13] = 0.144289746881;
   fMax_1[1][13] = 84.5542831421;
   fMin_1[2][13] = 0.0559116005898;
   fMax_1[2][13] = 84.5542831421;
   fMin_1[0][14] = 0.0131226135418;
   fMax_1[0][14] = 75.9046707153;
   fMin_1[1][14] = 0.146247655153;
   fMax_1[1][14] = 67.7235794067;
   fMin_1[2][14] = 0.0131226135418;
   fMax_1[2][14] = 75.9046707153;
   fMin_1[0][15] = 0.0151327997446;
   fMax_1[0][15] = 79.3785171509;
   fMin_1[1][15] = 0.0453270226717;
   fMax_1[1][15] = 68.506652832;
   fMin_1[2][15] = 0.0151327997446;
   fMax_1[2][15] = 79.3785171509;
}

//_______________________________________________________________________
inline void ReadMLPCJ::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 16;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   std::vector<int> indicesGet;
   std::vector<int> indicesPut;

   indicesGet.push_back( 0);
   indicesGet.push_back( 1);
   indicesGet.push_back( 2);
   indicesGet.push_back( 3);
   indicesGet.push_back( 4);
   indicesGet.push_back( 5);
   indicesGet.push_back( 6);
   indicesGet.push_back( 7);
   indicesGet.push_back( 8);
   indicesGet.push_back( 9);
   indicesGet.push_back( 10);
   indicesGet.push_back( 11);
   indicesGet.push_back( 12);
   indicesGet.push_back( 13);
   indicesGet.push_back( 14);
   indicesGet.push_back( 15);
   indicesPut.push_back( 0);
   indicesPut.push_back( 1);
   indicesPut.push_back( 2);
   indicesPut.push_back( 3);
   indicesPut.push_back( 4);
   indicesPut.push_back( 5);
   indicesPut.push_back( 6);
   indicesPut.push_back( 7);
   indicesPut.push_back( 8);
   indicesPut.push_back( 9);
   indicesPut.push_back( 10);
   indicesPut.push_back( 11);
   indicesPut.push_back( 12);
   indicesPut.push_back( 13);
   indicesPut.push_back( 14);
   indicesPut.push_back( 15);

   std::vector<double> dv(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<16;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLPCJ::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLPCJ::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
