// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.1.4         [262404]
ROOT Release   : 5.34/07       [336391]
Creator        : pseyfert
Date           : Wed Jan  1 12:55:32 2014
Host           : Linux lxbuild175.cern.ch 2.6.18-308.4.1.el5 #1 SMP Wed Apr 18 16:26:27 CEST 2012 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /auto/sigma0/pseyfert/zoontuple/Bender_v22r7/Phys/Tau23Mu/scripts/TMVA_training_v3
Training events: 38856
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 14
TMath::Exp(-1000*LifeTime)    TMath_Exp__M_1000_T_LifeTime_ TMath::Exp(-1000*LifeTime)    transformed decay time        1                                 'F'    [1.93987222119e-11,0.731256723404]
IPSig                         IPSig                         IPSig                         IP significance               1                                 'F'    [0.0111495917663,21.7485733032]
VertexChi2                    VertexChi2                    VertexChi2                    vertex #chi^{2}               1                                 'F'    [0.00189490010962,14.9983968735]
acos(dira)                    acos_dira_                    acos(dira)                    pointing angle                1                                 'F'    [0,0.137716650963]
pt                            pt                            pt                            p_{T}                         [MeV/c]                           'F'    [41.2933425903,37961.9179688]
Laura_SumBDT                  Laura_SumBDT                  Laura_SumBDT                  Laura_SumBDT                                                    'F'    [-2.57286167145,5]
min(p0_IPSig,min(p1_IPSig,p2_IPSig)) min_p0_IPSig,min_p1_IPSig,p2_IPSig__ min(p0_IPSig,min(p1_IPSig,p2_IPSig)) min. #mu IP significance             1                                        'F'    [2.30495882034,102.738922119]
DOCAone                       DOCAone                       DOCAone                       DOCA (#mu 1 and 2)            mm                                'F'    [2.63570382231e-06,0.738568007946]
DOCAtwo                       DOCAtwo                       DOCAtwo                       DOCA (#mu 2 and 3)            mm                                'F'    [2.4348450367e-08,0.622791826725]
DOCAthree                     DOCAthree                     DOCAthree                     DOCA (#mu 1 and 3)            mm                                'F'    [6.10736776707e-07,1.01704800129]
CDF3                          CDF3                          CDF3                          cone isolation                1                                 'F'    [0.00300450995564,1]
p0_track_MatchChi2            p0_track_MatchChi2            p0_track_MatchChi2            track match #chi^{2} (#mu 1)  1                                 'F'    [0.0559116005898,76.3943099976]
p1_track_MatchChi2            p1_track_MatchChi2            p1_track_MatchChi2            track match #chi^{2} (#mu 2)  1                                 'F'    [0.0131226135418,75.9046707153]
p2_track_MatchChi2            p2_track_MatchChi2            p2_track_MatchChi2            track match #chi^{2} (#mu 3)  1                                 'F'    [0.0151327997446,79.3785171509]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 14 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "TMath::Exp(-1000*LifeTime)", "IPSig", "VertexChi2", "acos(dira)", "pt", "Laura_SumBDT", "min(p0_IPSig,min(p1_IPSig,p2_IPSig))", "DOCAone", "DOCAtwo", "DOCAthree", "CDF3", "p0_track_MatchChi2", "p1_track_MatchChi2", "p2_track_MatchChi2" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 0.99999988079071;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 0.99999988079071;
      fVmin[11] = -1;
      fVmax[11] = 1;
      fVmin[12] = -1;
      fVmax[12] = 1;
      fVmin[13] = -1;
      fVmax[13] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][14];
   double fMax_1[3][14];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[14];
   double fVmax[14];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[14];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[20][15];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][20];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 15; fWeights[0] = new double[15]; 
   fLayerSize[1] = 20; fWeights[1] = new double[20]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.0461526027654878;
   fWeightMatrix0to1[1][0] = 1.25956503389649;
   fWeightMatrix0to1[2][0] = 0.831663145984077;
   fWeightMatrix0to1[3][0] = 1.16546519677943;
   fWeightMatrix0to1[4][0] = -1.49980048975984;
   fWeightMatrix0to1[5][0] = -0.575766552023389;
   fWeightMatrix0to1[6][0] = -0.634021198652555;
   fWeightMatrix0to1[7][0] = 2.02969968388209;
   fWeightMatrix0to1[8][0] = -0.305351031956194;
   fWeightMatrix0to1[9][0] = -0.566434313686951;
   fWeightMatrix0to1[10][0] = -1.11114001765608;
   fWeightMatrix0to1[11][0] = -0.00927940563216407;
   fWeightMatrix0to1[12][0] = -1.07357432281478;
   fWeightMatrix0to1[13][0] = -0.291864775090253;
   fWeightMatrix0to1[14][0] = -0.470330748310188;
   fWeightMatrix0to1[15][0] = 1.03465538876201;
   fWeightMatrix0to1[16][0] = -0.390375202436939;
   fWeightMatrix0to1[17][0] = 1.07146560709867;
   fWeightMatrix0to1[18][0] = -0.0518720579227343;
   fWeightMatrix0to1[0][1] = 0.963824986172443;
   fWeightMatrix0to1[1][1] = 1.24944975141118;
   fWeightMatrix0to1[2][1] = -0.0714988393166973;
   fWeightMatrix0to1[3][1] = 0.907061309999994;
   fWeightMatrix0to1[4][1] = 0.240695299129069;
   fWeightMatrix0to1[5][1] = -1.94160610855194;
   fWeightMatrix0to1[6][1] = -0.035761645516803;
   fWeightMatrix0to1[7][1] = 1.43842595746297;
   fWeightMatrix0to1[8][1] = 0.0210280189102227;
   fWeightMatrix0to1[9][1] = -0.7397778017131;
   fWeightMatrix0to1[10][1] = 0.390468770311046;
   fWeightMatrix0to1[11][1] = -0.344214290114519;
   fWeightMatrix0to1[12][1] = 1.38765624886677;
   fWeightMatrix0to1[13][1] = -0.387988344445728;
   fWeightMatrix0to1[14][1] = -0.307508467135772;
   fWeightMatrix0to1[15][1] = 0.561083944421663;
   fWeightMatrix0to1[16][1] = -0.193673695927974;
   fWeightMatrix0to1[17][1] = -1.21875612066324;
   fWeightMatrix0to1[18][1] = 1.97327726344507;
   fWeightMatrix0to1[0][2] = -0.802127505748566;
   fWeightMatrix0to1[1][2] = 0.491007946938176;
   fWeightMatrix0to1[2][2] = 0.846817727048163;
   fWeightMatrix0to1[3][2] = 1.05790961093607;
   fWeightMatrix0to1[4][2] = 2.06067583592609;
   fWeightMatrix0to1[5][2] = 0.645656810891872;
   fWeightMatrix0to1[6][2] = -0.626618296616368;
   fWeightMatrix0to1[7][2] = -1.42585268818965;
   fWeightMatrix0to1[8][2] = 0.522129199323145;
   fWeightMatrix0to1[9][2] = -0.364949649816394;
   fWeightMatrix0to1[10][2] = 1.30738938581413;
   fWeightMatrix0to1[11][2] = 1.32947473801241;
   fWeightMatrix0to1[12][2] = 1.39063438790396;
   fWeightMatrix0to1[13][2] = 0.808668114650942;
   fWeightMatrix0to1[14][2] = -1.47243784347675;
   fWeightMatrix0to1[15][2] = 0.846234994872111;
   fWeightMatrix0to1[16][2] = -1.50048600309525;
   fWeightMatrix0to1[17][2] = -1.00017576851878;
   fWeightMatrix0to1[18][2] = -0.161941164649413;
   fWeightMatrix0to1[0][3] = -2.50003776690581;
   fWeightMatrix0to1[1][3] = 1.60839506822085;
   fWeightMatrix0to1[2][3] = 0.694382491833401;
   fWeightMatrix0to1[3][3] = -1.10339675498995;
   fWeightMatrix0to1[4][3] = 0.804864491290083;
   fWeightMatrix0to1[5][3] = -1.15617301517541;
   fWeightMatrix0to1[6][3] = 1.03538152952237;
   fWeightMatrix0to1[7][3] = 1.71089815187788;
   fWeightMatrix0to1[8][3] = 0.304373534873444;
   fWeightMatrix0to1[9][3] = -0.770731417679944;
   fWeightMatrix0to1[10][3] = -1.26732264715682;
   fWeightMatrix0to1[11][3] = 0.584526354104066;
   fWeightMatrix0to1[12][3] = -1.09150295297707;
   fWeightMatrix0to1[13][3] = -1.34359940185345;
   fWeightMatrix0to1[14][3] = -1.50105208013587;
   fWeightMatrix0to1[15][3] = 0.912919099198774;
   fWeightMatrix0to1[16][3] = 1.39867832521821;
   fWeightMatrix0to1[17][3] = 0.657994805966142;
   fWeightMatrix0to1[18][3] = -0.397592796013665;
   fWeightMatrix0to1[0][4] = -2.18231790307859;
   fWeightMatrix0to1[1][4] = -1.36928813371335;
   fWeightMatrix0to1[2][4] = 1.22267315930112;
   fWeightMatrix0to1[3][4] = 0.996804799820289;
   fWeightMatrix0to1[4][4] = 1.94628361131211;
   fWeightMatrix0to1[5][4] = 0.735246992003443;
   fWeightMatrix0to1[6][4] = 1.50906647964607;
   fWeightMatrix0to1[7][4] = -0.391798023696059;
   fWeightMatrix0to1[8][4] = -0.239810181110782;
   fWeightMatrix0to1[9][4] = -0.504206617645928;
   fWeightMatrix0to1[10][4] = 0.850677484761043;
   fWeightMatrix0to1[11][4] = -0.844771465936952;
   fWeightMatrix0to1[12][4] = -1.65218926277431;
   fWeightMatrix0to1[13][4] = -1.99002793390076;
   fWeightMatrix0to1[14][4] = -0.507494472614844;
   fWeightMatrix0to1[15][4] = 0.233171993148588;
   fWeightMatrix0to1[16][4] = 1.86401954023013;
   fWeightMatrix0to1[17][4] = -2.08703836722932;
   fWeightMatrix0to1[18][4] = -0.854541359157677;
   fWeightMatrix0to1[0][5] = 1.31469039974996;
   fWeightMatrix0to1[1][5] = 0.983375425861085;
   fWeightMatrix0to1[2][5] = -1.24553484096091;
   fWeightMatrix0to1[3][5] = -1.11611285211743;
   fWeightMatrix0to1[4][5] = 0.450609899159192;
   fWeightMatrix0to1[5][5] = -2.2652260403207;
   fWeightMatrix0to1[6][5] = -1.41206555032919;
   fWeightMatrix0to1[7][5] = 0.837853428180898;
   fWeightMatrix0to1[8][5] = 2.43248526793254;
   fWeightMatrix0to1[9][5] = -2.16271179709602;
   fWeightMatrix0to1[10][5] = 1.3287358040569;
   fWeightMatrix0to1[11][5] = -1.25406901578892;
   fWeightMatrix0to1[12][5] = -0.911983239070245;
   fWeightMatrix0to1[13][5] = -0.470263737348801;
   fWeightMatrix0to1[14][5] = 0.177289957526785;
   fWeightMatrix0to1[15][5] = -1.52314876405523;
   fWeightMatrix0to1[16][5] = 0.532679705516657;
   fWeightMatrix0to1[17][5] = -0.0465981615980274;
   fWeightMatrix0to1[18][5] = 0.482152277673015;
   fWeightMatrix0to1[0][6] = -1.52091088300462;
   fWeightMatrix0to1[1][6] = -0.601734926445331;
   fWeightMatrix0to1[2][6] = 0.773386704566989;
   fWeightMatrix0to1[3][6] = -0.378759487594573;
   fWeightMatrix0to1[4][6] = 0.760818986455655;
   fWeightMatrix0to1[5][6] = -0.755965106521692;
   fWeightMatrix0to1[6][6] = -1.08373546736741;
   fWeightMatrix0to1[7][6] = 0.439815709225558;
   fWeightMatrix0to1[8][6] = -0.304972190159666;
   fWeightMatrix0to1[9][6] = 2.94832252884932;
   fWeightMatrix0to1[10][6] = 0.278841529748198;
   fWeightMatrix0to1[11][6] = 0.214973422770305;
   fWeightMatrix0to1[12][6] = -0.540151489149593;
   fWeightMatrix0to1[13][6] = -0.48106528106756;
   fWeightMatrix0to1[14][6] = -2.14137340728354;
   fWeightMatrix0to1[15][6] = 1.37747857439852;
   fWeightMatrix0to1[16][6] = 0.529354954317489;
   fWeightMatrix0to1[17][6] = -1.86788130020591;
   fWeightMatrix0to1[18][6] = 0.145640497807723;
   fWeightMatrix0to1[0][7] = -1.97980842238554;
   fWeightMatrix0to1[1][7] = 0.45687046096818;
   fWeightMatrix0to1[2][7] = 2.08906271389217;
   fWeightMatrix0to1[3][7] = 2.31827434418185;
   fWeightMatrix0to1[4][7] = -1.31641436382439;
   fWeightMatrix0to1[5][7] = 0.0217414337887184;
   fWeightMatrix0to1[6][7] = 1.96446753362782;
   fWeightMatrix0to1[7][7] = 1.88286674903258;
   fWeightMatrix0to1[8][7] = 0.0382968117409405;
   fWeightMatrix0to1[9][7] = -0.818855362256331;
   fWeightMatrix0to1[10][7] = -0.744861318561234;
   fWeightMatrix0to1[11][7] = -1.34390387087799;
   fWeightMatrix0to1[12][7] = 1.36168648059878;
   fWeightMatrix0to1[13][7] = 0.576126517608828;
   fWeightMatrix0to1[14][7] = -0.702039511601519;
   fWeightMatrix0to1[15][7] = -0.164779381997406;
   fWeightMatrix0to1[16][7] = 0.516606348921513;
   fWeightMatrix0to1[17][7] = -1.72241072663398;
   fWeightMatrix0to1[18][7] = 0.147118535992086;
   fWeightMatrix0to1[0][8] = 1.20954062531299;
   fWeightMatrix0to1[1][8] = 0.526518368662899;
   fWeightMatrix0to1[2][8] = 0.114032175150382;
   fWeightMatrix0to1[3][8] = 0.503280153782228;
   fWeightMatrix0to1[4][8] = 0.914812690316821;
   fWeightMatrix0to1[5][8] = 0.269688783606611;
   fWeightMatrix0to1[6][8] = 1.29480674619608;
   fWeightMatrix0to1[7][8] = -1.1993759193167;
   fWeightMatrix0to1[8][8] = 0.245699711960873;
   fWeightMatrix0to1[9][8] = 0.219332808249376;
   fWeightMatrix0to1[10][8] = 0.0689350532912499;
   fWeightMatrix0to1[11][8] = 0.520076388144467;
   fWeightMatrix0to1[12][8] = 0.771022261598272;
   fWeightMatrix0to1[13][8] = -1.22556062145469;
   fWeightMatrix0to1[14][8] = -0.854374635286742;
   fWeightMatrix0to1[15][8] = 1.24539537477063;
   fWeightMatrix0to1[16][8] = -0.462385494564928;
   fWeightMatrix0to1[17][8] = -1.26920514073662;
   fWeightMatrix0to1[18][8] = 0.518370284302761;
   fWeightMatrix0to1[0][9] = 0.376124065894001;
   fWeightMatrix0to1[1][9] = -0.593505000278411;
   fWeightMatrix0to1[2][9] = 2.22717161469261;
   fWeightMatrix0to1[3][9] = 2.11895619735526;
   fWeightMatrix0to1[4][9] = -1.72505415835076;
   fWeightMatrix0to1[5][9] = 0.237228364799641;
   fWeightMatrix0to1[6][9] = 0.486298853987571;
   fWeightMatrix0to1[7][9] = 0.693717551963131;
   fWeightMatrix0to1[8][9] = -1.60307385127371;
   fWeightMatrix0to1[9][9] = -1.02219612235503;
   fWeightMatrix0to1[10][9] = 0.670468600379042;
   fWeightMatrix0to1[11][9] = 1.74803206955583;
   fWeightMatrix0to1[12][9] = -1.96336625066828;
   fWeightMatrix0to1[13][9] = -0.858790891764526;
   fWeightMatrix0to1[14][9] = -0.757812512866664;
   fWeightMatrix0to1[15][9] = 0.447020577068045;
   fWeightMatrix0to1[16][9] = 2.13588577248762;
   fWeightMatrix0to1[17][9] = -0.791618658082216;
   fWeightMatrix0to1[18][9] = -0.699660117421543;
   fWeightMatrix0to1[0][10] = -1.038232382377;
   fWeightMatrix0to1[1][10] = -0.20924705893467;
   fWeightMatrix0to1[2][10] = 1.20171763030189;
   fWeightMatrix0to1[3][10] = 1.07905137939382;
   fWeightMatrix0to1[4][10] = 0.522213172496313;
   fWeightMatrix0to1[5][10] = 0.211029371074422;
   fWeightMatrix0to1[6][10] = -1.59180963864744;
   fWeightMatrix0to1[7][10] = 1.18486562917916;
   fWeightMatrix0to1[8][10] = 0.0771139010491516;
   fWeightMatrix0to1[9][10] = 0.078633301200636;
   fWeightMatrix0to1[10][10] = -0.229983986292232;
   fWeightMatrix0to1[11][10] = 0.796838409939661;
   fWeightMatrix0to1[12][10] = 0.267948255849575;
   fWeightMatrix0to1[13][10] = -1.45926821363156;
   fWeightMatrix0to1[14][10] = 1.43392956979436;
   fWeightMatrix0to1[15][10] = 0.658429858022701;
   fWeightMatrix0to1[16][10] = -0.562678322132701;
   fWeightMatrix0to1[17][10] = -0.16212889922289;
   fWeightMatrix0to1[18][10] = 0.247884560990889;
   fWeightMatrix0to1[0][11] = 0.524595669000351;
   fWeightMatrix0to1[1][11] = 1.32677315262298;
   fWeightMatrix0to1[2][11] = 0.229879474356652;
   fWeightMatrix0to1[3][11] = -1.2105131458395;
   fWeightMatrix0to1[4][11] = -0.480073447028398;
   fWeightMatrix0to1[5][11] = 1.31470603203736;
   fWeightMatrix0to1[6][11] = 1.68455331941357;
   fWeightMatrix0to1[7][11] = 1.39898208530736;
   fWeightMatrix0to1[8][11] = 0.600474965857885;
   fWeightMatrix0to1[9][11] = 0.489563090651449;
   fWeightMatrix0to1[10][11] = -2.15145764292191;
   fWeightMatrix0to1[11][11] = -1.28395184866456;
   fWeightMatrix0to1[12][11] = -0.296152029888628;
   fWeightMatrix0to1[13][11] = -1.40496874019499;
   fWeightMatrix0to1[14][11] = 0.722628019754117;
   fWeightMatrix0to1[15][11] = 2.02198204629823;
   fWeightMatrix0to1[16][11] = -0.80088077812857;
   fWeightMatrix0to1[17][11] = 0.12625081886298;
   fWeightMatrix0to1[18][11] = -0.0585969735392132;
   fWeightMatrix0to1[0][12] = -1.55819206948405;
   fWeightMatrix0to1[1][12] = -0.0329748083996266;
   fWeightMatrix0to1[2][12] = 0.0189825062104352;
   fWeightMatrix0to1[3][12] = 1.2361413491179;
   fWeightMatrix0to1[4][12] = 1.22269727937804;
   fWeightMatrix0to1[5][12] = -0.18740882716344;
   fWeightMatrix0to1[6][12] = 1.88566740830995;
   fWeightMatrix0to1[7][12] = -1.33919097561587;
   fWeightMatrix0to1[8][12] = 0.639342248359413;
   fWeightMatrix0to1[9][12] = -0.525872604101247;
   fWeightMatrix0to1[10][12] = -1.67465681753066;
   fWeightMatrix0to1[11][12] = -1.42720044227125;
   fWeightMatrix0to1[12][12] = -2.15766163109787;
   fWeightMatrix0to1[13][12] = -0.956663754639619;
   fWeightMatrix0to1[14][12] = -1.84601273647129;
   fWeightMatrix0to1[15][12] = -1.18767783994048;
   fWeightMatrix0to1[16][12] = -1.46217385804359;
   fWeightMatrix0to1[17][12] = -0.559484127594489;
   fWeightMatrix0to1[18][12] = -1.29852173298367;
   fWeightMatrix0to1[0][13] = -2.23119121459149;
   fWeightMatrix0to1[1][13] = 1.01399270319861;
   fWeightMatrix0to1[2][13] = -0.106074904141142;
   fWeightMatrix0to1[3][13] = 0.438084836769911;
   fWeightMatrix0to1[4][13] = -0.738044622070151;
   fWeightMatrix0to1[5][13] = -0.00288898385578361;
   fWeightMatrix0to1[6][13] = 1.89836227852873;
   fWeightMatrix0to1[7][13] = 1.62082282292312;
   fWeightMatrix0to1[8][13] = -0.312741414303138;
   fWeightMatrix0to1[9][13] = 0.0286142646044397;
   fWeightMatrix0to1[10][13] = -1.49579875604829;
   fWeightMatrix0to1[11][13] = -1.25473506223173;
   fWeightMatrix0to1[12][13] = -1.7044319197524;
   fWeightMatrix0to1[13][13] = -0.264935481748173;
   fWeightMatrix0to1[14][13] = -0.00862987091723854;
   fWeightMatrix0to1[15][13] = 1.83722105256277;
   fWeightMatrix0to1[16][13] = 0.0890779986566015;
   fWeightMatrix0to1[17][13] = -0.341884745685584;
   fWeightMatrix0to1[18][13] = -0.682458735727855;
   fWeightMatrix0to1[0][14] = -1.40301476243386;
   fWeightMatrix0to1[1][14] = 1.42163376909697;
   fWeightMatrix0to1[2][14] = 0.598760132383979;
   fWeightMatrix0to1[3][14] = -1.40164035328525;
   fWeightMatrix0to1[4][14] = -1.47753073667684;
   fWeightMatrix0to1[5][14] = 0.994053462474299;
   fWeightMatrix0to1[6][14] = 0.676257891981609;
   fWeightMatrix0to1[7][14] = 0.119079442262873;
   fWeightMatrix0to1[8][14] = -0.570598179242836;
   fWeightMatrix0to1[9][14] = 0.136812279847922;
   fWeightMatrix0to1[10][14] = 1.98177436767855;
   fWeightMatrix0to1[11][14] = 0.907225455265485;
   fWeightMatrix0to1[12][14] = 1.19891754010391;
   fWeightMatrix0to1[13][14] = 0.388972971169146;
   fWeightMatrix0to1[14][14] = 0.560472417007386;
   fWeightMatrix0to1[15][14] = -0.627900261250373;
   fWeightMatrix0to1[16][14] = -1.92440850574822;
   fWeightMatrix0to1[17][14] = 0.186791968177628;
   fWeightMatrix0to1[18][14] = -1.27392585166679;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -0.785428197519127;
   fWeightMatrix1to2[0][1] = -0.318482917833725;
   fWeightMatrix1to2[0][2] = 0.985894128156408;
   fWeightMatrix1to2[0][3] = -0.95265172107803;
   fWeightMatrix1to2[0][4] = -0.0266131971824592;
   fWeightMatrix1to2[0][5] = -0.196791110354937;
   fWeightMatrix1to2[0][6] = 0.437137152107087;
   fWeightMatrix1to2[0][7] = -0.135890072957337;
   fWeightMatrix1to2[0][8] = -0.146289504808281;
   fWeightMatrix1to2[0][9] = 0.271100280184042;
   fWeightMatrix1to2[0][10] = -1.32212440732553;
   fWeightMatrix1to2[0][11] = 0.732615403169168;
   fWeightMatrix1to2[0][12] = 0.589198138531155;
   fWeightMatrix1to2[0][13] = -1.40351585771412;
   fWeightMatrix1to2[0][14] = -1.17436148960304;
   fWeightMatrix1to2[0][15] = -1.7290825450039;
   fWeightMatrix1to2[0][16] = -0.447135968081519;
   fWeightMatrix1to2[0][17] = 1.54141244858962;
   fWeightMatrix1to2[0][18] = -0.0512518049646756;
   fWeightMatrix1to2[0][19] = 0.418830766784375;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLP::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // nothing to clear
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 1.93987222119e-11;
   fMax_1[0][0] = 0.731256723404;
   fMin_1[1][0] = 2.11151655094e-05;
   fMax_1[1][0] = 0.726359844208;
   fMin_1[2][0] = 1.93987222119e-11;
   fMax_1[2][0] = 0.731256723404;
   fMin_1[0][1] = 0.0111495917663;
   fMax_1[0][1] = 21.7485733032;
   fMin_1[1][1] = 0.134300857782;
   fMax_1[1][1] = 20.9987621307;
   fMin_1[2][1] = 0.0111495917663;
   fMax_1[2][1] = 21.7485733032;
   fMin_1[0][2] = 0.00189490010962;
   fMax_1[0][2] = 14.9983968735;
   fMin_1[1][2] = 0.0220367405564;
   fMax_1[1][2] = 14.9877176285;
   fMin_1[2][2] = 0.00189490010962;
   fMax_1[2][2] = 14.9983968735;
   fMin_1[0][3] = 0;
   fMax_1[0][3] = 0.134104982018;
   fMin_1[1][3] = 0;
   fMax_1[1][3] = 0.137716650963;
   fMin_1[2][3] = 0;
   fMax_1[2][3] = 0.137716650963;
   fMin_1[0][4] = 62.147693634;
   fMax_1[0][4] = 37961.9179688;
   fMin_1[1][4] = 41.2933425903;
   fMax_1[1][4] = 21269.5722656;
   fMin_1[2][4] = 41.2933425903;
   fMax_1[2][4] = 37961.9179688;
   fMin_1[0][5] = -2.57286167145;
   fMax_1[0][5] = 5;
   fMin_1[1][5] = -2.21387171745;
   fMax_1[1][5] = -0.0525252744555;
   fMin_1[2][5] = -2.57286167145;
   fMax_1[2][5] = 5;
   fMin_1[0][6] = 2.30495882034;
   fMax_1[0][6] = 102.738922119;
   fMin_1[1][6] = 2.78237915039;
   fMax_1[1][6] = 49.5175361633;
   fMin_1[2][6] = 2.30495882034;
   fMax_1[2][6] = 102.738922119;
   fMin_1[0][7] = 2.63570382231e-06;
   fMax_1[0][7] = 0.738568007946;
   fMin_1[1][7] = 3.91690700781e-05;
   fMax_1[1][7] = 0.731490552425;
   fMin_1[2][7] = 2.63570382231e-06;
   fMax_1[2][7] = 0.738568007946;
   fMin_1[0][8] = 2.4348450367e-08;
   fMax_1[0][8] = 0.622791826725;
   fMin_1[1][8] = 7.34744171496e-05;
   fMax_1[1][8] = 0.365254282951;
   fMin_1[2][8] = 2.4348450367e-08;
   fMax_1[2][8] = 0.622791826725;
   fMin_1[0][9] = 6.10736776707e-07;
   fMax_1[0][9] = 1.01704800129;
   fMin_1[1][9] = 3.12057891279e-05;
   fMax_1[1][9] = 0.672129392624;
   fMin_1[2][9] = 6.10736776707e-07;
   fMax_1[2][9] = 1.01704800129;
   fMin_1[0][10] = 0.00300450995564;
   fMax_1[0][10] = 1;
   fMin_1[1][10] = 0.0038299348671;
   fMax_1[1][10] = 1;
   fMin_1[2][10] = 0.00300450995564;
   fMax_1[2][10] = 1;
   fMin_1[0][11] = 0.0559116005898;
   fMax_1[0][11] = 72.067237854;
   fMin_1[1][11] = 0.151803418994;
   fMax_1[1][11] = 76.3943099976;
   fMin_1[2][11] = 0.0559116005898;
   fMax_1[2][11] = 76.3943099976;
   fMin_1[0][12] = 0.0131226135418;
   fMax_1[0][12] = 75.9046707153;
   fMin_1[1][12] = 0.146247655153;
   fMax_1[1][12] = 67.7235794067;
   fMin_1[2][12] = 0.0131226135418;
   fMax_1[2][12] = 75.9046707153;
   fMin_1[0][13] = 0.0151327997446;
   fMax_1[0][13] = 79.3785171509;
   fMin_1[1][13] = 0.0453270226717;
   fMax_1[1][13] = 68.506652832;
   fMin_1[2][13] = 0.0151327997446;
   fMax_1[2][13] = 79.3785171509;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 14;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   std::vector<int> indicesGet;
   std::vector<int> indicesPut;

   indicesGet.push_back( 0);
   indicesGet.push_back( 1);
   indicesGet.push_back( 2);
   indicesGet.push_back( 3);
   indicesGet.push_back( 4);
   indicesGet.push_back( 5);
   indicesGet.push_back( 6);
   indicesGet.push_back( 7);
   indicesGet.push_back( 8);
   indicesGet.push_back( 9);
   indicesGet.push_back( 10);
   indicesGet.push_back( 11);
   indicesGet.push_back( 12);
   indicesGet.push_back( 13);
   indicesPut.push_back( 0);
   indicesPut.push_back( 1);
   indicesPut.push_back( 2);
   indicesPut.push_back( 3);
   indicesPut.push_back( 4);
   indicesPut.push_back( 5);
   indicesPut.push_back( 6);
   indicesPut.push_back( 7);
   indicesPut.push_back( 8);
   indicesPut.push_back( 9);
   indicesPut.push_back( 10);
   indicesPut.push_back( 11);
   indicesPut.push_back( 12);
   indicesPut.push_back( 13);

   std::vector<double> dv(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<14;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
