// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.1.4         [262404]
ROOT Release   : 5.34/07       [336391]
Creator        : pseyfert
Date           : Wed Jan  1 12:55:02 2014
Host           : Linux lxbuild175.cern.ch 2.6.18-308.4.1.el5 #1 SMP Wed Apr 18 16:26:27 CEST 2012 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /auto/sigma0/pseyfert/zoontuple/Bender_v22r7/Phys/Tau23Mu/scripts/TMVA_training_v3
Training events: 38856
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 14
TMath::Exp(-1000*LifeTime)    TMath_Exp__M_1000_T_LifeTime_ TMath::Exp(-1000*LifeTime)    transformed decay time        1                                 'F'    [1.93987222119e-11,0.731256723404]
IPSig                         IPSig                         IPSig                         IP significance               1                                 'F'    [0.0111495917663,21.7485733032]
VertexChi2                    VertexChi2                    VertexChi2                    vertex #chi^{2}               1                                 'F'    [0.00189490010962,14.9983968735]
acos(dira)                    acos_dira_                    acos(dira)                    pointing angle                1                                 'F'    [0,0.137716650963]
pt                            pt                            pt                            p_{T}                         [MeV/c]                           'F'    [41.2933425903,37961.9179688]
min(p0_IPSig,min(p1_IPSig,p2_IPSig)) min_p0_IPSig,min_p1_IPSig,p2_IPSig__ min(p0_IPSig,min(p1_IPSig,p2_IPSig)) min. #mu IP significance             1                                        'F'    [2.30495882034,102.738922119]
DOCAone                       DOCAone                       DOCAone                       DOCA (#mu 1 and 2)            mm                                'F'    [2.63570382231e-06,0.738568007946]
DOCAtwo                       DOCAtwo                       DOCAtwo                       DOCA (#mu 2 and 3)            mm                                'F'    [2.4348450367e-08,0.622791826725]
DOCAthree                     DOCAthree                     DOCAthree                     DOCA (#mu 1 and 3)            mm                                'F'    [6.10736776707e-07,1.01704800129]
iso                           iso                           iso                           track isolation               1                                 'F'    [0,17]
CDF3                          CDF3                          CDF3                          cone isolation                1                                 'F'    [0.00300450995564,1]
p0_track_MatchChi2            p0_track_MatchChi2            p0_track_MatchChi2            track match #chi^{2} (#mu 1)  1                                 'F'    [0.0559116005898,76.3943099976]
p1_track_MatchChi2            p1_track_MatchChi2            p1_track_MatchChi2            track match #chi^{2} (#mu 2)  1                                 'F'    [0.0131226135418,75.9046707153]
p2_track_MatchChi2            p2_track_MatchChi2            p2_track_MatchChi2            track match #chi^{2} (#mu 3)  1                                 'F'    [0.0151327997446,79.3785171509]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 14 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "TMath::Exp(-1000*LifeTime)", "IPSig", "VertexChi2", "acos(dira)", "pt", "min(p0_IPSig,min(p1_IPSig,p2_IPSig))", "DOCAone", "DOCAtwo", "DOCAthree", "iso", "CDF3", "p0_track_MatchChi2", "p1_track_MatchChi2", "p2_track_MatchChi2" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 0.99999988079071;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 0.99999988079071;
      fVmin[11] = -1;
      fVmax[11] = 1;
      fVmin[12] = -1;
      fVmax[12] = 1;
      fVmin[13] = -1;
      fVmax[13] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][14];
   double fMax_1[3][14];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[14];
   double fVmax[14];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[14];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[20][15];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][20];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 15; fWeights[0] = new double[15]; 
   fLayerSize[1] = 20; fWeights[1] = new double[20]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.337828451297246;
   fWeightMatrix0to1[1][0] = 1.30607046891319;
   fWeightMatrix0to1[2][0] = 0.534322994672457;
   fWeightMatrix0to1[3][0] = 1.34476836967879;
   fWeightMatrix0to1[4][0] = -1.67983428571812;
   fWeightMatrix0to1[5][0] = -1.30018747516384;
   fWeightMatrix0to1[6][0] = -0.567198953329232;
   fWeightMatrix0to1[7][0] = 1.89500026125741;
   fWeightMatrix0to1[8][0] = -0.867739140063818;
   fWeightMatrix0to1[9][0] = -1.31889506496143;
   fWeightMatrix0to1[10][0] = -0.823897524143985;
   fWeightMatrix0to1[11][0] = -0.355758162748988;
   fWeightMatrix0to1[12][0] = -0.602261469737859;
   fWeightMatrix0to1[13][0] = -0.355993769834514;
   fWeightMatrix0to1[14][0] = -0.180082510427296;
   fWeightMatrix0to1[15][0] = 1.27463505145471;
   fWeightMatrix0to1[16][0] = -0.574192699357133;
   fWeightMatrix0to1[17][0] = 1.21669811774443;
   fWeightMatrix0to1[18][0] = 0.330638974331156;
   fWeightMatrix0to1[0][1] = 0.844746357561684;
   fWeightMatrix0to1[1][1] = -1.53208146636773;
   fWeightMatrix0to1[2][1] = -0.237478870291737;
   fWeightMatrix0to1[3][1] = 0.996272239137797;
   fWeightMatrix0to1[4][1] = -0.341951608585359;
   fWeightMatrix0to1[5][1] = -1.46302217531355;
   fWeightMatrix0to1[6][1] = -0.163709716776556;
   fWeightMatrix0to1[7][1] = 1.58646880669598;
   fWeightMatrix0to1[8][1] = -0.651654153730455;
   fWeightMatrix0to1[9][1] = -1.26053427943151;
   fWeightMatrix0to1[10][1] = 0.278831890791991;
   fWeightMatrix0to1[11][1] = 0.610476657454485;
   fWeightMatrix0to1[12][1] = 1.51717643155362;
   fWeightMatrix0to1[13][1] = -0.389833210286256;
   fWeightMatrix0to1[14][1] = -0.338304275382651;
   fWeightMatrix0to1[15][1] = 0.140621679065809;
   fWeightMatrix0to1[16][1] = -0.527303155075471;
   fWeightMatrix0to1[17][1] = -1.52704174228269;
   fWeightMatrix0to1[18][1] = 1.4887199419837;
   fWeightMatrix0to1[0][2] = -0.921194706350478;
   fWeightMatrix0to1[1][2] = 0.809042499813616;
   fWeightMatrix0to1[2][2] = 0.914061779613201;
   fWeightMatrix0to1[3][2] = 0.922822441299809;
   fWeightMatrix0to1[4][2] = 1.11943847414387;
   fWeightMatrix0to1[5][2] = 1.00856359232989;
   fWeightMatrix0to1[6][2] = -0.627687660430002;
   fWeightMatrix0to1[7][2] = -1.35520914042598;
   fWeightMatrix0to1[8][2] = -0.41543476690125;
   fWeightMatrix0to1[9][2] = -0.237421893682672;
   fWeightMatrix0to1[10][2] = 1.04441646154715;
   fWeightMatrix0to1[11][2] = 1.38441645324237;
   fWeightMatrix0to1[12][2] = 1.71651516754527;
   fWeightMatrix0to1[13][2] = 0.850851642633609;
   fWeightMatrix0to1[14][2] = -1.35873965413112;
   fWeightMatrix0to1[15][2] = 1.08602123384722;
   fWeightMatrix0to1[16][2] = -1.72304237267155;
   fWeightMatrix0to1[17][2] = -0.74306573263304;
   fWeightMatrix0to1[18][2] = -0.460154984442616;
   fWeightMatrix0to1[0][3] = -2.34485828164232;
   fWeightMatrix0to1[1][3] = 0.87723968944405;
   fWeightMatrix0to1[2][3] = 1.0541189744298;
   fWeightMatrix0to1[3][3] = -0.843012570825257;
   fWeightMatrix0to1[4][3] = 0.485329784227589;
   fWeightMatrix0to1[5][3] = -0.66392205951406;
   fWeightMatrix0to1[6][3] = 0.70332503062654;
   fWeightMatrix0to1[7][3] = 2.07834763805748;
   fWeightMatrix0to1[8][3] = -1.14812426872236;
   fWeightMatrix0to1[9][3] = 0.0281611180196643;
   fWeightMatrix0to1[10][3] = -0.634830232691358;
   fWeightMatrix0to1[11][3] = 0.711033657555393;
   fWeightMatrix0to1[12][3] = -0.615602438197208;
   fWeightMatrix0to1[13][3] = -1.31964642699018;
   fWeightMatrix0to1[14][3] = -1.41943364978581;
   fWeightMatrix0to1[15][3] = 1.13838615745114;
   fWeightMatrix0to1[16][3] = 0.899533888420037;
   fWeightMatrix0to1[17][3] = 0.826093458392281;
   fWeightMatrix0to1[18][3] = -0.69501866181496;
   fWeightMatrix0to1[0][4] = -2.52874648710238;
   fWeightMatrix0to1[1][4] = -1.11534735470899;
   fWeightMatrix0to1[2][4] = 1.68836698641342;
   fWeightMatrix0to1[3][4] = 1.11904556451992;
   fWeightMatrix0to1[4][4] = 2.28652604684441;
   fWeightMatrix0to1[5][4] = 0.318191130352356;
   fWeightMatrix0to1[6][4] = 1.16413841888611;
   fWeightMatrix0to1[7][4] = -0.743511145115171;
   fWeightMatrix0to1[8][4] = 0.306256309662802;
   fWeightMatrix0to1[9][4] = -0.349481628237107;
   fWeightMatrix0to1[10][4] = 1.13391196885244;
   fWeightMatrix0to1[11][4] = -1.04596915364115;
   fWeightMatrix0to1[12][4] = -1.62534739834927;
   fWeightMatrix0to1[13][4] = -1.90332685581435;
   fWeightMatrix0to1[14][4] = -0.546378630311328;
   fWeightMatrix0to1[15][4] = 0.301583914727222;
   fWeightMatrix0to1[16][4] = 1.5728817719591;
   fWeightMatrix0to1[17][4] = -2.04709510593679;
   fWeightMatrix0to1[18][4] = -1.09322859283128;
   fWeightMatrix0to1[0][5] = 1.04871095080639;
   fWeightMatrix0to1[1][5] = -0.28011459576397;
   fWeightMatrix0to1[2][5] = -0.740067858355346;
   fWeightMatrix0to1[3][5] = -0.605970844795569;
   fWeightMatrix0to1[4][5] = 0.684648208766495;
   fWeightMatrix0to1[5][5] = -2.2036736185857;
   fWeightMatrix0to1[6][5] = -1.52624575790824;
   fWeightMatrix0to1[7][5] = 0.803449460084937;
   fWeightMatrix0to1[8][5] = 2.5844426125261;
   fWeightMatrix0to1[9][5] = -1.48011236536411;
   fWeightMatrix0to1[10][5] = 1.04499547495935;
   fWeightMatrix0to1[11][5] = -0.939233168778461;
   fWeightMatrix0to1[12][5] = -0.916052910582564;
   fWeightMatrix0to1[13][5] = -0.587294402360568;
   fWeightMatrix0to1[14][5] = -0.0238798429197363;
   fWeightMatrix0to1[15][5] = -1.29651580198225;
   fWeightMatrix0to1[16][5] = 0.175287429922022;
   fWeightMatrix0to1[17][5] = -0.221922132223205;
   fWeightMatrix0to1[18][5] = 0.0319382622140624;
   fWeightMatrix0to1[0][6] = -1.46367134486497;
   fWeightMatrix0to1[1][6] = 1.84450475531263;
   fWeightMatrix0to1[2][6] = 0.974924367505558;
   fWeightMatrix0to1[3][6] = -0.0158765016308405;
   fWeightMatrix0to1[4][6] = 0.938134391302695;
   fWeightMatrix0to1[5][6] = -1.51563618609166;
   fWeightMatrix0to1[6][6] = -1.42788069628801;
   fWeightMatrix0to1[7][6] = 0.260076926768043;
   fWeightMatrix0to1[8][6] = -0.900462194828712;
   fWeightMatrix0to1[9][6] = 1.42982649530977;
   fWeightMatrix0to1[10][6] = 1.07241420704514;
   fWeightMatrix0to1[11][6] = -0.0519381013383654;
   fWeightMatrix0to1[12][6] = -0.362943097262236;
   fWeightMatrix0to1[13][6] = -0.418445074677489;
   fWeightMatrix0to1[14][6] = -2.3646776863859;
   fWeightMatrix0to1[15][6] = 1.2729841895613;
   fWeightMatrix0to1[16][6] = -0.0472359999372291;
   fWeightMatrix0to1[17][6] = -2.11490470599088;
   fWeightMatrix0to1[18][6] = 0.425667012736011;
   fWeightMatrix0to1[0][7] = -1.47688515607838;
   fWeightMatrix0to1[1][7] = 0.439205845599768;
   fWeightMatrix0to1[2][7] = 1.77042615330116;
   fWeightMatrix0to1[3][7] = 2.04145911133161;
   fWeightMatrix0to1[4][7] = -1.31075136080562;
   fWeightMatrix0to1[5][7] = -0.128671015596996;
   fWeightMatrix0to1[6][7] = 1.61618428522003;
   fWeightMatrix0to1[7][7] = 1.72287824283267;
   fWeightMatrix0to1[8][7] = -0.36599527655271;
   fWeightMatrix0to1[9][7] = -1.89858976127421;
   fWeightMatrix0to1[10][7] = -0.770060420212842;
   fWeightMatrix0to1[11][7] = -1.48113799857035;
   fWeightMatrix0to1[12][7] = 1.39697416627278;
   fWeightMatrix0to1[13][7] = 0.657918974494055;
   fWeightMatrix0to1[14][7] = -0.722950645227684;
   fWeightMatrix0to1[15][7] = 0.0576362886875323;
   fWeightMatrix0to1[16][7] = 0.0579594020808426;
   fWeightMatrix0to1[17][7] = -1.64045175015908;
   fWeightMatrix0to1[18][7] = 0.199923315032839;
   fWeightMatrix0to1[0][8] = 1.05481601956084;
   fWeightMatrix0to1[1][8] = -0.286643479669101;
   fWeightMatrix0to1[2][8] = 0.104643690802173;
   fWeightMatrix0to1[3][8] = 0.884225609548091;
   fWeightMatrix0to1[4][8] = 1.32467707837738;
   fWeightMatrix0to1[5][8] = 0.100969762282284;
   fWeightMatrix0to1[6][8] = 1.04441694189124;
   fWeightMatrix0to1[7][8] = -1.36329159528131;
   fWeightMatrix0to1[8][8] = 0.193406605148874;
   fWeightMatrix0to1[9][8] = 0.405087555085711;
   fWeightMatrix0to1[10][8] = 0.211620535088422;
   fWeightMatrix0to1[11][8] = 0.569072031410537;
   fWeightMatrix0to1[12][8] = 0.936667819605601;
   fWeightMatrix0to1[13][8] = -1.1654539767008;
   fWeightMatrix0to1[14][8] = -1.00513618337544;
   fWeightMatrix0to1[15][8] = 1.33363483889101;
   fWeightMatrix0to1[16][8] = -1.03971231019746;
   fWeightMatrix0to1[17][8] = -0.482348107882681;
   fWeightMatrix0to1[18][8] = 1.20303371479182;
   fWeightMatrix0to1[0][9] = 0.604083391080903;
   fWeightMatrix0to1[1][9] = -0.624954236063901;
   fWeightMatrix0to1[2][9] = 2.23433060541483;
   fWeightMatrix0to1[3][9] = 2.27661843956981;
   fWeightMatrix0to1[4][9] = -2.10269411497106;
   fWeightMatrix0to1[5][9] = 0.034859535371422;
   fWeightMatrix0to1[6][9] = 0.252773639890353;
   fWeightMatrix0to1[7][9] = 0.696011805466482;
   fWeightMatrix0to1[8][9] = -0.321535215802293;
   fWeightMatrix0to1[9][9] = -0.98810141853416;
   fWeightMatrix0to1[10][9] = 2.13913312569376;
   fWeightMatrix0to1[11][9] = 1.79365428489714;
   fWeightMatrix0to1[12][9] = -1.81343812182783;
   fWeightMatrix0to1[13][9] = -0.814240761277152;
   fWeightMatrix0to1[14][9] = -0.797386138998163;
   fWeightMatrix0to1[15][9] = 0.803601952705518;
   fWeightMatrix0to1[16][9] = 1.18892536935821;
   fWeightMatrix0to1[17][9] = -0.83670512210596;
   fWeightMatrix0to1[18][9] = -0.374845292790529;
   fWeightMatrix0to1[0][10] = -1.16304431078237;
   fWeightMatrix0to1[1][10] = 0.168876218903493;
   fWeightMatrix0to1[2][10] = 1.20660715163429;
   fWeightMatrix0to1[3][10] = 1.15268628833545;
   fWeightMatrix0to1[4][10] = 0.134246384209458;
   fWeightMatrix0to1[5][10] = -0.369908695162757;
   fWeightMatrix0to1[6][10] = -1.84379834802753;
   fWeightMatrix0to1[7][10] = 1.01959942440357;
   fWeightMatrix0to1[8][10] = 0.0351930033049189;
   fWeightMatrix0to1[9][10] = -1.85413837273349;
   fWeightMatrix0to1[10][10] = 0.230057778793707;
   fWeightMatrix0to1[11][10] = 0.387551722067657;
   fWeightMatrix0to1[12][10] = 0.316117615653263;
   fWeightMatrix0to1[13][10] = -1.49216371734024;
   fWeightMatrix0to1[14][10] = 1.42706139105359;
   fWeightMatrix0to1[15][10] = 0.184552141091362;
   fWeightMatrix0to1[16][10] = -0.339355458760084;
   fWeightMatrix0to1[17][10] = -0.336191601710011;
   fWeightMatrix0to1[18][10] = 0.58549569415869;
   fWeightMatrix0to1[0][11] = 0.555385937488911;
   fWeightMatrix0to1[1][11] = 1.1641060099695;
   fWeightMatrix0to1[2][11] = 0.552860464577681;
   fWeightMatrix0to1[3][11] = -1.04893263978528;
   fWeightMatrix0to1[4][11] = -0.876123875939706;
   fWeightMatrix0to1[5][11] = 1.36308429138453;
   fWeightMatrix0to1[6][11] = 1.41668124920626;
   fWeightMatrix0to1[7][11] = 0.882048296614763;
   fWeightMatrix0to1[8][11] = -0.965482707201482;
   fWeightMatrix0to1[9][11] = 1.68978069220612;
   fWeightMatrix0to1[10][11] = -1.09949224679752;
   fWeightMatrix0to1[11][11] = -1.36346291593223;
   fWeightMatrix0to1[12][11] = -0.162839384291758;
   fWeightMatrix0to1[13][11] = -1.46417854042953;
   fWeightMatrix0to1[14][11] = 0.684988931281997;
   fWeightMatrix0to1[15][11] = 1.82035900530407;
   fWeightMatrix0to1[16][11] = -1.4594768090156;
   fWeightMatrix0to1[17][11] = 0.17384899727866;
   fWeightMatrix0to1[18][11] = -0.156792263928932;
   fWeightMatrix0to1[0][12] = -1.88288242763294;
   fWeightMatrix0to1[1][12] = -0.0164245001549846;
   fWeightMatrix0to1[2][12] = 1.24028374794462;
   fWeightMatrix0to1[3][12] = 1.14402060443923;
   fWeightMatrix0to1[4][12] = 0.229198701985152;
   fWeightMatrix0to1[5][12] = -1.13561445357475;
   fWeightMatrix0to1[6][12] = 1.98652483130782;
   fWeightMatrix0to1[7][12] = -1.64256671526982;
   fWeightMatrix0to1[8][12] = -0.0911399381878632;
   fWeightMatrix0to1[9][12] = -0.45691797558424;
   fWeightMatrix0to1[10][12] = -0.517399546046581;
   fWeightMatrix0to1[11][12] = -1.41766117666157;
   fWeightMatrix0to1[12][12] = -2.28413739384965;
   fWeightMatrix0to1[13][12] = -0.903135514882496;
   fWeightMatrix0to1[14][12] = -1.80713465932203;
   fWeightMatrix0to1[15][12] = -1.05612744260604;
   fWeightMatrix0to1[16][12] = -1.98452543549006;
   fWeightMatrix0to1[17][12] = -0.55813736628329;
   fWeightMatrix0to1[18][12] = -1.13081571134064;
   fWeightMatrix0to1[0][13] = -2.44006521731117;
   fWeightMatrix0to1[1][13] = 1.29735599640306;
   fWeightMatrix0to1[2][13] = -0.059157264479253;
   fWeightMatrix0to1[3][13] = 0.762135603675516;
   fWeightMatrix0to1[4][13] = -0.658369733572862;
   fWeightMatrix0to1[5][13] = -0.244538223881506;
   fWeightMatrix0to1[6][13] = 1.96068853707788;
   fWeightMatrix0to1[7][13] = 1.28209746971185;
   fWeightMatrix0to1[8][13] = -0.529128435280452;
   fWeightMatrix0to1[9][13] = -2.11834008557793;
   fWeightMatrix0to1[10][13] = -0.480424403508485;
   fWeightMatrix0to1[11][13] = -0.887816182253086;
   fWeightMatrix0to1[12][13] = -1.8327062839906;
   fWeightMatrix0to1[13][13] = -0.192239350724659;
   fWeightMatrix0to1[14][13] = -0.0101789664827738;
   fWeightMatrix0to1[15][13] = 1.46751446625709;
   fWeightMatrix0to1[16][13] = -0.535023240275181;
   fWeightMatrix0to1[17][13] = -0.291814291154665;
   fWeightMatrix0to1[18][13] = -0.817013772933751;
   fWeightMatrix0to1[0][14] = -1.34545570642959;
   fWeightMatrix0to1[1][14] = 0.804451844522684;
   fWeightMatrix0to1[2][14] = 0.378254018077823;
   fWeightMatrix0to1[3][14] = -1.7618192356847;
   fWeightMatrix0to1[4][14] = -1.32860220017157;
   fWeightMatrix0to1[5][14] = 1.3391031581909;
   fWeightMatrix0to1[6][14] = 1.07256179676582;
   fWeightMatrix0to1[7][14] = 0.337144239507688;
   fWeightMatrix0to1[8][14] = 0.0776249744627057;
   fWeightMatrix0to1[9][14] = 0.152706639131286;
   fWeightMatrix0to1[10][14] = 0.967115086789691;
   fWeightMatrix0to1[11][14] = 1.01771719623616;
   fWeightMatrix0to1[12][14] = 1.0750256267579;
   fWeightMatrix0to1[13][14] = 0.308582682279307;
   fWeightMatrix0to1[14][14] = 0.592216844028513;
   fWeightMatrix0to1[15][14] = -0.870546543967791;
   fWeightMatrix0to1[16][14] = -1.28804029116985;
   fWeightMatrix0to1[17][14] = 0.0647256518313352;
   fWeightMatrix0to1[18][14] = -1.39299518406349;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -0.452724705508777;
   fWeightMatrix1to2[0][1] = 0.14413905492304;
   fWeightMatrix1to2[0][2] = 1.07384090008368;
   fWeightMatrix1to2[0][3] = -0.929112265571621;
   fWeightMatrix1to2[0][4] = 0.0724113439963482;
   fWeightMatrix1to2[0][5] = -1.05610238101677;
   fWeightMatrix1to2[0][6] = -0.508080435766698;
   fWeightMatrix1to2[0][7] = 0.0949120843808289;
   fWeightMatrix1to2[0][8] = 0.592666272057085;
   fWeightMatrix1to2[0][9] = 0.326334155187999;
   fWeightMatrix1to2[0][10] = -0.0972965125204533;
   fWeightMatrix1to2[0][11] = -0.221801257565187;
   fWeightMatrix1to2[0][12] = 0.622176979969654;
   fWeightMatrix1to2[0][13] = -1.36640901767596;
   fWeightMatrix1to2[0][14] = -1.12294710371668;
   fWeightMatrix1to2[0][15] = -1.44315790755474;
   fWeightMatrix1to2[0][16] = 0.0241722276537718;
   fWeightMatrix1to2[0][17] = 1.62297401817916;
   fWeightMatrix1to2[0][18] = -0.00987199800230697;
   fWeightMatrix1to2[0][19] = 0.438921832346884;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLP::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // nothing to clear
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 1.93987222119e-11;
   fMax_1[0][0] = 0.731256723404;
   fMin_1[1][0] = 2.11151655094e-05;
   fMax_1[1][0] = 0.726359844208;
   fMin_1[2][0] = 1.93987222119e-11;
   fMax_1[2][0] = 0.731256723404;
   fMin_1[0][1] = 0.0111495917663;
   fMax_1[0][1] = 21.7485733032;
   fMin_1[1][1] = 0.134300857782;
   fMax_1[1][1] = 20.9987621307;
   fMin_1[2][1] = 0.0111495917663;
   fMax_1[2][1] = 21.7485733032;
   fMin_1[0][2] = 0.00189490010962;
   fMax_1[0][2] = 14.9983968735;
   fMin_1[1][2] = 0.0220367405564;
   fMax_1[1][2] = 14.9877176285;
   fMin_1[2][2] = 0.00189490010962;
   fMax_1[2][2] = 14.9983968735;
   fMin_1[0][3] = 0;
   fMax_1[0][3] = 0.134104982018;
   fMin_1[1][3] = 0;
   fMax_1[1][3] = 0.137716650963;
   fMin_1[2][3] = 0;
   fMax_1[2][3] = 0.137716650963;
   fMin_1[0][4] = 62.147693634;
   fMax_1[0][4] = 37961.9179688;
   fMin_1[1][4] = 41.2933425903;
   fMax_1[1][4] = 21269.5722656;
   fMin_1[2][4] = 41.2933425903;
   fMax_1[2][4] = 37961.9179688;
   fMin_1[0][5] = 2.30495882034;
   fMax_1[0][5] = 102.738922119;
   fMin_1[1][5] = 2.78237915039;
   fMax_1[1][5] = 49.5175361633;
   fMin_1[2][5] = 2.30495882034;
   fMax_1[2][5] = 102.738922119;
   fMin_1[0][6] = 2.63570382231e-06;
   fMax_1[0][6] = 0.738568007946;
   fMin_1[1][6] = 3.91690700781e-05;
   fMax_1[1][6] = 0.731490552425;
   fMin_1[2][6] = 2.63570382231e-06;
   fMax_1[2][6] = 0.738568007946;
   fMin_1[0][7] = 2.4348450367e-08;
   fMax_1[0][7] = 0.622791826725;
   fMin_1[1][7] = 7.34744171496e-05;
   fMax_1[1][7] = 0.365254282951;
   fMin_1[2][7] = 2.4348450367e-08;
   fMax_1[2][7] = 0.622791826725;
   fMin_1[0][8] = 6.10736776707e-07;
   fMax_1[0][8] = 1.01704800129;
   fMin_1[1][8] = 3.12057891279e-05;
   fMax_1[1][8] = 0.672129392624;
   fMin_1[2][8] = 6.10736776707e-07;
   fMax_1[2][8] = 1.01704800129;
   fMin_1[0][9] = 0;
   fMax_1[0][9] = 13;
   fMin_1[1][9] = 0;
   fMax_1[1][9] = 17;
   fMin_1[2][9] = 0;
   fMax_1[2][9] = 17;
   fMin_1[0][10] = 0.00300450995564;
   fMax_1[0][10] = 1;
   fMin_1[1][10] = 0.0038299348671;
   fMax_1[1][10] = 1;
   fMin_1[2][10] = 0.00300450995564;
   fMax_1[2][10] = 1;
   fMin_1[0][11] = 0.0559116005898;
   fMax_1[0][11] = 72.067237854;
   fMin_1[1][11] = 0.151803418994;
   fMax_1[1][11] = 76.3943099976;
   fMin_1[2][11] = 0.0559116005898;
   fMax_1[2][11] = 76.3943099976;
   fMin_1[0][12] = 0.0131226135418;
   fMax_1[0][12] = 75.9046707153;
   fMin_1[1][12] = 0.146247655153;
   fMax_1[1][12] = 67.7235794067;
   fMin_1[2][12] = 0.0131226135418;
   fMax_1[2][12] = 75.9046707153;
   fMin_1[0][13] = 0.0151327997446;
   fMax_1[0][13] = 79.3785171509;
   fMin_1[1][13] = 0.0453270226717;
   fMax_1[1][13] = 68.506652832;
   fMin_1[2][13] = 0.0151327997446;
   fMax_1[2][13] = 79.3785171509;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 14;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   std::vector<int> indicesGet;
   std::vector<int> indicesPut;

   indicesGet.push_back( 0);
   indicesGet.push_back( 1);
   indicesGet.push_back( 2);
   indicesGet.push_back( 3);
   indicesGet.push_back( 4);
   indicesGet.push_back( 5);
   indicesGet.push_back( 6);
   indicesGet.push_back( 7);
   indicesGet.push_back( 8);
   indicesGet.push_back( 9);
   indicesGet.push_back( 10);
   indicesGet.push_back( 11);
   indicesGet.push_back( 12);
   indicesGet.push_back( 13);
   indicesPut.push_back( 0);
   indicesPut.push_back( 1);
   indicesPut.push_back( 2);
   indicesPut.push_back( 3);
   indicesPut.push_back( 4);
   indicesPut.push_back( 5);
   indicesPut.push_back( 6);
   indicesPut.push_back( 7);
   indicesPut.push_back( 8);
   indicesPut.push_back( 9);
   indicesPut.push_back( 10);
   indicesPut.push_back( 11);
   indicesPut.push_back( 12);
   indicesPut.push_back( 13);

   std::vector<double> dv(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<14;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
