#ifndef FLATHLT2
#define FLATHLT2 1
#include "iostream"

class crack_junkie {
  public:
    unsigned m_idx;
    float    m_evt;
    float    m_tos;
    float    m_tis;
    void     reset() {
      m_evt = 0.;
      m_tos = 0.;
      m_tis = 0.;
    }
};

std::string givethel0(unsigned name) {
  unsigned idx = 0u;

  if (name == idx++) return "L0B1gas";
  if (name == idx++) return "L0B2gas";
  if (name == idx++) return "L0Calo";
  if (name == idx++) return "L0DiMuon";
  if (name == idx++) return "L0DiMuonlowMult";
  if (name == idx++) return "L0Electron";
  if (name == idx++) return "L0GlobalPi0";
  if (name == idx++) return "L0HCAL";
  if (name == idx++) return "L0Hadron";
  if (name == idx++) return "L0LocalPi0";
  if (name == idx++) return "L0MuonMinbias";
  if (name == idx++) return "L0Muon";
  if (name == idx++) return "L0MuonLowMult";
  if (name == idx++) return "L0PU";
  if (name == idx++) return "L0PU20";
  if (name == idx++) return "L0Photon";
  if (name == idx++) return "L0SPD";
  if (name == idx++) return "L0SPD40";
  if (name == idx++) return "maxl0";

  return "NEED crack" ;


}std::string givethehlt1(unsigned name) {
  unsigned idx = 0u;

  if (name == idx++) return "Hlt1DiMuonHighMassDecision";
  if (name == idx++) return "Hlt1DiMuonLowMassDecision";
  if (name == idx++) return "Hlt1SingleMuonNoIPDecision";
  if (name == idx++) return "Hlt1SingleMuonHighPTDecision";
  if (name == idx++) return "Hlt1TrackAllL0Decision";
  if (name == idx++) return "Hlt1TrackMuonDecision";
  if (name == idx++) return "Hlt1TrackPhotonDecision";
  if (name == idx++) return "Hlt1LumiDecision";
  if (name == idx++) return "Hlt1LumiMidBeamCrossingDecision";
  if (name == idx++) return "Hlt1MBNoBiasDecision";
  if (name == idx++) return "Hlt1L0AnyDecision";
  if (name == idx++) return "Hlt1L0AnyRateLimitedDecision";
  if (name == idx++) return "Hlt1L0AnyNoSPDDecision";
  if (name == idx++) return "Hlt1L0AnyNoSPDRateLimitedDecision";
  if (name == idx++) return "Hlt1NoPVPassThroughDecision";
  if (name == idx++) return "Hlt1DiProtonLowMultDecision";
  if (name == idx++) return "Hlt1BeamGasNoBeamBeam1Decision";
  if (name == idx++) return "Hlt1BeamGasNoBeamBeam2Decision";
  if (name == idx++) return "Hlt1BeamGasBeam1Decision";
  if (name == idx++) return "Hlt1BeamGasBeam2Decision";
  if (name == idx++) return "Hlt1BeamGasCrossingEnhancedBeam1Decision";
  if (name == idx++) return "Hlt1BeamGasCrossingEnhancedBeam2Decision";
  if (name == idx++) return "Hlt1BeamGasCrossingForcedRecoDecision";
  if (name == idx++) return "Hlt1ODINTechnicalDecision";
  if (name == idx++) return "Hlt1Tell1ErrorDecision";
  if (name == idx++) return "Hlt1BeamGasCrossingParasiticDecision";
  if (name == idx++) return "Hlt1ErrorEventDecision";
  if (name == idx++) return "Hlt1Global";
  if (name == idx++) return "Hlt1MBMicroBiasVeloDecision";
  if (name == idx++) return "Hlt1MBMicroBiasVeloRateLimitedDecision";
  if (name == idx++) return "Hlt1MBMicroBiasTStationDecision";
  if (name == idx++) return "Hlt1MBMicroBiasTStationRateLimitedDecision";
  if (name == idx++) return "Hlt1DiProtonDecision";
  if (name == idx++) return "Hlt1VeloClosingMicroBiasDecision";
  if (name == idx++) return "Hlt1SingleElectronNoIPDecision";
  if (name == idx++) return "Hlt1TrackForwardPassThroughDecision";
  if (name == idx++) return "Hlt1TrackForwardPassThroughLooseDecision";
  if (name == idx++) return "Hlt1CharmCalibrationNoBiasDecision";
  if (name == idx++) return "Hlt1L0HighSumETJetDecision";
  if (name == idx++) return "Hlt1BeamGasCrossingForcedRecoFullZDecision";
  if (name == idx++) return "Hlt1BeamGasHighRhoVerticesDecision";
  if (name == idx++) return "Hlt1VertexDisplVertexDecision";
  if (name == idx++) return "Hlt1TrackAllL0TightDecision";
  if (name == idx++) return "maxhlt1";

  return "NEED crack" ;


}
std::string givethename(unsigned name) {
  unsigned idx = 0u;
  if (name == idx++) return "Hlt2SingleElectronTFLowPtDecision";
  if (name == idx++) return "Hlt2SingleElectronTFHighPtDecision";
  if (name == idx++) return "Hlt2DiElectronHighMassDecision";
  if (name == idx++) return "Hlt2DiElectronBDecision";
  if (name == idx++) return "Hlt2Topo2BodySimpleDecision";
  if (name == idx++) return "Hlt2Topo3BodySimpleDecision";
  if (name == idx++) return "Hlt2Topo4BodySimpleDecision";
  if (name == idx++) return "Hlt2Topo2BodyBBDTDecision";
  if (name == idx++) return "Hlt2Topo3BodyBBDTDecision";
  if (name == idx++) return "Hlt2Topo4BodyBBDTDecision";
  if (name == idx++) return "Hlt2TopoMu2BodyBBDTDecision";
  if (name == idx++) return "Hlt2TopoMu3BodyBBDTDecision";
  if (name == idx++) return "Hlt2TopoMu4BodyBBDTDecision";
  if (name == idx++) return "Hlt2TopoE2BodyBBDTDecision";
  if (name == idx++) return "Hlt2TopoE3BodyBBDTDecision";
  if (name == idx++) return "Hlt2TopoE4BodyBBDTDecision";
  if (name == idx++) return "Hlt2IncPhiDecision";
  if (name == idx++) return "Hlt2IncPhiSidebandsDecision";
  if (name == idx++) return "Hlt2CharmHadD02HHKsLLDecision";
  if (name == idx++) return "Hlt2Dst2PiD02PiPiDecision";
  if (name == idx++) return "Hlt2Dst2PiD02MuMuDecision";
  if (name == idx++) return "Hlt2Dst2PiD02KMuDecision";
  if (name == idx++) return "Hlt2Dst2PiD02KPiDecision";
  if (name == idx++) return "Hlt2PassThroughDecision";
  if (name == idx++) return "Hlt2TransparentDecision";
  if (name == idx++) return "Hlt2DebugEventDecision";
  if (name == idx++) return "Hlt2CharmHadD02KKDecision";
  if (name == idx++) return "Hlt2CharmHadD02KKWideMassDecision";
  if (name == idx++) return "Hlt2CharmHadD02KPiDecision";
  if (name == idx++) return "Hlt2CharmHadD02KPiWideMassDecision";
  if (name == idx++) return "Hlt2CharmHadD02PiPiDecision";
  if (name == idx++) return "Hlt2CharmHadD02PiPiWideMassDecision";
  if (name == idx++) return "Hlt2ExpressLambdaDecision";
  if (name == idx++) return "Hlt2ExpressDs2PhiPiDecision";
  if (name == idx++) return "Hlt2ExpressDStar2D0PiDecision";
  if (name == idx++) return "Hlt2ExpressHLT1PhysicsDecision";
  if (name == idx++) return "Hlt2Bs2PhiGammaDecision";
  if (name == idx++) return "Hlt2Bs2PhiGammaWideBMassDecision";
  if (name == idx++) return "Hlt2Bd2KstGammaDecision";
  if (name == idx++) return "Hlt2Bd2KstGammaWideKMassDecision";
  if (name == idx++) return "Hlt2Bd2KstGammaWideBMassDecision";
  if (name == idx++) return "Hlt2CharmHadD2KS0PiDecision";
  if (name == idx++) return "Hlt2CharmHadD2KS0KDecision";
  if (name == idx++) return "Hlt2CharmRareDecayD02MuMuDecision";
  if (name == idx++) return "Hlt2B2HHDecision";
  if (name == idx++) return "Hlt2MuonFromHLT1Decision";
  if (name == idx++) return "Hlt2SingleMuonDecision";
  if (name == idx++) return "Hlt2SingleMuonHighPTDecision";
  if (name == idx++) return "Hlt2SingleMuonLowPTDecision";
  if (name == idx++) return "Hlt2TFBc2JpsiMuXDecision";
  if (name == idx++) return "Hlt2TFBc2JpsiMuXSignalDecision";
  if (name == idx++) return "Hlt2DisplVerticesLowMassSingleDecision";
  if (name == idx++) return "Hlt2DisplVerticesHighMassSingleDecision";
  if (name == idx++) return "Hlt2DisplVerticesDoubleDecision";
  if (name == idx++) return "Hlt2DisplVerticesSinglePostScaledDecision";
  if (name == idx++) return "Hlt2DisplVerticesHighFDSingleDecision";
  if (name == idx++) return "Hlt2DisplVerticesSingleDownDecision";
  if (name == idx++) return "Hlt2B2HHPi0_MergedDecision";
  if (name == idx++) return "Hlt2CharmHadD2HHHDecision";
  if (name == idx++) return "Hlt2CharmHadD2HHHWideMassDecision";
  if (name == idx++) return "Hlt2DiMuonDecision";
  if (name == idx++) return "Hlt2DiMuonLowMassDecision";
  if (name == idx++) return "Hlt2DiMuonJPsiDecision";
  if (name == idx++) return "Hlt2DiMuonJPsiHighPTDecision";
  if (name == idx++) return "Hlt2DiMuonPsi2SDecision";
  if (name == idx++) return "Hlt2DiMuonBDecision";
  if (name == idx++) return "Hlt2DiMuonZDecision";
  if (name == idx++) return "Hlt2DiMuonDY1Decision";
  if (name == idx++) return "Hlt2DiMuonDY2Decision";
  if (name == idx++) return "Hlt2DiMuonDY3Decision";
  if (name == idx++) return "Hlt2DiMuonDY4Decision";
  if (name == idx++) return "Hlt2DiMuonDetachedDecision";
  if (name == idx++) return "Hlt2DiMuonDetachedHeavyDecision";
  if (name == idx++) return "Hlt2DiMuonDetachedJPsiDecision";
  if (name == idx++) return "Hlt2DiMuonNoPVDecision";
  if (name == idx++) return "Hlt2TriMuonDetachedDecision";
  if (name == idx++) return "Hlt2TriMuonTauDecision";
  if (name == idx++) return "Hlt2CharmHadD02HHHHDecision";
  if (name == idx++) return "Hlt2CharmHadD02HHHHWideMassDecision";
  if (name == idx++) return "Hlt2ErrorEventDecision";
  if (name == idx++) return "Hlt2B2HHLTUnbiasedDecision";
  if (name == idx++) return "Hlt2CharmHadD02HH_D02PiPiDecision";
  if (name == idx++) return "Hlt2CharmHadD02HH_D02PiPiWideMassDecision";
  if (name == idx++) return "Hlt2CharmHadD02HH_D02KKDecision";
  if (name == idx++) return "Hlt2CharmHadD02HH_D02KKWideMassDecision";
  if (name == idx++) return "Hlt2CharmHadD02HH_D02KPiDecision";
  if (name == idx++) return "Hlt2CharmHadD02HH_D02KPiWideMassDecision";
  if (name == idx++) return "Hlt2CharmHadD2KS0H_D2KS0PiDecision";
  if (name == idx++) return "Hlt2CharmHadD2KS0H_D2KS0KDecision";
  if (name == idx++) return "Hlt2DiProtonDecision";
  if (name == idx++) return "Hlt2DiProtonTFDecision";
  if (name == idx++) return "Hlt2DiProtonLowMultDecision";
  if (name == idx++) return "Hlt2DiProtonLowMultTFDecision";
  if (name == idx++) return "Hlt2CharmSemilepD02HMuNu_D02KMuNuWSDecision";
  if (name == idx++) return "Hlt2CharmSemilepD02HMuNu_D02PiMuNuWSDecision";
  if (name == idx++) return "Hlt2CharmSemilepD02HMuNu_D02KMuNuDecision";
  if (name == idx++) return "Hlt2CharmSemilepD02HMuNu_D02PiMuNuDecision";
  if (name == idx++) return "Hlt2CharmSemilepD2HMuMuDecision";
  if (name == idx++) return "Hlt2CharmSemilepD2HMuMuWideMassDecision";
  if (name == idx++) return "Hlt2CharmSemilepD02HHMuMuDecision";
  if (name == idx++) return "Hlt2CharmSemilepD02HHMuMuWideMassDecision";
  if (name == idx++) return "Hlt2diPhotonDiMuonDecision";
  if (name == idx++) return "Hlt2LowMultMuonDecision";
  if (name == idx++) return "Hlt2LowMultHadronDecision";
  if (name == idx++) return "Hlt2LowMultPhotonDecision";
  if (name == idx++) return "Hlt2LowMultElectronDecision";
  if (name == idx++) return "Hlt2SingleTFElectronDecision";
  if (name == idx++) return "Hlt2SingleTFVHighPtElectronDecision";
  if (name == idx++) return "Hlt2B2HHLTUnbiasedDetachedDecision";
  if (name == idx++) return "Hlt2CharmHadLambdaC2KPPiDecision";
  if (name == idx++) return "Hlt2SingleMuonVHighPTDecision";
  if (name == idx++) return "Hlt2CharmSemilepD02HMuNu_D02KMuNuTightDecision";
  if (name == idx++) return "Hlt2DisplVerticesSingleDecision";
  if (name == idx++) return "Hlt2DisplVerticesDoublePostScaledDecision";
  if (name == idx++) return "Hlt2DisplVerticesSingleHighMassPostScaledDecision";
  if (name == idx++) return "Hlt2DisplVerticesSingleHighFDPostScaledDecision";
  if (name == idx++) return "Hlt2DisplVerticesSingleMVPostScaledDecision";
  if (name == idx++) return "Hlt2RadiativeTopoTrackTOSDecision";
  if (name == idx++) return "Hlt2RadiativeTopoPhotonL0Decision";
  if (name == idx++) return "Hlt2DiMuonPsi2SHighPTDecision";
  if (name == idx++) return "Hlt2DoubleDiMuonDecision";
  if (name == idx++) return "Hlt2DiMuonAndMuonDecision";
  if (name == idx++) return "Hlt2DiMuonAndGammaDecision";
  if (name == idx++) return "Hlt2DiMuonAndD0Decision";
  if (name == idx++) return "Hlt2DiMuonAndDpDecision";
  if (name == idx++) return "Hlt2DiMuonAndDsDecision";
  if (name == idx++) return "Hlt2DiMuonAndLcDecision";
  if (name == idx++) return "Hlt2CharmSemilepD02HHMuMuHardHadronsSoftMuonsDecision";
  if (name == idx++) return "Hlt2CharmSemilepD02HHMuMuHardHadronsSoftMuonsWideMassDecision";
  if (name == idx++) return "Hlt2CharmSemilepD02HHMuMuHardHadronsAndMuonsDecision";
  if (name == idx++) return "Hlt2CharmSemilepD02HHMuMuHardHadronsAndMuonsWideMassDecision";
  if (name == idx++) return "Hlt2TopoRad2BodyBBDTDecision";
  if (name == idx++) return "Hlt2TopoRad2plus1BodyBBDTDecision";
  if (name == idx++) return "Hlt2LowMultHadron_nofilterDecision";
  if (name == idx++) return "Hlt2LowMultElectron_nofilterDecision";
  if (name == idx++) return "Hlt2CharmHadD02HHKsDDDecision";
  if (name == idx++) return "Hlt2CharmHadD2KS0KS0Decision";
  if (name == idx++) return "Hlt2CharmHadD2KS0KS0WideMassDecision";
  if (name == idx++) return "Hlt2ExpressD02KPiDecision";
  if (name == idx++) return "Hlt2CharmHadLambdaC2KPPiWideMassDecision";
  if (name == idx++) return "Hlt2CharmHadLambdaC2KPKDecision";
  if (name == idx++) return "Hlt2CharmHadLambdaC2KPKWideMassDecision";
  if (name == idx++) return "Hlt2CharmHadLambdaC2PiPPiDecision";
  if (name == idx++) return "Hlt2CharmHadLambdaC2PiPPiWideMassDecision";
  if (name == idx++) return "Hlt2CharmHadLambdaC2PiPKDecision";
  if (name == idx++) return "Hlt2CharmHadLambdaC2PiPKWideMassDecision";
  if (name == idx++) return "Hlt2CharmHadD2KS0H_D2KS0DDPiDecision";
  if (name == idx++) return "Hlt2CharmHadD2KS0H_D2KS0DDKDecision";
  if (name == idx++) return "Hlt2DiPhiDecision";
  if (name == idx++) return "Hlt2CharmHadD02HHHHDstNoHltOne_4piDecision";
  if (name == idx++) return "Hlt2CharmHadD02HHHHDstNoHltOne_4piWideMassDecision";
  if (name == idx++) return "Hlt2CharmHadD02HHHHDstNoHltOne_K3piDecision";
  if (name == idx++) return "Hlt2CharmHadD02HHHHDstNoHltOne_K3piWideMassDecision";
  if (name == idx++) return "Hlt2CharmHadD02HHHHDstNoHltOne_KKpipiDecision";
  if (name == idx++) return "Hlt2CharmHadD02HHHHDstNoHltOne_KKpipiWideMassDecision";
  if (name == idx++) return "Hlt2CharmHadD02HHHHDstNoHltOne_2K2piDecision";
  if (name == idx++) return "Hlt2CharmHadD02HHHHDstNoHltOne_2K2piWideMassDecision";
  if (name == idx++) return "Hlt2CharmHadD02HHHHDstNoHltOne_3KpiDecision";
  if (name == idx++) return "Hlt2CharmHadD02HHHHDstNoHltOne_3KpiWideMassDecision";
  if (name == idx++) return "Hlt2CharmHadD02HHHHDstNoHltOne_Ch2Decision";
  if (name == idx++) return "Hlt2CharmHadD02HHHHDstNoHltOne_Ch2WideMassDecision";
  if (name == idx++) return "Hlt2CharmSemilep3bodyD2PiMuMuDecision";
  if (name == idx++) return "Hlt2CharmSemilep3bodyD2PiMuMuSSDecision";
  if (name == idx++) return "Hlt2CharmSemilep3bodyD2KMuMuDecision";
  if (name == idx++) return "Hlt2CharmSemilep3bodyD2KMuMuSSDecision";
  if (name == idx++) return "Hlt2CharmSemilep3bodyLambdac2PMuMuDecision";
  if (name == idx++) return "Hlt2CharmSemilep3bodyLambdac2PMuMuSSDecision";
  if (name == idx++) return "Hlt2LambdaC_LambdaC2Lambda0LLPiDecision";
  if (name == idx++) return "Hlt2LambdaC_LambdaC2Lambda0LLKDecision";
  if (name == idx++) return "Hlt2LambdaC_LambdaC2Lambda0DDPiDecision";
  if (name == idx++) return "Hlt2LambdaC_LambdaC2Lambda0DDKDecision";
  if (name == idx++) return "Hlt2RadiativeTopoTrackDecision";
  if (name == idx++) return "Hlt2RadiativeTopoPhotonDecision";
  if (name == idx++) return "Hlt2CharmHadD02HHHHDst_4piDecision";
  if (name == idx++) return "Hlt2CharmHadD02HHHHDst_4piWideMassDecision";
  if (name == idx++) return "Hlt2CharmHadD02HHHHDst_K3piDecision";
  if (name == idx++) return "Hlt2CharmHadD02HHHHDst_K3piWideMassDecision";
  if (name == idx++) return "Hlt2CharmHadD02HHHHDst_KKpipiDecision";
  if (name == idx++) return "Hlt2CharmHadD02HHHHDst_KKpipiWideMassDecision";
  if (name == idx++) return "Hlt2CharmHadD02HHHHDst_2K2piDecision";
  if (name == idx++) return "Hlt2CharmHadD02HHHHDst_2K2piWideMassDecision";
  if (name == idx++) return "Hlt2CharmHadD02HHHHDst_3KpiDecision";
  if (name == idx++) return "Hlt2CharmHadD02HHHHDst_3KpiWideMassDecision";
  if (name == idx++) return "Hlt2CharmHadD02HHHHDst_Ch2Decision";
  if (name == idx++) return "Hlt2CharmHadD02HHHHDst_Ch2WideMassDecision";
  if (name == idx++) return "Hlt2CharmSemilepD02PiPiMuMuDecision";
  if (name == idx++) return "Hlt2CharmSemilepD02KKMuMuDecision";
  if (name == idx++) return "Hlt2CharmSemilepD02KPiMuMuDecision";
  if (name == idx++) return "Hlt2CharmHadD02HHHH_4piDecision";
  if (name == idx++) return "Hlt2CharmHadD02HHHH_4piWideMassDecision";
  if (name == idx++) return "Hlt2CharmHadD02HHHH_K3piDecision";
  if (name == idx++) return "Hlt2CharmHadD02HHHH_K3piWideMassDecision";
  if (name == idx++) return "Hlt2CharmHadD02HHHH_KKpipiDecision";
  if (name == idx++) return "Hlt2CharmHadD02HHHH_KKpipiWideMassDecision";
  if (name == idx++) return "Hlt2CharmHadD02HHHH_2K2piDecision";
  if (name == idx++) return "Hlt2CharmHadD02HHHH_2K2piWideMassDecision";
  if (name == idx++) return "Hlt2CharmHadD02HHHH_3KpiDecision";
  if (name == idx++) return "Hlt2CharmHadD02HHHH_3KpiWideMassDecision";
  if (name == idx++) return "Hlt2CharmHadD02HHHH_Ch2Decision";
  if (name == idx++) return "Hlt2CharmHadD02HHHH_Ch2WideMassDecision";
  if (name == idx++) return "Hlt2DiMuonDetachedPsi2SDecision";
  if (name == idx++) return "Hlt2CharmHadD02HHXDst_hhXDecision";
  if (name == idx++) return "Hlt2CharmHadD02HHXDst_hhXWideMassDecision";
  if (name == idx++) return "Hlt2LowMultD2KPiDecision";
  if (name == idx++) return "Hlt2LowMultD2KPiPiDecision";
  if (name == idx++) return "Hlt2LowMultD2K3PiDecision";
  if (name == idx++) return "Hlt2LowMultChiC2HHDecision";
  if (name == idx++) return "Hlt2LowMultChiC2HHHHDecision";
  if (name == idx++) return "Hlt2LowMultD2KPiWSDecision";
  if (name == idx++) return "Hlt2LowMultD2KPiPiWSDecision";
  if (name == idx++) return "Hlt2LowMultD2K3PiWSDecision";
  if (name == idx++) return "Hlt2LowMultChiC2HHWSDecision";
  if (name == idx++) return "Hlt2LowMultChiC2HHHHWSDecision";
  if (name == idx++) return "Hlt2LowMultDDIncDecision";
  if (name == idx++) return "Hlt2DisplVerticesSingleLoosePSDecision";
  if (name == idx++) return "Hlt2DisplVerticesSingleHighFDDecision";
  if (name == idx++) return "Hlt2DisplVerticesSingleVeryHighFDDecision";
  if (name == idx++) return "Hlt2DisplVerticesSingleHighMassDecision";
  if (name == idx++) return "Hlt2DisplVerticesSinglePSDecision";
  if (name == idx++) return "Hlt2DisplVerticesDoublePSDecision";
  if (name == idx++) return "maxindex";

  return "NEED crack" ;


}




unsigned index(std::string name) {
  unsigned idx = 0u;
  if (name == "TriggerTOSHlt2SingleElectronTFLowPtDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2SingleElectronTFHighPtDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2DiElectronHighMassDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2DiElectronBDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2Topo2BodySimpleDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2Topo3BodySimpleDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2Topo4BodySimpleDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2Topo2BodyBBDTDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2Topo3BodyBBDTDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2Topo4BodyBBDTDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2TopoMu2BodyBBDTDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2TopoMu3BodyBBDTDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2TopoMu4BodyBBDTDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2TopoE2BodyBBDTDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2TopoE3BodyBBDTDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2TopoE4BodyBBDTDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2IncPhiDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2IncPhiSidebandsDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmHadD02HHKsLLDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2Dst2PiD02PiPiDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2Dst2PiD02MuMuDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2Dst2PiD02KMuDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2Dst2PiD02KPiDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2PassThroughDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2TransparentDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2DebugEventDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmHadD02KKDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmHadD02KKWideMassDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmHadD02KPiDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmHadD02KPiWideMassDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmHadD02PiPiDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmHadD02PiPiWideMassDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2ExpressLambdaDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2ExpressDs2PhiPiDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2ExpressDStar2D0PiDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2ExpressHLT1PhysicsDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2Bs2PhiGammaDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2Bs2PhiGammaWideBMassDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2Bd2KstGammaDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2Bd2KstGammaWideKMassDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2Bd2KstGammaWideBMassDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmHadD2KS0PiDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmHadD2KS0KDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmRareDecayD02MuMuDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2B2HHDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2MuonFromHLT1Decision") return idx; ++idx;
  if (name == "TriggerTOSHlt2SingleMuonDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2SingleMuonHighPTDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2SingleMuonLowPTDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2TFBc2JpsiMuXDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2TFBc2JpsiMuXSignalDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2DisplVerticesLowMassSingleDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2DisplVerticesHighMassSingleDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2DisplVerticesDoubleDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2DisplVerticesSinglePostScaledDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2DisplVerticesHighFDSingleDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2DisplVerticesSingleDownDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2B2HHPi0_MergedDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmHadD2HHHDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmHadD2HHHWideMassDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2DiMuonDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2DiMuonLowMassDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2DiMuonJPsiDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2DiMuonJPsiHighPTDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2DiMuonPsi2SDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2DiMuonBDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2DiMuonZDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2DiMuonDY1Decision") return idx; ++idx;
  if (name == "TriggerTOSHlt2DiMuonDY2Decision") return idx; ++idx;
  if (name == "TriggerTOSHlt2DiMuonDY3Decision") return idx; ++idx;
  if (name == "TriggerTOSHlt2DiMuonDY4Decision") return idx; ++idx;
  if (name == "TriggerTOSHlt2DiMuonDetachedDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2DiMuonDetachedHeavyDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2DiMuonDetachedJPsiDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2DiMuonNoPVDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2TriMuonDetachedDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2TriMuonTauDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmHadD02HHHHDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmHadD02HHHHWideMassDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2ErrorEventDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2B2HHLTUnbiasedDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmHadD02HH_D02PiPiDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmHadD02HH_D02PiPiWideMassDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmHadD02HH_D02KKDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmHadD02HH_D02KKWideMassDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmHadD02HH_D02KPiDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmHadD02HH_D02KPiWideMassDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmHadD2KS0H_D2KS0PiDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmHadD2KS0H_D2KS0KDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2DiProtonDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2DiProtonTFDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2DiProtonLowMultDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2DiProtonLowMultTFDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmSemilepD02HMuNu_D02KMuNuWSDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmSemilepD02HMuNu_D02PiMuNuWSDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmSemilepD02HMuNu_D02KMuNuDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmSemilepD02HMuNu_D02PiMuNuDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmSemilepD2HMuMuDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmSemilepD2HMuMuWideMassDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmSemilepD02HHMuMuDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmSemilepD02HHMuMuWideMassDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2diPhotonDiMuonDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2LowMultMuonDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2LowMultHadronDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2LowMultPhotonDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2LowMultElectronDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2SingleTFElectronDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2SingleTFVHighPtElectronDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2B2HHLTUnbiasedDetachedDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmHadLambdaC2KPPiDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2SingleMuonVHighPTDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmSemilepD02HMuNu_D02KMuNuTightDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2DisplVerticesSingleDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2DisplVerticesDoublePostScaledDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2DisplVerticesSingleHighMassPostScaledDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2DisplVerticesSingleHighFDPostScaledDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2DisplVerticesSingleMVPostScaledDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2RadiativeTopoTrackTOSDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2RadiativeTopoPhotonL0Decision") return idx; ++idx;
  if (name == "TriggerTOSHlt2DiMuonPsi2SHighPTDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2DoubleDiMuonDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2DiMuonAndMuonDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2DiMuonAndGammaDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2DiMuonAndD0Decision") return idx; ++idx;
  if (name == "TriggerTOSHlt2DiMuonAndDpDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2DiMuonAndDsDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2DiMuonAndLcDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmSemilepD02HHMuMuHardHadronsSoftMuonsDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmSemilepD02HHMuMuHardHadronsSoftMuonsWideMassDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmSemilepD02HHMuMuHardHadronsAndMuonsDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmSemilepD02HHMuMuHardHadronsAndMuonsWideMassDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2TopoRad2BodyBBDTDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2TopoRad2plus1BodyBBDTDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2LowMultHadron_nofilterDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2LowMultElectron_nofilterDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmHadD02HHKsDDDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmHadD2KS0KS0Decision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmHadD2KS0KS0WideMassDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2ExpressD02KPiDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmHadLambdaC2KPPiWideMassDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmHadLambdaC2KPKDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmHadLambdaC2KPKWideMassDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmHadLambdaC2PiPPiDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmHadLambdaC2PiPPiWideMassDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmHadLambdaC2PiPKDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmHadLambdaC2PiPKWideMassDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmHadD2KS0H_D2KS0DDPiDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmHadD2KS0H_D2KS0DDKDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2DiPhiDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmHadD02HHHHDstNoHltOne_4piDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmHadD02HHHHDstNoHltOne_4piWideMassDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmHadD02HHHHDstNoHltOne_K3piDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmHadD02HHHHDstNoHltOne_K3piWideMassDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmHadD02HHHHDstNoHltOne_KKpipiDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmHadD02HHHHDstNoHltOne_KKpipiWideMassDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmHadD02HHHHDstNoHltOne_2K2piDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmHadD02HHHHDstNoHltOne_2K2piWideMassDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmHadD02HHHHDstNoHltOne_3KpiDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmHadD02HHHHDstNoHltOne_3KpiWideMassDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmHadD02HHHHDstNoHltOne_Ch2Decision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmHadD02HHHHDstNoHltOne_Ch2WideMassDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmSemilep3bodyD2PiMuMuDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmSemilep3bodyD2PiMuMuSSDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmSemilep3bodyD2KMuMuDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmSemilep3bodyD2KMuMuSSDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmSemilep3bodyLambdac2PMuMuDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmSemilep3bodyLambdac2PMuMuSSDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2LambdaC_LambdaC2Lambda0LLPiDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2LambdaC_LambdaC2Lambda0LLKDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2LambdaC_LambdaC2Lambda0DDPiDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2LambdaC_LambdaC2Lambda0DDKDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2RadiativeTopoTrackDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2RadiativeTopoPhotonDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmHadD02HHHHDst_4piDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmHadD02HHHHDst_4piWideMassDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmHadD02HHHHDst_K3piDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmHadD02HHHHDst_K3piWideMassDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmHadD02HHHHDst_KKpipiDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmHadD02HHHHDst_KKpipiWideMassDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmHadD02HHHHDst_2K2piDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmHadD02HHHHDst_2K2piWideMassDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmHadD02HHHHDst_3KpiDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmHadD02HHHHDst_3KpiWideMassDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmHadD02HHHHDst_Ch2Decision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmHadD02HHHHDst_Ch2WideMassDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmSemilepD02PiPiMuMuDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmSemilepD02KKMuMuDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmSemilepD02KPiMuMuDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmHadD02HHHH_4piDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmHadD02HHHH_4piWideMassDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmHadD02HHHH_K3piDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmHadD02HHHH_K3piWideMassDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmHadD02HHHH_KKpipiDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmHadD02HHHH_KKpipiWideMassDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmHadD02HHHH_2K2piDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmHadD02HHHH_2K2piWideMassDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmHadD02HHHH_3KpiDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmHadD02HHHH_3KpiWideMassDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmHadD02HHHH_Ch2Decision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmHadD02HHHH_Ch2WideMassDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2DiMuonDetachedPsi2SDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmHadD02HHXDst_hhXDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2CharmHadD02HHXDst_hhXWideMassDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2LowMultD2KPiDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2LowMultD2KPiPiDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2LowMultD2K3PiDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2LowMultChiC2HHDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2LowMultChiC2HHHHDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2LowMultD2KPiWSDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2LowMultD2KPiPiWSDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2LowMultD2K3PiWSDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2LowMultChiC2HHWSDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2LowMultChiC2HHHHWSDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2LowMultDDIncDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2DisplVerticesSingleLoosePSDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2DisplVerticesSingleHighFDDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2DisplVerticesSingleVeryHighFDDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2DisplVerticesSingleHighMassDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2DisplVerticesSinglePSDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt2DisplVerticesDoublePSDecision") return idx; ++idx;
  if (name == "maxindex") return idx;

  idx = 0u;
  if (name == "TriggerDecHlt2SingleElectronTFLowPtDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2SingleElectronTFHighPtDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2DiElectronHighMassDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2DiElectronBDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2Topo2BodySimpleDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2Topo3BodySimpleDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2Topo4BodySimpleDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2Topo2BodyBBDTDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2Topo3BodyBBDTDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2Topo4BodyBBDTDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2TopoMu2BodyBBDTDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2TopoMu3BodyBBDTDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2TopoMu4BodyBBDTDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2TopoE2BodyBBDTDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2TopoE3BodyBBDTDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2TopoE4BodyBBDTDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2IncPhiDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2IncPhiSidebandsDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmHadD02HHKsLLDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2Dst2PiD02PiPiDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2Dst2PiD02MuMuDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2Dst2PiD02KMuDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2Dst2PiD02KPiDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2PassThroughDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2TransparentDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2DebugEventDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmHadD02KKDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmHadD02KKWideMassDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmHadD02KPiDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmHadD02KPiWideMassDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmHadD02PiPiDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmHadD02PiPiWideMassDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2ExpressLambdaDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2ExpressDs2PhiPiDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2ExpressDStar2D0PiDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2ExpressHLT1PhysicsDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2Bs2PhiGammaDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2Bs2PhiGammaWideBMassDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2Bd2KstGammaDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2Bd2KstGammaWideKMassDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2Bd2KstGammaWideBMassDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmHadD2KS0PiDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmHadD2KS0KDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmRareDecayD02MuMuDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2B2HHDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2MuonFromHLT1Decision") return idx; ++idx;
  if (name == "TriggerDecHlt2SingleMuonDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2SingleMuonHighPTDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2SingleMuonLowPTDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2TFBc2JpsiMuXDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2TFBc2JpsiMuXSignalDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2DisplVerticesLowMassSingleDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2DisplVerticesHighMassSingleDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2DisplVerticesDoubleDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2DisplVerticesSinglePostScaledDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2DisplVerticesHighFDSingleDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2DisplVerticesSingleDownDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2B2HHPi0_MergedDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmHadD2HHHDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmHadD2HHHWideMassDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2DiMuonDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2DiMuonLowMassDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2DiMuonJPsiDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2DiMuonJPsiHighPTDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2DiMuonPsi2SDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2DiMuonBDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2DiMuonZDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2DiMuonDY1Decision") return idx; ++idx;
  if (name == "TriggerDecHlt2DiMuonDY2Decision") return idx; ++idx;
  if (name == "TriggerDecHlt2DiMuonDY3Decision") return idx; ++idx;
  if (name == "TriggerDecHlt2DiMuonDY4Decision") return idx; ++idx;
  if (name == "TriggerDecHlt2DiMuonDetachedDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2DiMuonDetachedHeavyDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2DiMuonDetachedJPsiDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2DiMuonNoPVDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2TriMuonDetachedDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2TriMuonTauDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmHadD02HHHHDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmHadD02HHHHWideMassDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2ErrorEventDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2B2HHLTUnbiasedDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmHadD02HH_D02PiPiDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmHadD02HH_D02PiPiWideMassDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmHadD02HH_D02KKDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmHadD02HH_D02KKWideMassDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmHadD02HH_D02KPiDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmHadD02HH_D02KPiWideMassDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmHadD2KS0H_D2KS0PiDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmHadD2KS0H_D2KS0KDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2DiProtonDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2DiProtonTFDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2DiProtonLowMultDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2DiProtonLowMultTFDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmSemilepD02HMuNu_D02KMuNuWSDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmSemilepD02HMuNu_D02PiMuNuWSDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmSemilepD02HMuNu_D02KMuNuDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmSemilepD02HMuNu_D02PiMuNuDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmSemilepD2HMuMuDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmSemilepD2HMuMuWideMassDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmSemilepD02HHMuMuDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmSemilepD02HHMuMuWideMassDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2diPhotonDiMuonDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2LowMultMuonDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2LowMultHadronDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2LowMultPhotonDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2LowMultElectronDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2SingleTFElectronDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2SingleTFVHighPtElectronDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2B2HHLTUnbiasedDetachedDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmHadLambdaC2KPPiDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2SingleMuonVHighPTDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmSemilepD02HMuNu_D02KMuNuTightDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2DisplVerticesSingleDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2DisplVerticesDoublePostScaledDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2DisplVerticesSingleHighMassPostScaledDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2DisplVerticesSingleHighFDPostScaledDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2DisplVerticesSingleMVPostScaledDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2RadiativeTopoTrackTOSDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2RadiativeTopoPhotonL0Decision") return idx; ++idx;
  if (name == "TriggerDecHlt2DiMuonPsi2SHighPTDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2DoubleDiMuonDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2DiMuonAndMuonDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2DiMuonAndGammaDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2DiMuonAndD0Decision") return idx; ++idx;
  if (name == "TriggerDecHlt2DiMuonAndDpDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2DiMuonAndDsDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2DiMuonAndLcDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmSemilepD02HHMuMuHardHadronsSoftMuonsDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmSemilepD02HHMuMuHardHadronsSoftMuonsWideMassDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmSemilepD02HHMuMuHardHadronsAndMuonsDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmSemilepD02HHMuMuHardHadronsAndMuonsWideMassDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2TopoRad2BodyBBDTDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2TopoRad2plus1BodyBBDTDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2LowMultHadron_nofilterDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2LowMultElectron_nofilterDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmHadD02HHKsDDDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmHadD2KS0KS0Decision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmHadD2KS0KS0WideMassDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2ExpressD02KPiDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmHadLambdaC2KPPiWideMassDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmHadLambdaC2KPKDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmHadLambdaC2KPKWideMassDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmHadLambdaC2PiPPiDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmHadLambdaC2PiPPiWideMassDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmHadLambdaC2PiPKDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmHadLambdaC2PiPKWideMassDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmHadD2KS0H_D2KS0DDPiDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmHadD2KS0H_D2KS0DDKDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2DiPhiDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmHadD02HHHHDstNoHltOne_4piDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmHadD02HHHHDstNoHltOne_4piWideMassDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmHadD02HHHHDstNoHltOne_K3piDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmHadD02HHHHDstNoHltOne_K3piWideMassDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmHadD02HHHHDstNoHltOne_KKpipiDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmHadD02HHHHDstNoHltOne_KKpipiWideMassDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmHadD02HHHHDstNoHltOne_2K2piDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmHadD02HHHHDstNoHltOne_2K2piWideMassDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmHadD02HHHHDstNoHltOne_3KpiDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmHadD02HHHHDstNoHltOne_3KpiWideMassDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmHadD02HHHHDstNoHltOne_Ch2Decision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmHadD02HHHHDstNoHltOne_Ch2WideMassDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmSemilep3bodyD2PiMuMuDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmSemilep3bodyD2PiMuMuSSDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmSemilep3bodyD2KMuMuDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmSemilep3bodyD2KMuMuSSDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmSemilep3bodyLambdac2PMuMuDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmSemilep3bodyLambdac2PMuMuSSDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2LambdaC_LambdaC2Lambda0LLPiDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2LambdaC_LambdaC2Lambda0LLKDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2LambdaC_LambdaC2Lambda0DDPiDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2LambdaC_LambdaC2Lambda0DDKDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2RadiativeTopoTrackDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2RadiativeTopoPhotonDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmHadD02HHHHDst_4piDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmHadD02HHHHDst_4piWideMassDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmHadD02HHHHDst_K3piDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmHadD02HHHHDst_K3piWideMassDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmHadD02HHHHDst_KKpipiDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmHadD02HHHHDst_KKpipiWideMassDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmHadD02HHHHDst_2K2piDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmHadD02HHHHDst_2K2piWideMassDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmHadD02HHHHDst_3KpiDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmHadD02HHHHDst_3KpiWideMassDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmHadD02HHHHDst_Ch2Decision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmHadD02HHHHDst_Ch2WideMassDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmSemilepD02PiPiMuMuDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmSemilepD02KKMuMuDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmSemilepD02KPiMuMuDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmHadD02HHHH_4piDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmHadD02HHHH_4piWideMassDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmHadD02HHHH_K3piDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmHadD02HHHH_K3piWideMassDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmHadD02HHHH_KKpipiDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmHadD02HHHH_KKpipiWideMassDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmHadD02HHHH_2K2piDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmHadD02HHHH_2K2piWideMassDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmHadD02HHHH_3KpiDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmHadD02HHHH_3KpiWideMassDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmHadD02HHHH_Ch2Decision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmHadD02HHHH_Ch2WideMassDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2DiMuonDetachedPsi2SDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmHadD02HHXDst_hhXDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2CharmHadD02HHXDst_hhXWideMassDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2LowMultD2KPiDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2LowMultD2KPiPiDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2LowMultD2K3PiDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2LowMultChiC2HHDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2LowMultChiC2HHHHDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2LowMultD2KPiWSDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2LowMultD2KPiPiWSDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2LowMultD2K3PiWSDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2LowMultChiC2HHWSDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2LowMultChiC2HHHHWSDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2LowMultDDIncDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2DisplVerticesSingleLoosePSDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2DisplVerticesSingleHighFDDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2DisplVerticesSingleVeryHighFDDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2DisplVerticesSingleHighMassDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2DisplVerticesSinglePSDecision") return idx; ++idx;
  if (name == "TriggerDecHlt2DisplVerticesDoublePSDecision") return idx; ++idx;
  if (name == "maxindex") return idx;

  idx = 0u;
  if (name == "TriggerTOSHlt1DiMuonHighMassDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt1DiMuonLowMassDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt1SingleMuonNoIPDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt1SingleMuonHighPTDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt1TrackAllL0Decision") return idx; ++idx;
  if (name == "TriggerTOSHlt1TrackMuonDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt1TrackPhotonDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt1LumiDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt1LumiMidBeamCrossingDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt1MBNoBiasDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt1L0AnyDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt1L0AnyRateLimitedDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt1L0AnyNoSPDDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt1L0AnyNoSPDRateLimitedDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt1NoPVPassThroughDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt1DiProtonLowMultDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt1BeamGasNoBeamBeam1Decision") return idx; ++idx;
  if (name == "TriggerTOSHlt1BeamGasNoBeamBeam2Decision") return idx; ++idx;
  if (name == "TriggerTOSHlt1BeamGasBeam1Decision") return idx; ++idx;
  if (name == "TriggerTOSHlt1BeamGasBeam2Decision") return idx; ++idx;
  if (name == "TriggerTOSHlt1BeamGasCrossingEnhancedBeam1Decision") return idx; ++idx;
  if (name == "TriggerTOSHlt1BeamGasCrossingEnhancedBeam2Decision") return idx; ++idx;
  if (name == "TriggerTOSHlt1BeamGasCrossingForcedRecoDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt1ODINTechnicalDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt1Tell1ErrorDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt1BeamGasCrossingParasiticDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt1ErrorEventDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt1Global") return idx; ++idx;
  if (name == "TriggerTOSHlt1MBMicroBiasVeloDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt1MBMicroBiasVeloRateLimitedDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt1MBMicroBiasTStationDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt1MBMicroBiasTStationRateLimitedDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt1DiProtonDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt1VeloClosingMicroBiasDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt1SingleElectronNoIPDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt1TrackForwardPassThroughDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt1TrackForwardPassThroughLooseDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt1CharmCalibrationNoBiasDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt1L0HighSumETJetDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt1BeamGasCrossingForcedRecoFullZDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt1BeamGasHighRhoVerticesDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt1VertexDisplVertexDecision") return idx; ++idx;
  if (name == "TriggerTOSHlt1TrackAllL0TightDecision") return idx; ++idx;
  if (name == "maxhlt1") return idx;

  idx = 0u;
  if (name == "TriggerDecHlt1DiMuonHighMassDecision") return idx; ++idx;
  if (name == "TriggerDecHlt1DiMuonLowMassDecision") return idx; ++idx;
  if (name == "TriggerDecHlt1SingleMuonNoIPDecision") return idx; ++idx;
  if (name == "TriggerDecHlt1SingleMuonHighPTDecision") return idx; ++idx;
  if (name == "TriggerDecHlt1TrackAllL0Decision") return idx; ++idx;
  if (name == "TriggerDecHlt1TrackMuonDecision") return idx; ++idx;
  if (name == "TriggerDecHlt1TrackPhotonDecision") return idx; ++idx;
  if (name == "TriggerDecHlt1LumiDecision") return idx; ++idx;
  if (name == "TriggerDecHlt1LumiMidBeamCrossingDecision") return idx; ++idx;
  if (name == "TriggerDecHlt1MBNoBiasDecision") return idx; ++idx;
  if (name == "TriggerDecHlt1L0AnyDecision") return idx; ++idx;
  if (name == "TriggerDecHlt1L0AnyRateLimitedDecision") return idx; ++idx;
  if (name == "TriggerDecHlt1L0AnyNoSPDDecision") return idx; ++idx;
  if (name == "TriggerDecHlt1L0AnyNoSPDRateLimitedDecision") return idx; ++idx;
  if (name == "TriggerDecHlt1NoPVPassThroughDecision") return idx; ++idx;
  if (name == "TriggerDecHlt1DiProtonLowMultDecision") return idx; ++idx;
  if (name == "TriggerDecHlt1BeamGasNoBeamBeam1Decision") return idx; ++idx;
  if (name == "TriggerDecHlt1BeamGasNoBeamBeam2Decision") return idx; ++idx;
  if (name == "TriggerDecHlt1BeamGasBeam1Decision") return idx; ++idx;
  if (name == "TriggerDecHlt1BeamGasBeam2Decision") return idx; ++idx;
  if (name == "TriggerDecHlt1BeamGasCrossingEnhancedBeam1Decision") return idx; ++idx;
  if (name == "TriggerDecHlt1BeamGasCrossingEnhancedBeam2Decision") return idx; ++idx;
  if (name == "TriggerDecHlt1BeamGasCrossingForcedRecoDecision") return idx; ++idx;
  if (name == "TriggerDecHlt1ODINTechnicalDecision") return idx; ++idx;
  if (name == "TriggerDecHlt1Tell1ErrorDecision") return idx; ++idx;
  if (name == "TriggerDecHlt1BeamGasCrossingParasiticDecision") return idx; ++idx;
  if (name == "TriggerDecHlt1ErrorEventDecision") return idx; ++idx;
  if (name == "TriggerDecHlt1Global") return idx; ++idx;
  if (name == "TriggerDecHlt1MBMicroBiasVeloDecision") return idx; ++idx;
  if (name == "TriggerDecHlt1MBMicroBiasVeloRateLimitedDecision") return idx; ++idx;
  if (name == "TriggerDecHlt1MBMicroBiasTStationDecision") return idx; ++idx;
  if (name == "TriggerDecHlt1MBMicroBiasTStationRateLimitedDecision") return idx; ++idx;
  if (name == "TriggerDecHlt1DiProtonDecision") return idx; ++idx;
  if (name == "TriggerDecHlt1VeloClosingMicroBiasDecision") return idx; ++idx;
  if (name == "TriggerDecHlt1SingleElectronNoIPDecision") return idx; ++idx;
  if (name == "TriggerDecHlt1TrackForwardPassThroughDecision") return idx; ++idx;
  if (name == "TriggerDecHlt1TrackForwardPassThroughLooseDecision") return idx; ++idx;
  if (name == "TriggerDecHlt1CharmCalibrationNoBiasDecision") return idx; ++idx;
  if (name == "TriggerDecHlt1L0HighSumETJetDecision") return idx; ++idx;
  if (name == "TriggerDecHlt1BeamGasCrossingForcedRecoFullZDecision") return idx; ++idx;
  if (name == "TriggerDecHlt1BeamGasHighRhoVerticesDecision") return idx; ++idx;
  if (name == "TriggerDecHlt1VertexDisplVertexDecision") return idx; ++idx;
  if (name == "TriggerDecHlt1TrackAllL0TightDecision") return idx; ++idx;
  if (name == "maxhlt1") return idx;

  idx = 0u;
  if (name == "TriggerTOSL0B1gas") return idx; ++idx;
  if (name == "TriggerTOSL0B2gas") return idx; ++idx;
  if (name == "TriggerTOSL0Calo") return idx; ++idx;
  if (name == "TriggerTOSL0DiMuon") return idx; ++idx;
  if (name == "TriggerTOSL0DiMuonlowMult") return idx; ++idx;
  if (name == "TriggerTOSL0Electron") return idx; ++idx;
  if (name == "TriggerTOSL0GlobalPi0") return idx; ++idx;
  if (name == "TriggerTOSL0HCAL") return idx; ++idx;
  if (name == "TriggerTOSL0Hadron") return idx; ++idx;
  if (name == "TriggerTOSL0LocalPi0") return idx; ++idx;
  if (name == "TriggerTOSL0MuonMinbias") return idx; ++idx;
  if (name == "TriggerTOSL0Muon") return idx; ++idx;
  if (name == "TriggerTOSL0MuonLowMult") return idx; ++idx;
  if (name == "TriggerTOSL0PU") return idx; ++idx;
  if (name == "TriggerTOSL0PU20") return idx; ++idx;
  if (name == "TriggerTOSL0Photon") return idx; ++idx;
  if (name == "TriggerTOSL0SPD") return idx; ++idx;
  if (name == "TriggerTOSL0SPD40") return idx; ++idx;
  if (name == "maxl0") return idx;

  idx = 0u;
  if (name == "TriggerDecL0B1gas") return idx; ++idx;
  if (name == "TriggerDecL0B2gas") return idx; ++idx;
  if (name == "TriggerDecL0Calo") return idx; ++idx;
  if (name == "TriggerDecL0DiMuon") return idx; ++idx;
  if (name == "TriggerDecL0DiMuonlowMult") return idx; ++idx;
  if (name == "TriggerDecL0Electron") return idx; ++idx;
  if (name == "TriggerDecL0GlobalPi0") return idx; ++idx;
  if (name == "TriggerDecL0HCAL") return idx; ++idx;
  if (name == "TriggerDecL0Hadron") return idx; ++idx;
  if (name == "TriggerDecL0LocalPi0") return idx; ++idx;
  if (name == "TriggerDecL0MuonMinbias") return idx; ++idx;
  if (name == "TriggerDecL0Muon") return idx; ++idx;
  if (name == "TriggerDecL0MuonLowMult") return idx; ++idx;
  if (name == "TriggerDecL0PU") return idx; ++idx;
  if (name == "TriggerDecL0PU20") return idx; ++idx;
  if (name == "TriggerDecL0Photon") return idx; ++idx;
  if (name == "TriggerDecL0SPD") return idx; ++idx;
  if (name == "TriggerDecL0SPD40") return idx; ++idx;
  if (name == "maxl0") return idx;



  std::cerr << "NEED CRACK!!!" << std::endl;
}

#endif
