
l0_lines = [ "L0PhysicsDecision"
           , "L0MuonDecision"
           , "L0DiMuonDecision"
           , "L0MuonHighDecision"
           , "L0HadronDecision"
           , "L0ElectronDecision"
           , "L0PhotonDecision" ]

hlt1_lines = [ "Hlt1DiMuonHighMassDecision"
             , "Hlt1DiMuonLowMassDecision"
             , "Hlt1SingleMuonNoIPDecision"
             , "Hlt1SingleMuonHighPTDecision"
             , "Hlt1TrackMuonMVADecision"
             , "Hlt1TwoTrackMVADecision"
             , "Hlt1TrackMuonDecision"
             , "Hlt1TrackPhotonDecision"
             , "Hlt1MBNoBiasDecision"
             , "Hlt1MBMicroBiasVeloDecision"
             , "Hlt1MBMicroBiasTStationDecision"
             , "Hlt1L0AnyDecision"
             , "Hlt1DiProtonDecision"
             , "Hlt1DiProtonLowMultDecision" ]

hlt2_lines = [ "Hlt2SingleElectronTFLowPtDecision"
             , "Hlt2SingleElectronTFHighPtDecision"
             , "Hlt2DiElectronHighMassDecision"
             , "Hlt2DiElectronBDecision"
             , "Hlt2B2HHLTUnbiasedDecision"
             , "Hlt2Topo2BodySimpleDecision"
             , "Hlt2Topo3BodySimpleDecision"
             , "Hlt2Topo4BodySimpleDecision"
             , "Hlt2Topo2BodyBBDTDecision"
             , "Hlt2Topo3BodyBBDTDecision"
             , "Hlt2Topo4BodyBBDTDecision"
             , "Hlt2TopoMu2BodyBBDTDecision"
             , "Hlt2TopoMu3BodyBBDTDecision"
             , "Hlt2TopoMu4BodyBBDTDecision"
             , "Hlt2TopoE2BodyBBDTDecision"
             , "Hlt2TopoE3BodyBBDTDecision"
             , "Hlt2TopoE4BodyBBDTDecision"
             , "Hlt2IncPhiDecision"
             , "Hlt2IncPhiSidebandsDecision"
             , "Hlt2MuonFromHLT1Decision"
             , "Hlt2SingleMuonDecision"
             , "Hlt2SingleMuonHighPTDecision"
             , "Hlt2SingleMuonLowPTDecision"
             , "Hlt2DiMuonDecision"
             , "Hlt2DiMuonLowMassDecision"
             , "Hlt2DiMuonJPsiDecision"
             , "Hlt2DiMuonJPsiHighPTDecision"
             , "Hlt2DiMuonPsi2SDecision"
             , "Hlt2DiMuonBDecision"
             , "Hlt2DiMuonZDecision"
             , "Hlt2DiMuonDY1Decision"
             , "Hlt2DiMuonDY2Decision"
             , "Hlt2DiMuonDY3Decision"
             , "Hlt2DiMuonDY4Decision"
             , "Hlt2DiMuonDetachedDecision"
             , "Hlt2DiMuonDetachedHeavyDecision"
             , "Hlt2DiMuonDetachedJPsiDecision"
             , "Hlt2DiMuonNoPVDecision"
             , "Hlt2TriMuonDetachedDecision"
             , "Hlt2TriMuonTauDecision"
             , "Hlt2DiMuonDetachedJPsiDecision"
             , "Hlt2DiMuonDetachedDecision" ]
