// Class: ReadMLPCJ
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLPCJ
TMVA Release   : 4.1.4         [262404]
ROOT Release   : 5.34/04       [336388]
Creator        : pseyfert
Date           : Sun Sep 15 14:37:16 2013
Host           : Linux robusta 3.2.0-4-amd64 #1 SMP Debian 3.2.35-2 x86_64 GNU/Linux
Dir            : /home/pseyfert/phd/Tau23Mu/scripts/TMVA_training
Training events: 28369
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 14
TMath::Exp(-1000*LifeTime)    TMath_Exp__M_1000_T_LifeTime_ TMath::Exp(-1000*LifeTime)    transformed decay time        1                                 'F'    [5.07596409349e-09,0.729348361492]
IPSig                         IPSig                         IPSig                         IP significance               1                                 'F'    [0.0111495917663,24.9779434204]
VertexChi2                    VertexChi2                    VertexChi2                    vertex #chi^{2}               1                                 'F'    [0.00382822961546,14.9971981049]
acos(dira)                    acos_dira_                    acos(dira)                    pointing angle                1                                 'F'    [0,0.137716650963]
pt                            pt                            pt                            p_{T}                         [MeV/c]                           'F'    [35.8559303284,34423.7578125]
min(p0_IPSig,min(p1_IPSig,p2_IPSig)) min_p0_IPSig,min_p1_IPSig,p2_IPSig__ min(p0_IPSig,min(p1_IPSig,p2_IPSig)) min. #mu IP significance             1                                        'F'    [2.21565961838,95.5455551147]
DOCAone                       DOCAone                       DOCAone                       DOCA (#mu 1 and 2)            mm                                'F'    [1.44155967519e-06,0.923672735691]
DOCAtwo                       DOCAtwo                       DOCAtwo                       DOCA (#mu 2 and 3)            mm                                'F'    [1.14804166174e-07,0.744905769825]
DOCAthree                     DOCAthree                     DOCAthree                     DOCA (#mu 1 and 3)            mm                                'F'    [6.62684851704e-06,1.05343544483]
iso                           iso                           iso                           track isolation               1                                 'F'    [0,17]
CDF3                          CDF3                          CDF3                          cone isolation                1                                 'F'    [0.0038299348671,1]
p0_track_MatchChi2            p0_track_MatchChi2            p0_track_MatchChi2            track match #chi^{2} (#mu 1)  1                                 'F'    [0.0673476010561,84.5542831421]
p1_track_MatchChi2            p1_track_MatchChi2            p1_track_MatchChi2            track match #chi^{2} (#mu 2)  1                                 'F'    [0.0131226135418,68.1548233032]
p2_track_MatchChi2            p2_track_MatchChi2            p2_track_MatchChi2            track match #chi^{2} (#mu 3)  1                                 'F'    [0.0453270226717,79.3785171509]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLPCJ : public IClassifierReader {

 public:

   // constructor
   ReadMLPCJ( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLPCJ" ),
        fNvars( 14 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "TMath::Exp(-1000*LifeTime)", "IPSig", "VertexChi2", "acos(dira)", "pt", "min(p0_IPSig,min(p1_IPSig,p2_IPSig))", "DOCAone", "DOCAtwo", "DOCAthree", "iso", "CDF3", "p0_track_MatchChi2", "p1_track_MatchChi2", "p2_track_MatchChi2" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 0.99999988079071;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;
      fVmin[11] = -1;
      fVmax[11] = 1;
      fVmin[12] = -1;
      fVmax[12] = 1;
      fVmin[13] = -1;
      fVmax[13] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLPCJ() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][14];
   double fMax_1[3][14];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[14];
   double fVmax[14];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[14];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[20][15];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][20];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLPCJ::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 15; fWeights[0] = new double[15]; 
   fLayerSize[1] = 20; fWeights[1] = new double[20]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.848603867050058;
   fWeightMatrix0to1[1][0] = 1.40387985359427;
   fWeightMatrix0to1[2][0] = 1.52865964865709;
   fWeightMatrix0to1[3][0] = 1.32321951851739;
   fWeightMatrix0to1[4][0] = -3.43021617773092;
   fWeightMatrix0to1[5][0] = -0.0339196925538559;
   fWeightMatrix0to1[6][0] = -0.609187816846313;
   fWeightMatrix0to1[7][0] = 3.43983988738097;
   fWeightMatrix0to1[8][0] = 0.328930833340438;
   fWeightMatrix0to1[9][0] = -0.966081433039265;
   fWeightMatrix0to1[10][0] = -1.61778657195269;
   fWeightMatrix0to1[11][0] = -0.774229418904968;
   fWeightMatrix0to1[12][0] = -1.70752144433142;
   fWeightMatrix0to1[13][0] = -0.232376715956144;
   fWeightMatrix0to1[14][0] = -0.464941796990424;
   fWeightMatrix0to1[15][0] = 0.125232826456074;
   fWeightMatrix0to1[16][0] = -0.302856876757704;
   fWeightMatrix0to1[17][0] = 1.24444978976981;
   fWeightMatrix0to1[18][0] = -0.00582950814286193;
   fWeightMatrix0to1[0][1] = 6.64197848540417;
   fWeightMatrix0to1[1][1] = 2.60214015848267;
   fWeightMatrix0to1[2][1] = -1.04666630571463;
   fWeightMatrix0to1[3][1] = 1.17903436392467;
   fWeightMatrix0to1[4][1] = -0.113157410514466;
   fWeightMatrix0to1[5][1] = -1.35259368475415;
   fWeightMatrix0to1[6][1] = -0.089562615935658;
   fWeightMatrix0to1[7][1] = 2.63391750212389;
   fWeightMatrix0to1[8][1] = -6.40213530248823;
   fWeightMatrix0to1[9][1] = -0.528797864139806;
   fWeightMatrix0to1[10][1] = 0.421737737815309;
   fWeightMatrix0to1[11][1] = 0.410555792026981;
   fWeightMatrix0to1[12][1] = 2.01032199840684;
   fWeightMatrix0to1[13][1] = -0.336124984514384;
   fWeightMatrix0to1[14][1] = -0.406642030035931;
   fWeightMatrix0to1[15][1] = -1.6621244161668;
   fWeightMatrix0to1[16][1] = -0.111580473581761;
   fWeightMatrix0to1[17][1] = 0.243016777944637;
   fWeightMatrix0to1[18][1] = 1.01963171400921;
   fWeightMatrix0to1[0][2] = -0.274127611468584;
   fWeightMatrix0to1[1][2] = 0.416016568350247;
   fWeightMatrix0to1[2][2] = 1.51337336663291;
   fWeightMatrix0to1[3][2] = -0.33419414979441;
   fWeightMatrix0to1[4][2] = 0.838028576830645;
   fWeightMatrix0to1[5][2] = 1.22121295233326;
   fWeightMatrix0to1[6][2] = -0.604539265158512;
   fWeightMatrix0to1[7][2] = -0.343249253117596;
   fWeightMatrix0to1[8][2] = 0.0993857791548539;
   fWeightMatrix0to1[9][2] = 0.0734137913755239;
   fWeightMatrix0to1[10][2] = 1.27543692708791;
   fWeightMatrix0to1[11][2] = 0.240481076037911;
   fWeightMatrix0to1[12][2] = 1.76809274708019;
   fWeightMatrix0to1[13][2] = 0.967952521477845;
   fWeightMatrix0to1[14][2] = -1.38077381025559;
   fWeightMatrix0to1[15][2] = 0.701577247914231;
   fWeightMatrix0to1[16][2] = -1.42022636176384;
   fWeightMatrix0to1[17][2] = -1.26863020040821;
   fWeightMatrix0to1[18][2] = -1.14951118379263;
   fWeightMatrix0to1[0][3] = 1.69393996644263;
   fWeightMatrix0to1[1][3] = 1.55610836038857;
   fWeightMatrix0to1[2][3] = 0.21523766667899;
   fWeightMatrix0to1[3][3] = -0.932342421797748;
   fWeightMatrix0to1[4][3] = -0.895207855990478;
   fWeightMatrix0to1[5][3] = -1.50564410504564;
   fWeightMatrix0to1[6][3] = 1.00719069166396;
   fWeightMatrix0to1[7][3] = 2.12220632352866;
   fWeightMatrix0to1[8][3] = -0.000994457465434554;
   fWeightMatrix0to1[9][3] = 0.325148742501992;
   fWeightMatrix0to1[10][3] = -0.527243735748286;
   fWeightMatrix0to1[11][3] = 0.441166305909109;
   fWeightMatrix0to1[12][3] = -1.04631991738935;
   fWeightMatrix0to1[13][3] = -1.03982286345975;
   fWeightMatrix0to1[14][3] = -1.60948023249731;
   fWeightMatrix0to1[15][3] = 2.68669824553459;
   fWeightMatrix0to1[16][3] = 1.59655188402533;
   fWeightMatrix0to1[17][3] = 0.851391524752003;
   fWeightMatrix0to1[18][3] = -0.451214269884687;
   fWeightMatrix0to1[0][4] = -1.49216619906001;
   fWeightMatrix0to1[1][4] = -0.959462633838883;
   fWeightMatrix0to1[2][4] = 1.71409133818533;
   fWeightMatrix0to1[3][4] = 0.487587509740664;
   fWeightMatrix0to1[4][4] = 1.5943523831141;
   fWeightMatrix0to1[5][4] = 1.42086069416161;
   fWeightMatrix0to1[6][4] = 1.44453194574431;
   fWeightMatrix0to1[7][4] = -0.576360086893451;
   fWeightMatrix0to1[8][4] = -1.55575124598147;
   fWeightMatrix0to1[9][4] = 0.208910402778682;
   fWeightMatrix0to1[10][4] = -0.128422505288684;
   fWeightMatrix0to1[11][4] = -1.87307605941919;
   fWeightMatrix0to1[12][4] = -1.9669488978744;
   fWeightMatrix0to1[13][4] = -2.08710801519238;
   fWeightMatrix0to1[14][4] = -0.603535340793192;
   fWeightMatrix0to1[15][4] = -0.0866175013152996;
   fWeightMatrix0to1[16][4] = 1.92013920411616;
   fWeightMatrix0to1[17][4] = -1.39940714594229;
   fWeightMatrix0to1[18][4] = -1.29890943836955;
   fWeightMatrix0to1[0][5] = -0.546852019516778;
   fWeightMatrix0to1[1][5] = -2.38480309123507;
   fWeightMatrix0to1[2][5] = -0.672468770330268;
   fWeightMatrix0to1[3][5] = -2.74533175889956;
   fWeightMatrix0to1[4][5] = 0.254828922961666;
   fWeightMatrix0to1[5][5] = -1.57279092984719;
   fWeightMatrix0to1[6][5] = -1.183278913267;
   fWeightMatrix0to1[7][5] = -1.20520428940109;
   fWeightMatrix0to1[8][5] = 5.45497027832361;
   fWeightMatrix0to1[9][5] = -0.826506478171437;
   fWeightMatrix0to1[10][5] = 0.960168437845817;
   fWeightMatrix0to1[11][5] = 0.096308145595709;
   fWeightMatrix0to1[12][5] = -0.582328614382696;
   fWeightMatrix0to1[13][5] = -0.672614080222041;
   fWeightMatrix0to1[14][5] = -0.0998610321239097;
   fWeightMatrix0to1[15][5] = -5.4031268807819;
   fWeightMatrix0to1[16][5] = 0.648346799775763;
   fWeightMatrix0to1[17][5] = 0.0401894177946544;
   fWeightMatrix0to1[18][5] = -0.0895755319006468;
   fWeightMatrix0to1[0][6] = -0.235427731226513;
   fWeightMatrix0to1[1][6] = 2.47043825619832;
   fWeightMatrix0to1[2][6] = 0.863493195536201;
   fWeightMatrix0to1[3][6] = 0.37996815227488;
   fWeightMatrix0to1[4][6] = 1.90983171128535;
   fWeightMatrix0to1[5][6] = -1.57958040295667;
   fWeightMatrix0to1[6][6] = -1.13125025309652;
   fWeightMatrix0to1[7][6] = 1.87603286333661;
   fWeightMatrix0to1[8][6] = 1.14491798610859;
   fWeightMatrix0to1[9][6] = 1.92926002347648;
   fWeightMatrix0to1[10][6] = 0.416377394503766;
   fWeightMatrix0to1[11][6] = 1.80972560172246;
   fWeightMatrix0to1[12][6] = -0.50785407340111;
   fWeightMatrix0to1[13][6] = -0.46687253293317;
   fWeightMatrix0to1[14][6] = -1.99328041718772;
   fWeightMatrix0to1[15][6] = 1.98623881896649;
   fWeightMatrix0to1[16][6] = 0.610465433605074;
   fWeightMatrix0to1[17][6] = -3.09259968549593;
   fWeightMatrix0to1[18][6] = 0.687363181571611;
   fWeightMatrix0to1[0][7] = -1.37077567893368;
   fWeightMatrix0to1[1][7] = -0.961417990795597;
   fWeightMatrix0to1[2][7] = 2.06339790075078;
   fWeightMatrix0to1[3][7] = 0.580386096940839;
   fWeightMatrix0to1[4][7] = -2.22311565003703;
   fWeightMatrix0to1[5][7] = 1.59430210704095;
   fWeightMatrix0to1[6][7] = 2.00589455471142;
   fWeightMatrix0to1[7][7] = 2.51003120818655;
   fWeightMatrix0to1[8][7] = -1.02821778535245;
   fWeightMatrix0to1[9][7] = -1.34663320735421;
   fWeightMatrix0to1[10][7] = 0.913923433428247;
   fWeightMatrix0to1[11][7] = -1.47305279491907;
   fWeightMatrix0to1[12][7] = 1.53918498983477;
   fWeightMatrix0to1[13][7] = 0.611887786399145;
   fWeightMatrix0to1[14][7] = -0.852246443301663;
   fWeightMatrix0to1[15][7] = 0.332908867376747;
   fWeightMatrix0to1[16][7] = 0.633226154089483;
   fWeightMatrix0to1[17][7] = -1.77117114833253;
   fWeightMatrix0to1[18][7] = 0.517758237072668;
   fWeightMatrix0to1[0][8] = 1.52614081049638;
   fWeightMatrix0to1[1][8] = -1.85346213747014;
   fWeightMatrix0to1[2][8] = 0.12353940238401;
   fWeightMatrix0to1[3][8] = 2.83433738624271;
   fWeightMatrix0to1[4][8] = 1.38450363709721;
   fWeightMatrix0to1[5][8] = 0.81805699525981;
   fWeightMatrix0to1[6][8] = 1.31518814527724;
   fWeightMatrix0to1[7][8] = -0.521410543310027;
   fWeightMatrix0to1[8][8] = -0.186307148098913;
   fWeightMatrix0to1[9][8] = 0.662646467734698;
   fWeightMatrix0to1[10][8] = 0.0270882145973126;
   fWeightMatrix0to1[11][8] = 0.364853469583669;
   fWeightMatrix0to1[12][8] = 0.694753619805728;
   fWeightMatrix0to1[13][8] = -1.20465399038493;
   fWeightMatrix0to1[14][8] = -0.847320459001068;
   fWeightMatrix0to1[15][8] = -0.330870441738777;
   fWeightMatrix0to1[16][8] = -0.433903018112416;
   fWeightMatrix0to1[17][8] = 1.03140662872002;
   fWeightMatrix0to1[18][8] = 1.90977903767985;
   fWeightMatrix0to1[0][9] = -0.69036525669299;
   fWeightMatrix0to1[1][9] = -1.27274478083985;
   fWeightMatrix0to1[2][9] = 1.25002423032147;
   fWeightMatrix0to1[3][9] = -0.417695918910782;
   fWeightMatrix0to1[4][9] = -2.41135759475527;
   fWeightMatrix0to1[5][9] = -0.501792831703985;
   fWeightMatrix0to1[6][9] = 0.366622344925223;
   fWeightMatrix0to1[7][9] = -1.96942048520006;
   fWeightMatrix0to1[8][9] = -7.0656086829823;
   fWeightMatrix0to1[9][9] = -1.15003694962208;
   fWeightMatrix0to1[10][9] = 2.80843632409903;
   fWeightMatrix0to1[11][9] = 1.9258734980793;
   fWeightMatrix0to1[12][9] = -2.08540544113575;
   fWeightMatrix0to1[13][9] = -0.709709418215023;
   fWeightMatrix0to1[14][9] = -0.800126793836896;
   fWeightMatrix0to1[15][9] = 1.35823391978473;
   fWeightMatrix0to1[16][9] = 1.9609492004361;
   fWeightMatrix0to1[17][9] = -1.2916036976465;
   fWeightMatrix0to1[18][9] = -0.242685978698584;
   fWeightMatrix0to1[0][10] = 0.183973982715985;
   fWeightMatrix0to1[1][10] = 0.318946600577866;
   fWeightMatrix0to1[2][10] = 1.88660820872025;
   fWeightMatrix0to1[3][10] = -0.740880670170969;
   fWeightMatrix0to1[4][10] = -2.46483647021753;
   fWeightMatrix0to1[5][10] = -1.35278100867747;
   fWeightMatrix0to1[6][10] = -1.71862836221709;
   fWeightMatrix0to1[7][10] = -0.0737853328504809;
   fWeightMatrix0to1[8][10] = 0.536434300480067;
   fWeightMatrix0to1[9][10] = -1.09333161131874;
   fWeightMatrix0to1[10][10] = -0.526226904427072;
   fWeightMatrix0to1[11][10] = 1.74312004949329;
   fWeightMatrix0to1[12][10] = 0.0342821415956583;
   fWeightMatrix0to1[13][10] = -1.48656048176772;
   fWeightMatrix0to1[14][10] = 1.32909662386198;
   fWeightMatrix0to1[15][10] = -0.145684436366678;
   fWeightMatrix0to1[16][10] = -0.454492752121588;
   fWeightMatrix0to1[17][10] = 0.105724245937187;
   fWeightMatrix0to1[18][10] = 0.144619457118382;
   fWeightMatrix0to1[0][11] = -0.748312780317058;
   fWeightMatrix0to1[1][11] = 2.55010506177914;
   fWeightMatrix0to1[2][11] = 0.0393868773197693;
   fWeightMatrix0to1[3][11] = -2.2995240563986;
   fWeightMatrix0to1[4][11] = -1.45382440981895;
   fWeightMatrix0to1[5][11] = 2.37775591963277;
   fWeightMatrix0to1[6][11] = 1.66250911538433;
   fWeightMatrix0to1[7][11] = 1.76310612415829;
   fWeightMatrix0to1[8][11] = -0.107220828007248;
   fWeightMatrix0to1[9][11] = 2.06810179982609;
   fWeightMatrix0to1[10][11] = -1.56540495502086;
   fWeightMatrix0to1[11][11] = 0.0264098464340157;
   fWeightMatrix0to1[12][11] = -0.0614632456445493;
   fWeightMatrix0to1[13][11] = -1.56511817202659;
   fWeightMatrix0to1[14][11] = 0.597778741746194;
   fWeightMatrix0to1[15][11] = 1.62437532304407;
   fWeightMatrix0to1[16][11] = -0.776366346921369;
   fWeightMatrix0to1[17][11] = 0.858943971277958;
   fWeightMatrix0to1[18][11] = -0.716539283133208;
   fWeightMatrix0to1[0][12] = -0.327739802044532;
   fWeightMatrix0to1[1][12] = 2.36593078526484;
   fWeightMatrix0to1[2][12] = 1.26963079063286;
   fWeightMatrix0to1[3][12] = 3.19893077204211;
   fWeightMatrix0to1[4][12] = 2.37759876044439;
   fWeightMatrix0to1[5][12] = -0.163693355136062;
   fWeightMatrix0to1[6][12] = 1.71240405717383;
   fWeightMatrix0to1[7][12] = -2.28582080364573;
   fWeightMatrix0to1[8][12] = 0.418541878089706;
   fWeightMatrix0to1[9][12] = -0.0444775066980223;
   fWeightMatrix0to1[10][12] = 0.627391619124563;
   fWeightMatrix0to1[11][12] = -0.488502825952795;
   fWeightMatrix0to1[12][12] = -2.55367415757436;
   fWeightMatrix0to1[13][12] = -0.84244482168799;
   fWeightMatrix0to1[14][12] = -1.91936258615156;
   fWeightMatrix0to1[15][12] = 0.593334573968727;
   fWeightMatrix0to1[16][12] = -1.44055796777628;
   fWeightMatrix0to1[17][12] = -0.408140613009413;
   fWeightMatrix0to1[18][12] = -1.6760169101897;
   fWeightMatrix0to1[0][13] = -1.76653199196528;
   fWeightMatrix0to1[1][13] = 0.372389113447998;
   fWeightMatrix0to1[2][13] = -0.608897958713523;
   fWeightMatrix0to1[3][13] = 0.851097674353279;
   fWeightMatrix0to1[4][13] = -1.89480261236114;
   fWeightMatrix0to1[5][13] = 0.884933339070531;
   fWeightMatrix0to1[6][13] = 2.02517694764769;
   fWeightMatrix0to1[7][13] = 0.729057670860112;
   fWeightMatrix0to1[8][13] = 0.340096676953206;
   fWeightMatrix0to1[9][13] = -1.3455561706231;
   fWeightMatrix0to1[10][13] = -0.85125728951995;
   fWeightMatrix0to1[11][13] = -0.941777918339955;
   fWeightMatrix0to1[12][13] = -1.35791623896861;
   fWeightMatrix0to1[13][13] = -0.254321891664434;
   fWeightMatrix0to1[14][13] = -0.113822797295839;
   fWeightMatrix0to1[15][13] = 1.95157705973661;
   fWeightMatrix0to1[16][13] = 0.0886188725739179;
   fWeightMatrix0to1[17][13] = -0.706157047268035;
   fWeightMatrix0to1[18][13] = -0.920577590309807;
   fWeightMatrix0to1[0][14] = 1.85285770762023;
   fWeightMatrix0to1[1][14] = 3.14869607011423;
   fWeightMatrix0to1[2][14] = 0.25581476124338;
   fWeightMatrix0to1[3][14] = -0.56681506095974;
   fWeightMatrix0to1[4][14] = -2.31596700740027;
   fWeightMatrix0to1[5][14] = 1.63572742832371;
   fWeightMatrix0to1[6][14] = 0.708147928932969;
   fWeightMatrix0to1[7][14] = 1.25062873378632;
   fWeightMatrix0to1[8][14] = -7.20928959560781;
   fWeightMatrix0to1[9][14] = -0.279895666659826;
   fWeightMatrix0to1[10][14] = 2.00778343516427;
   fWeightMatrix0to1[11][14] = 0.897206319694172;
   fWeightMatrix0to1[12][14] = 1.0210977617652;
   fWeightMatrix0to1[13][14] = 0.389540769826493;
   fWeightMatrix0to1[14][14] = 0.681518747043807;
   fWeightMatrix0to1[15][14] = 0.703896375428292;
   fWeightMatrix0to1[16][14] = -1.94040886050256;
   fWeightMatrix0to1[17][14] = -0.0743391064817144;
   fWeightMatrix0to1[18][14] = -1.94971784512587;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -0.897278265932908;
   fWeightMatrix1to2[0][1] = -0.55233557136168;
   fWeightMatrix1to2[0][2] = 0.672944519567175;
   fWeightMatrix1to2[0][3] = -1.37492553235247;
   fWeightMatrix1to2[0][4] = 0.665364409622557;
   fWeightMatrix1to2[0][5] = -0.633454202479661;
   fWeightMatrix1to2[0][6] = 0.374870434483984;
   fWeightMatrix1to2[0][7] = -0.861413106396951;
   fWeightMatrix1to2[0][8] = 1.47811275969251;
   fWeightMatrix1to2[0][9] = -0.174946335371845;
   fWeightMatrix1to2[0][10] = -0.474370522053003;
   fWeightMatrix1to2[0][11] = -0.824210734275364;
   fWeightMatrix1to2[0][12] = 1.70682366718303;
   fWeightMatrix1to2[0][13] = -1.51121000646179;
   fWeightMatrix1to2[0][14] = -1.19160317909273;
   fWeightMatrix1to2[0][15] = -1.24146894006821;
   fWeightMatrix1to2[0][16] = 0.0202261836024842;
   fWeightMatrix1to2[0][17] = 2.45600161019628;
   fWeightMatrix1to2[0][18] = 0.411178294880732;
   fWeightMatrix1to2[0][19] = 0.306634456326637;
}

inline double ReadMLPCJ::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLPCJ::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLPCJ::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadMLPCJ::Clear() 
{
   // nothing to clear
}
   inline double ReadMLPCJ::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLPCJ::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 5.07596409349e-09;
   fMax_1[0][0] = 0.721660792828;
   fMin_1[1][0] = 0.00042104543536;
   fMax_1[1][0] = 0.729348361492;
   fMin_1[2][0] = 5.07596409349e-09;
   fMax_1[2][0] = 0.729348361492;
   fMin_1[0][1] = 0.0111495917663;
   fMax_1[0][1] = 24.074131012;
   fMin_1[1][1] = 0.190648660064;
   fMax_1[1][1] = 24.9779434204;
   fMin_1[2][1] = 0.0111495917663;
   fMax_1[2][1] = 24.9779434204;
   fMin_1[0][2] = 0.00382822961546;
   fMax_1[0][2] = 14.9971981049;
   fMin_1[1][2] = 0.0220367405564;
   fMax_1[1][2] = 14.9911079407;
   fMin_1[2][2] = 0.00382822961546;
   fMax_1[2][2] = 14.9971981049;
   fMin_1[0][3] = 0;
   fMax_1[0][3] = 0.112061448395;
   fMin_1[1][3] = 0.000345266977092;
   fMax_1[1][3] = 0.137716650963;
   fMin_1[2][3] = 0;
   fMax_1[2][3] = 0.137716650963;
   fMin_1[0][4] = 35.8559303284;
   fMax_1[0][4] = 34423.7578125;
   fMin_1[1][4] = 198.006759644;
   fMax_1[1][4] = 21269.5722656;
   fMin_1[2][4] = 35.8559303284;
   fMax_1[2][4] = 34423.7578125;
   fMin_1[0][5] = 2.21565961838;
   fMax_1[0][5] = 95.5455551147;
   fMin_1[1][5] = 2.78464269638;
   fMax_1[1][5] = 51.1214294434;
   fMin_1[2][5] = 2.21565961838;
   fMax_1[2][5] = 95.5455551147;
   fMin_1[0][6] = 1.44155967519e-06;
   fMax_1[0][6] = 0.628568589687;
   fMin_1[1][6] = 3.91690700781e-05;
   fMax_1[1][6] = 0.923672735691;
   fMin_1[2][6] = 1.44155967519e-06;
   fMax_1[2][6] = 0.923672735691;
   fMin_1[0][7] = 1.14804166174e-07;
   fMax_1[0][7] = 0.568330645561;
   fMin_1[1][7] = 7.34744171496e-05;
   fMax_1[1][7] = 0.744905769825;
   fMin_1[2][7] = 1.14804166174e-07;
   fMax_1[2][7] = 0.744905769825;
   fMin_1[0][8] = 6.62684851704e-06;
   fMax_1[0][8] = 1.01704800129;
   fMin_1[1][8] = 3.12057891279e-05;
   fMax_1[1][8] = 1.05343544483;
   fMin_1[2][8] = 6.62684851704e-06;
   fMax_1[2][8] = 1.05343544483;
   fMin_1[0][9] = 0;
   fMax_1[0][9] = 12;
   fMin_1[1][9] = 0;
   fMax_1[1][9] = 17;
   fMin_1[2][9] = 0;
   fMax_1[2][9] = 17;
   fMin_1[0][10] = 0.00459374347702;
   fMax_1[0][10] = 1;
   fMin_1[1][10] = 0.0038299348671;
   fMax_1[1][10] = 1;
   fMin_1[2][10] = 0.0038299348671;
   fMax_1[2][10] = 1;
   fMin_1[0][11] = 0.0673476010561;
   fMax_1[0][11] = 74.6602020264;
   fMin_1[1][11] = 0.144289746881;
   fMax_1[1][11] = 84.5542831421;
   fMin_1[2][11] = 0.0673476010561;
   fMax_1[2][11] = 84.5542831421;
   fMin_1[0][12] = 0.0131226135418;
   fMax_1[0][12] = 68.1548233032;
   fMin_1[1][12] = 0.146247655153;
   fMax_1[1][12] = 67.7235794067;
   fMin_1[2][12] = 0.0131226135418;
   fMax_1[2][12] = 68.1548233032;
   fMin_1[0][13] = 0.117283865809;
   fMax_1[0][13] = 79.3785171509;
   fMin_1[1][13] = 0.0453270226717;
   fMax_1[1][13] = 68.506652832;
   fMin_1[2][13] = 0.0453270226717;
   fMax_1[2][13] = 79.3785171509;
}

//_______________________________________________________________________
inline void ReadMLPCJ::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 14;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   std::vector<int> indicesGet;
   std::vector<int> indicesPut;

   indicesGet.push_back( 0);
   indicesGet.push_back( 1);
   indicesGet.push_back( 2);
   indicesGet.push_back( 3);
   indicesGet.push_back( 4);
   indicesGet.push_back( 5);
   indicesGet.push_back( 6);
   indicesGet.push_back( 7);
   indicesGet.push_back( 8);
   indicesGet.push_back( 9);
   indicesGet.push_back( 10);
   indicesGet.push_back( 11);
   indicesGet.push_back( 12);
   indicesGet.push_back( 13);
   indicesPut.push_back( 0);
   indicesPut.push_back( 1);
   indicesPut.push_back( 2);
   indicesPut.push_back( 3);
   indicesPut.push_back( 4);
   indicesPut.push_back( 5);
   indicesPut.push_back( 6);
   indicesPut.push_back( 7);
   indicesPut.push_back( 8);
   indicesPut.push_back( 9);
   indicesPut.push_back( 10);
   indicesPut.push_back( 11);
   indicesPut.push_back( 12);
   indicesPut.push_back( 13);

   std::vector<double> dv(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<14;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLPCJ::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLPCJ::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
