/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

#ifndef ROOMEERKATPDF
#define ROOMEERKATPDF

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooListProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
#include "TIterator.h"

#include <vector>

class AbsDensity; 
 
class RooMeerkatPdf : public RooAbsPdf {
public:
  RooMeerkatPdf() {} ; 
  RooMeerkatPdf(const char *name, const char *title,
	        RooArgList& varList, AbsDensity* density);
  RooMeerkatPdf(const RooMeerkatPdf& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooMeerkatPdf(*this,newname); }
  virtual ~RooMeerkatPdf(); 

protected:

  RooListProxy _varList ;
//  vector<std::string> _varName; 

  TIterator* _varItr; 

  Int_t _dim; 

  AbsDensity* _density; 

  Double_t evaluate() const ;

private:

  ClassDef(RooMeerkatPdf,1) // Your description goes here...
};
 
#endif
