main: main.o MVAntuple.o Rich1DTabFunc.o
	c++-color -L/home/pseyfert/coding/v5-34-01/lib -lCore -lCint -lRIO -lNet -lHist -lGraf -lGraf3d -lGpad -lTree -lRint -lPostscript -lMatrix -lPhysics -lMathCore -lThread -pthread -lm -ldl -rdynamic -lRooStats -lRooFitCore -lRooFit -lMinuit -lFoam -lMathMore -lstdc++ -L/usr/lib -lgsl -lgslcblas -lm -m64  main.o MVAntuple.o Rich1DTabFunc.o  -o main
