/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef KMATRIX_2RES
#define KMATRIX_2RES

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class Kmatrix_2res : public RooAbsPdf {
public:
  Kmatrix_2res() {} ; 
  Kmatrix_2res(const char *name, const char *title,
	      RooAbsReal& _m,
	      RooAbsReal& _beta,
	      RooAbsReal& _phase,
	      RooAbsReal& _mlo,
	      RooAbsReal& _mhi,
	      RooAbsReal& _gammalo,
	      RooAbsReal& _gammahi,
	      RooAbsReal& _L,
	      RooAbsReal& _MB,
	      RooAbsReal& _MV);
  Kmatrix_2res(const Kmatrix_2res& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new Kmatrix_2res(*this,newname); }
  inline virtual ~Kmatrix_2res() { }

protected:

  RooRealProxy m ;
  RooRealProxy beta ;
  RooRealProxy phase ;
  RooRealProxy mlo ;
  RooRealProxy mhi ;
  RooRealProxy gammalo ;
  RooRealProxy gammahi ;
  RooRealProxy L ;
  RooRealProxy MB ;
  RooRealProxy MV ;
  
  Double_t evaluate() const ;

private:

  ClassDef(Kmatrix_2res,1) // Your description goes here...
};
 
#endif
