/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef KMATRIX_NONRES
#define KMATRIX_NONRES

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class Kmatrix_nonRes : public RooAbsPdf {
public:
  Kmatrix_nonRes() {} ; 
  Kmatrix_nonRes(const char *name, const char *title,
	      RooAbsReal& _m,
	      RooAbsReal& _M0,
	      RooAbsReal& _gamma,
	      RooAbsReal& _kappa,
	      RooAbsReal& _phi,
	      RooAbsReal& _MB,
	      RooAbsReal& _MV,
	      RooAbsReal& _J);
  Kmatrix_nonRes(const Kmatrix_nonRes& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new Kmatrix_nonRes(*this,newname); }
  inline virtual ~Kmatrix_nonRes() { }

protected:

  RooRealProxy m ;
  RooRealProxy M0 ;
  RooRealProxy gamma ;
  RooRealProxy kappa ;
  RooRealProxy phi ;
  RooRealProxy MB ;
  RooRealProxy MV ;
  RooRealProxy J ;
  
  Double_t evaluate() const ;

private:

  ClassDef(Kmatrix_nonRes,1) // Your description goes here...
};
 
#endif
